### ISSUE TITLE
Crash when player joins

### ISSUE THREAD

**Issue by mieu12** [MT-CTF/capturetheflag#1008]
Minetest 5.6.0-9fc018ded

AsyncErr: Lua: Runtime error from mod 'ctf_modebase' in callback on_joinplayer(): ...0-9fc018ded-win64\bin\..\builtin\common\misc_helpers.lua:257: attempt to index local 'text' (a number value)
stack traceback:
	...0-9fc018ded-win64\bin\..\builtin\common\misc_helpers.lua:257: in function 'formspec_escape'
	...4\bin\..\games\capturetheflag\mods\apis\ctf_gui\init.lua:159: in function 'show_formspec'
	...games\capturetheflag\mods\ctf\ctf_modebase/mode_vote.lua:43: in function 'show_modechoose_form'
	...games\capturetheflag\mods\ctf\ctf_modebase/mode_vote.lua:153: in function <...games\capturetheflag\mods\ctf\ctf_modebase/mode_vote.lua:149>
	...t-5.6.0-9fc018ded-win64\bin\..\builtin\game\register.lua:429: in function <...t-5.6.0-9fc018ded-win64\bin\..\builtin\game\register.lua:415>

**Comment by savilli** [comment]
`ctf_gui/init.lua:159` doesn't have `show_formspec` call. What version are you using?

**Comment by savilli** [comment]
What version did you download from CDB?

**Comment by mieu12** [comment]
I'm using 3.1.1.

**Comment by savilli** [comment]
It was a minetest engine issue https://github.com/minetest/minetest/issues/12412. It's fixed in https://github.com/minetest/minetest/commit/edc7df54801ab3bf30f96ac5aad6ce11a102f6b9. Update your minetest version.

**Comment by mieu12** [comment]
Thanks.
