### ISSUE TITLE
/lb should show a panel with visual properties of those who have bounty on their head

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1013]
I think the title explains well.
Since currently there is no way to do #1009 so I think this could work.
Visual properties mainly are hair colour and skin colour but it's a good idea to include eye colour as well.

**Comment by LoneWolfHT** [comment]
Those can be changed on the fly, I think a name is good enough

**Comment by farooqkz** [comment]
> Those can be changed on the fly

Yeah and `/lb` could show the latest info always

 > I think a name is good enough

I don't think it is. One will have to be real close with an enemy to recognize it by name. By visual properties, it will be much easier for people to kill those who have bounty on their head.

**Comment by LoneWolfHT** [comment]
> Any progress/thoughts on this? I've tried to do it myself but when I forked this repo and tried adding a `lb2` command, I noticed my fork doesn't have "Customize" tab and I don't know why...

That's a part of the private mod. The public API should work for you though 
https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_cosmetics/init.lua

**Comment by farooqkz** [comment]
Hmm...
How can I test my code then?
Can you give hints how to have a 3D view of a player like you do in `Customize`?

**Comment by LoneWolfHT** [comment]
> Hmm...
> How can I test my code then?
> Can you give hints how to have a 3D view of a player like you do in `Customize`?

Your code will work if it displays what the player looks like using the ctf_cosmetics function(s)

I think the classes code uses ctf_cosmetics for the class skins

**Comment by farooqkz** [comment]
And how should I display what the player looks like?

**Comment by LoneWolfHT** [comment]
> And how should I display what the player looks like?

The easiest way would probably be a `model[]` element displaying the player model with the bountied player's textures

**Comment by LoneWolfHT** [comment]
I think `ctf_cosmetics.get_skin(player)` will work for getting the correct player texture

**Comment by farooqkz** [comment]
Implemented
