### ISSUE TITLE
Why dummy backend is required?

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1014]
Hello.
I was wondering. As maximum one map at one time is played, why is it needed to have dummy backend and have all maps in memory? Which highly increases memory usage.

**Comment by Calinou** [comment]
Using the dummy backend reduces I/O usage a lot as the map no longer needs to be saved to a database on disk.

Sure, you could move this to a RAMdisk, but this is not something that is particularly straightforward to set up.

**Comment by farooqkz** [comment]
My point is that just one map is required at a time. So how about using dummy backend but loading one map at a time?

**Comment by LoneWolfHT** [comment]
I'm pretty sure we already use the dummy backend for the server

**Comment by farooqkz** [comment]
hmm okay
