### ISSUE TITLE
Make spikes damage enemies only(not teammates, not yourself)

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1021]
Depends on https://github.com/minetest/minetest/issues/8265

**Comment by LoneWolfHT** [comment]
Fixed by https://github.com/MT-CTF/capturetheflag/commit/186ef8a142bbf4eb966786141828cb23e7af3387

**Comment by farooqkz** [comment]
> Fixed by [186ef8a](https://github.com/MT-CTF/capturetheflag/commit/186ef8a142bbf4eb966786141828cb23e7af3387)

Nice but I think if we had engine support, it could be better?

**Comment by LoneWolfHT** [comment]
> > Fixed by [186ef8a](https://github.com/MT-CTF/capturetheflag/commit/186ef8a142bbf4eb966786141828cb23e7af3387)
> 
> Nice but I think if we had engine support, it could be better?

The merged method makes it easy to see what spikes will damage who, and also allows map editors to place team & teamless spikes. It's probably the best approach even with an engine change
