### ISSUE TITLE
Dual pistols

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1023]
There are so many pistols in the game. Why not gather 3 of them and craft a "dual pistol" which can its reload rate is a little better?

**Comment by LoneWolfHT** [comment]
I feel like this suggestion is lazily made/has no meat to it

**Comment by farooqkz** [comment]
I don't know what `has no meat to it` mean nor I remember my state when creating the suggestion.

However, I don't think it's a bad idea. There are so many pistols found in the chests. Why not craft 3 of them into a dual pistol for a bit enhanced weapon?

**Comment by magnetar47** [comment]
> I don't know what `has no meat to it` mean nor I remember my state when creating the suggestion.
> 
> However, I don't think it's a bad idea. There are so many pistols found in the chests. Why not craft 3 of them into a dual pistol for a bit enhanced weapon?

That crafting recipe sorta makes sense, but the idea itself doesn't. Don't we already have a wide variety of guns? Is it worth implementing the concept of dual-wielding just for this?

**Comment by farooqkz** [comment]
> > I don't know what `has no meat to it` mean nor I remember my state when creating the suggestion.
> > However, I don't think it's a bad idea. There are so many pistols found in the chests. Why not craft 3 of them into a dual pistol for a bit enhanced weapon?
> 
> That crafting recipe sorta makes sense, but the idea itself doesn't. Don't we already have a wide variety of guns? Is it worth implementing the concept of dual-wielding just for this?

It's not dual wielding. Just a new item which has picture of two pistols and has a lower reload rate comparing to current pistols.

**Comment by magnetar47** [comment]
> > > I don't know what `has no meat to it` mean nor I remember my state when creating the suggestion.
> > > However, I don't think it's a bad idea. There are so many pistols found in the chests. Why not craft 3 of them into a dual pistol for a bit enhanced weapon?
> > 
> > 
> > That crafting recipe sorta makes sense, but the idea itself doesn't. Don't we already have a wide variety of guns? Is it worth implementing the concept of dual-wielding just for this?
> 
> It's not dual wielding. Just a new item which has picture of two pistols and has a lower reload rate comparing to current pistols.

Ah, I misunderstood. So would the "dual pistol" be one physical gun with two barrels?

**Comment by farooqkz** [comment]
> 



> > > > I don't know what `has no meat to it` mean nor I remember my state when creating the suggestion.
> > > > However, I don't think it's a bad idea. There are so many pistols found in the chests. Why not craft 3 of them into a dual pistol for a bit enhanced weapon?
> > > 
> > > 
> > > That crafting recipe sorta makes sense, but the idea itself doesn't. Don't we already have a wide variety of guns? Is it worth implementing the concept of dual-wielding just for this?
> > 
> > 
> > It's not dual wielding. Just a new item which has picture of two pistols and has a lower reload rate comparing to current pistols.
> 
> Ah, I misunderstood. So would the "dual pistol" be one physical gun with two barrels?

Well this idea seems good and funny. But I was thinking to two guns(the sprite) as an item with lower reload rate than the normal pistol.

**Comment by LoneWolfHT** [comment]
I'll close this for now. Might work in an all-guns mode though
