### ISSUE TITLE
More creative grenades

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1024]
Currently in nade fight mode there are 3 kinds of grenades:
 - Green ones which damage enemies near their blast
 - Purple ones which trap enemies(and possible the user) very close to its blastplace into a block. Disallowing them to use grenades for the time being trapped and reducing the damage they deal.
 - Yellow ones which simply make the enemies and possibly the user themselves jump to some direction.

I am thinking of more kinds of grenades:

 - Blue grenade: Spawns one or more blocks of water which disappears after few seconds. Can be used to slow down enemies.
 - Orange grenade: Spawns one or more blocks of lava which disappears after some time. Can be used to slow down enemies and damage them at the same time.
 - Gray grenade: Spawns a jail(let's say a small building with no door or window) which disappears after some time. Can be used to slow down the enemies.

Regarding where do players get these special granades, I have multiple thoughts:

 - They are alternatives to the purple grenade since all three of them slow down the enemies. Players could choose which grenade they want to use similar to how they choose their class in "Classes mode"
 - People find them in chests(rarely?) or craft them(hardly?)

**Comment by farooqkz** [comment]
@LoneWolfHT Thoughts?

**Comment by LoneWolfHT** [comment]
None of the ideas stand out to me. The jail one will probably either be big enough to cause lag/other issues, or too small to be of any use, and is quite similar to what the void nade does.

I'm not sure changing a single grenade's ability would warrant a classes-like formspec

Sounds fine for a Minetest Game mod though

**Comment by farooqkz** [comment]
> None of the ideas stand out to me. The jail one will probably either be big enough to cause lag/other issues, or too small to be of any use, and is quite similar to what the void nade does.

Not sure about the lag vs usability thingie. But such a thing to trap players feels more natural in Minetest than the current void nade.

**Comment by LoneWolfHT** [comment]
> Not sure about the lag vs usability thingie. But such a thing to trap players feels more natural in Minetest than the current void nade. Though, I don't know how others will be able to damage the trapped player? Maybe add some lava?

If I wanted to make CTF more natural to Minetest I would be switching us over to Nodecore CTF :P

I'd prefer if the only blocks involved in combat are the ones players place/dig. Although I might eventually allow grenades that destroy blocks

**Comment by farooqkz** [comment]
Closing as the initial suggestions did not stand out. However if I am remembering right, there are other grenade suggestions in Discord and with a gppd number of upvotes.
