### ISSUE TITLE
Shortcuts for common phrases

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1031]
It could be useful if there were some custom shortcuts for common phrases like `behind you`. Opening chat and typing in such these situations for sure will waste a lot of time. It might be too late or you might be dead before even you could finish typing.

While the original suggestion from [here](https://discord.com/channels/447819017391046687/448136308108296213/1002194614855405598) is about text, I think a better suggestion is registering different keybindings and playing voices.

Depends on: https://github.com/minetest/minetest/issues/11446

**Comment by LoneWolfHT** [comment]
I will not register extra keybinds for this.

You can draw attention to areas by pressing `Zoom + LMB/RMB`, if that's somehow unsuitable maybe consider a clientmod

**Comment by farooqkz** [comment]
Is it possible with a CSM to play a sound on server?
