### ISSUE TITLE
Formspec text clipping

### ISSUE THREAD

**Issue by magnetar47** [MT-CTF/capturetheflag#1032]
![screenshot_20220801_222338](https://user-images.githubusercontent.com/88258122/182772233-e4c00931-7600-496b-91c2-881f7cd9378d.png)

Crucial bit of info which is so hard to understand because some important parts have been clipped by the formspec. Would love to have word wrapping or something similar. Plis fix.

FYI, this screenshot was taken with a MT res of 1366x768.

Btw I did a quick search to see if there was already an issue on this and I couldn't find any. Please feel free to close this if there is indeed an old one.

**Comment by farooqkz** [comment]
This is now solved.
