### ISSUE TITLE
Game mode suggestions: Team deathmatch and Free-for-all

### ISSUE THREAD

**Issue by magnetar47** [MT-CTF/capturetheflag#1036]
Since we have multiple game-modes now, I'd like to suggest the following *very* popular game modes, for some of my blood-thirsty comrades out there:

### Team Deathmatch

Two (or more?) teams fite each other. Match winning criteria can be one of the following:

- First team to reach total of x kills.
- Team with higher kills at the end of t minutes.

### Free-For-All

No teams **OR** teams with friendly-fire enabled, whatever is simpler to implement. Random spawn is required, but tricky to implement (see #131 for discussion on randomising spawn location) - we can't have spawns restricted to a 5x5 area in free-for-all game-mode. Match winning criteria can be one of the following:

- First player to reach total of x kills.
- Player with most kills at the end of t minutes.

----

Discussion, thoughts, implementation details, and constructive criticism welcome. :)

**Comment by LoneWolfHT** [comment]
I plan on keeping all of the modes flag-related in some way

**Comment by magnetar47** [comment]
> I plan on keeping all of the modes flag-related in some way

Ah I see. Understandable. This is "Capture the **Flag**" after all. :)

**Comment by xenonca** [comment]
I can still see the first suggestion (deathmatch) implemented without neglecting the flags. Basically a match in `classic` mode but players do not respawn when they die. I think that could be fun.

**Comment by LoneWolfHT** [comment]
Might be problematic for engagement, unless there was an option for playing something else

**Comment by magnetar47** [comment]
> I can still see the first suggestion (deathmatch) implemented without neglecting the flags. Basically a match in `classic` mode but players do not respawn when they die. I think that could be fun. EDIT: They would respawn ofc without being pointable (and visible?) and without interact, so basically spectating only.

I think that'd make them feel *very* bored very soon. In most cases, there's really nothing worthwhile to spectate (like a good match between pros), and if there is, then players surely would want to be a part of it rather than spectate. :)
