### ISSUE TITLE
Players who've just spawned can be killed by their own team-mates

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#105]
I've noticed this a couple of times - the freshly-spawned players who haven't even touched the 'floor' yet can be killed by their own team-mates.

**Comment by rubenwardy** [comment]
Ah, thanks. I tried to reproduce this but couldn't - I was missing the fact that it was due to the respawn immunity code

**Comment by AKryukov92** [comment]
I think you have two conflicting mods: ctf (teams.lua) and respawn_immunity (init.lua).
I propose to join those mods and add configuration variable "respawn immunity duration" to core.

**Comment by ClobberXD** [comment]
I think the players are 'floating' a few inches above the spawn-point, as their map wouldn't have loaded at all - it's grey all around and we can't move - this happened to me a couple of times too. There are a few exceptions when a player 'floats' above spawn-point in spite of their map having been loaded (maybe lag?)

**Comment by AKryukov92** [comment]
Do I understand you correctly:
It is possible to kill recently joined players when their world hasn't loaded yet
?

**Comment by afshaan4** [comment]
>It is possible to kill recently joined players when their world hasn't loaded yet

happened to me once.

**Comment by ClobberXD** [comment]
AKryukov92 - yes you are correct.  This generally happens when they join the game, and not after **re-**spawning (as their map would have loaded already)

**Comment by ClobberXD** [comment]
As AKryukov92 said, the `register_on_punchplayer` in `respawn_immunity/init.lua` and `ctf_pvp_engine/ctf/teams.lua` both return true, so depending on the order of insertion, one of them gets executed and the other isn't

**Comment by ClobberXD** [comment]
This bug is very rare and hard to reproduce, but players still do occasionally report being able to damage their team-mates.
