### ISSUE TITLE
Player lose immunity on picking any item

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#106]
Steps to reproduce:
- die
- pick item from the ground

result: you lose immunity and can be killed by enemy player

It is probably related to #105

**Comment by ClobberXD** [comment]
Strange - it hasn't happened to me before though...

**Comment by ClobberXD** [comment]
At times of significant lag, I lose my immunity immediately after respawn, when I hit the enemy _after_ they've killed me.

**Comment by ClobberXD** [comment]
This hasn't been reported ever since this issue was opened. This can be re-opened when someone can reproduce this again. The chances are quite remote, as the code has been streamlined by quite a bit since the creation of this issue.
