### ISSUE TITLE
Do not give pro players stuff when their connection is unstable or laggy

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1067]

**Comment by LoneWolfHT** [comment]
Neither the game or server should enforce this. The pro chest already has an minimum intelligence bar

**Comment by farooqkz** [comment]
Also this seems what we need:

https://minetest.gitlab.io/minetest/minetest-namespace-reference/

`minetest.get_player_information(player_name)`

`avg_rtt` and `avg_jitter`

**Comment by farooqkz** [comment]
@LoneWolfHT No matter how much good at PvP a player is, if the connection is unstable and unpredictable(high jitter), they can't be a Jedi and sense what will happen in the future.

**Comment by LoneWolfHT** [comment]
Lag is not constant, and is a horrible indicator of skill/survivability

**Comment by farooqkz** [comment]
Surely it's not constant but having 50%+ change in lag every moment is not something you can play and survive with it.
