### ISSUE TITLE
Allow only `singlenode` on world creation

### ISSUE THREAD

**Issue by Panquesito7** [MT-CTF/capturetheflag#1084]
### Description

On `game.conf`, we can add a field specifying which mapgens are allowed only.
AFAIK, CTF only supports `singlenode`, so, we can add this in `game.conf`:

```conf
allowed_mapgens = singlenode
```

Let me know what you think.
I'd like to create a PR for this if this is good. Thanks. 🙂

**Comment by LoneWolfHT** [comment]
CTF allows other mapgen for map creation, so we unfortunately can't do this
