### ISSUE TITLE
Treasure chests don't close after opening

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1085]
After this recent PR was merged, now treasure chests get opened after someone opens them but after that they don't get closed. They also don't have the new texture of visited chest which Xenon contributed.

**Comment by LoneWolfHT** [comment]
Open chests are visited chests

**Comment by farooqkz** [comment]
> 

Why so? Or perhaps the decision about open/close state was just about the teamchest?

**Comment by LoneWolfHT** [comment]
I prefer the open chest over the cracked chest to indicate a chest as being already opened by someone else.
If it closed again after being opened we would be back to what we had before the cracked chest texture

**Comment by farooqkz** [comment]
okay closing it
