### ISSUE TITLE
Add a recipe for poison grenade

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1104]
If you agree, I want to add a recipe for poison grenade:

`one iron lump + one smoke grenade`

**Comment by LuismiInTheZone** [comment]
> If you agree, I want to add a recipe for poison grenade:
> 
> `one iron lump + one smoke grenade`

That's very easy to get, make them 5 iron lumps

**Comment by farooqkz** [comment]
Not really. In some maps there are a lot of Iron while in some others there is no iron or so rare they are.

**Comment by farooqkz** [comment]
What is recipe of smoke grenade itself? I can't find it.

**Comment by LuismiInTheZone** [comment]
there's not one

> What is recipe of smoke grenade itself? I can't find it.

**Comment by HobbitPower** [comment]
There are already enough of them in chests for my taste. If it were craftable, I think there should be less of it to be found. Maybe you can lower the "spawn rate" of posion grenades then.

**Comment by farooqkz** [comment]
> There are already enough of them in chests for my taste. If it were craftable, I think there should be less of it to be found. Maybe you can lower the "spawn rate" of posion grenades then.

IMO, enough is not an exact value but a range. I agree there is enough but a little more on the maps with needed materials will add diversity to the game play. And to not have too many of them, I'd suggest making the recipe a bit expensive. For example 4 coal plus a smoke grenade sounds like a good one(or a close one at least). I'd not include iron as I'm afraid newbies will use all the iron for this rather than swords. And without swords at least as good as steel sword the game will be boring for most players.

One other related idea: How about adding a second recipe which is one red mushroom + one smoke nade producing one or two poison nades? In cave/underground maps no red mushroom can be found and on most maps which you can find red mushroom, you can't easily find coal. Probably the wall is an exception.

**Comment by farooqkz** [comment]
Closing as heavily downvoted on Discord.
