### ISSUE TITLE
I would like read only access to Grafana panel

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1110]
I am interested in resource usage of Minetest CTF.

**Comment by LoneWolfHT** [comment]
The server isn't currently running Grafana, I have no experience with it.

**Comment by farooqkz** [comment]
> The server isn't currently running Grafana, I have no experience with it.

So how do you monitor server resource's usage?

**Comment by LoneWolfHT** [comment]
I use `top`, and when I do it's only to make sure nothing is taking an unusual amount of resources. I use Minetest's builtin profiler for looking at mod perf

**Comment by farooqkz** [comment]
Hmm. Care to share Memory, CPU and bandwidth usage for different number of online players?

**Comment by LoneWolfHT** [comment]
That would be a lot of work to compile. I'd maybe look at doing it when my plate isn't as full.

If someone is considering making a server I'd recommend streamlining the server setup, going with a cheaper VPS to start, and upgrading as needed
