### ISSUE TITLE
Add soda vending machine to CTF

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1116]
Do you think it's a good idea to add soda vending machine which gives soda in exchange for iron or gold? And soda can regenerate sprint thing.

**Comment by LoneWolfHT** [comment]
Not in any of the current modes, it would be like apples but for flag cappers

**Comment by farooqkz** [comment]
Well I was thinking about forbidding it for flag carriers. I was also thinking about it for flagwars maybe. But it could fit in the current modes, too. We'll have to use another currency tho.

**Comment by LoneWolfHT** [comment]
Definitely possible for flagwars, feel free to add this to that mode

**Comment by farooqkz** [comment]
@LoneWolfHT you closed as "completed" not "invalid/won't add"

**Comment by LoneWolfHT** [comment]
I didn't even realize I had options for closing until now :P
