### ISSUE TITLE
Recruit another core developer

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1123]
Since LV/LW is not much available these days, I suggest recruiting another developer.

**Comment by LuismiInTheZone** [comment]
And... from where do you want to take a developer?

**Comment by farooqkz** [comment]
One candidate I guess is @olliy1or . Another alternative is cloning one of the current core developers we have.

**Comment by LoneWolfHT** [comment]
I'm always on the lookout for people who would do well as a core dev, but it's hard to find someone who fits the requirements
