### ISSUE TITLE
New class: Block spammer

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1125]
- It has very high HP or somehow is hard to kill
 - Has infinite blocks
 - It can't damage others
 
Also perhaps:
 - It takes damage only from shooter or guns excluding shotgun?
 - It takes damage only from a specific gun(pistol or the shooter rifle).

Edit: I'm feeling like my brain cannot forget NodeCore CTF :)

**Comment by LoneWolfHT** [comment]
This would probably kill CTF's entire playerbase :P

**Comment by farooqkz** [comment]
> This would probably kill CTF's entire playerbase :P

LOL. Really? Care to explain why?

**Comment by LoneWolfHT** [comment]
Block spammers are the most complained about people in CTF, other than tunnelers

**Comment by farooqkz** [comment]
> Block spammers are the most complained about people in CTF, other than tunnelers

That's true but the complains are for in combat(spamming to run away, e.g. pillars) not a class which cannot damage others.

**Comment by LoneWolfHT** [comment]
Take away the combat and you have something worryingly similar to a tunneler, I don't want to put any effort into figuring out if this is worth it or not
