### ISSUE TITLE
Poison grenades are underpowered

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1127]
I think they must deal more damage

**Comment by LoneWolfHT** [comment]
This will probably have to be a poll, I'm seeing a lot of negative reactions to your PR in Discord

**Comment by farooqkz** [comment]
> This will probably have to be a poll, I'm seeing a lot of negative reactions to your PR in Discord

Has the other poll ended yet?

**Comment by farooqkz** [comment]
\o/

**Comment by ixPost** [comment]
> > I think they must deal more damage
> 
> I agree.

Actually they should if they had a less harresing fog effect like using semitransparent circles of smoke.(Counts form smoke screen grenades to)
