### ISSUE TITLE
Shell access to the game server

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1134]
If possible, I would like to have shell access to the server to monitor network, memory and processor usage to analyze it and in result, roughly find a formula for usage of these resources per player.

**Comment by farooqkz** [comment]
Why? You can give me a restricted shell.

**Comment by LoneWolfHT** [comment]
> Why? You can give me a restricted shell.

IIRC the last time I looked at it there was greater risk of/ways to do privilege escalation

**Comment by farooqkz** [comment]
I, Farooq Karimi Zadeh, hereby verify `l433#4221` as my Discord account.
