### ISSUE TITLE
Indication of weapon score of teams

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#114]
Currently, gathering weapons from other team is important part of the game.
If you teams don't have any steel sword (on the bridge or H&L), then it is meaningless to for flag because you very likely be killed.

I propose to show amount of steel swords in each team (inventories and chests) at the top of the screen.
It will emphasize the fact that collecting of swords is important.

**Comment by afshaan4** [comment]
I second this idea.

>If you teams don't have any steel sword (on the bridge or H&L), then it is meaningless to for flag because you very likely be killed.

meaningless to us mere mortals, though I've seen ANAND and Shovelsmcgee get the enemy flag with no issue.
