### ISSUE TITLE
Add concept of dynamic maps to CTF

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1142]
It could be nice if we had "dynamic" maps in CTF. Maps which get generated each time they get loaded. Examples of such these maps can be random forests or random mazes.

**Comment by LoneWolfHT** [comment]
This is better suited for a different CTF game, or the next rewrite. It has barely any return on work investment IMO

**Comment by farooqkz** [comment]
> This is better suited for a different CTF game, or a future rewrite. It currently has barely any return on work investment IMO

Then why close this and why close it as completed?

**Comment by LoneWolfHT** [comment]
I want to have as few issues open as possible, so that they're more easily navigable.

Ignore the "as x" parts of my close messages, as I pay no attention to that option :P

**Comment by farooqkz** [comment]
This can be implemented using a third party program which on run or on request, generates a mts file using a mapgen and thus, no CTF rewrite. @LoneWolfHT Maybe reopen it?

**Comment by LoneWolfHT** [comment]
There's a reason we don't accept random sections of forest or maze as a map. It needs to be unique and thought out.

Feel free to do this as a mod for other server owners though

**Comment by LoneWolfHT** [comment]
I'm not saying it would necessarily require a rewrite to implement btw. The current goals of v3 don't fit with it, and it's a lot of work no matter what

**Comment by LoneWolfHT** [comment]
I'm not saying it would necessarily require a rewrite to implement btw. The current goals of v3 don't fit with it, and it's a lot of work no matter what

**Comment by LoneWolfHT** [comment]
I'm not saying it would necessarily require a rewrite to implement btw. The current goals of v3 don't fit with it, and it's a lot of work no matter what

**Comment by farooqkz** [comment]
> There's a reason we don't accept random sections of forest or maze as a map. It needs to be unique and thought out.
> 
> Feel free to do this as a mod for other server owners though

It's unique. Each time it's generated. However, the team balance could be a problem when generating random maps.

**Comment by LoneWolfHT** [comment]
Categorically unique maybe. A forest is still a forest even if you move all of the trees around, or swap them out with different ones
