### ISSUE TITLE
Discussion for combating the issue with multi team maps and barrier removal in them

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1146]
Currently in 4 player maps, we don't have classic barriers anymore which you can define by only 2 points and a big cube. While this works perfectly for 2 team maps which their barrier fits in a minimal cube, this isn't the case for 4 team maps. I am proposing two ideas to combat this issue:

 - Have more than one pair of points to define barrier area. In all of 4 team maps we've got as of now(2023-05-14), you can define the barrier area with exactly two pairs of positions because the barriers form a plus(`+`) shape in these maps. There is, however, one exception to this as there is a map which the barrier is placed like a `x` sign(the water academy map).
 - Have multiple cubes define the barrier area. This is a more general solution of the first proposed solution. We can have multiple pairs of positions in which we look for the red barrier to be removed from.
 
![image](https://github.com/MT-CTF/capturetheflag/assets/15038218/ed20e8a3-8cf5-4445-ac40-ea4934b5d526)

The above image shows the shape of the red barrier(in red colour) and 2 pairs of points to efficiently define where the red barrier is(the black circles). As you see this method is very efficient and most or all of the blocks(or nodes) inside the defined positions are the red barrier blocks which later are to be removed.

![image](https://github.com/MT-CTF/capturetheflag/assets/15038218/d0e7384f-3eaa-4161-ae7a-acb5beebcff9)

This second image, shows the more general solution for maps like water academy. We can make the cubes(the pairs of black circles) in a size small enough to not contain much of the map but at the same time big enough to so that we won't have too many of them to iterate over(to look for red barrier inside to delete it).

**Comment by src4026** [comment]
Reminds me of derivatives in calculus lol :joy: . Good idea by opening an issue :smile: .

**Comment by farooqkz** [comment]
> Reminds me of derivatives in calculus lol joy . Good idea by opening an issue smile .

Did you mean Integrals?

**Comment by src4026** [comment]
> > Reminds me of derivatives in calculus lol joy . Good idea by opening an issue smile .
> 
> Did you mean Integrals?

The last image looks like the diagram for derivatives and Riemann sums. The concept of tiny areas does remind me of integrals too :p.

**Comment by LoneWolfHT** [comment]
A better solution would be to search the map for barrier nodes and save their positions when the map is saved

**Comment by farooqkz** [comment]
Won't this solution require doing so for all the current maps?

**Comment by LoneWolfHT** [comment]
Yeah, so I need to implement mass-map-resaving at some point

**Comment by farooqkz** [comment]
> Yeah, so I need to implement mass-map-resaving at some point

What is format of these binary mts files?

**Comment by LoneWolfHT** [comment]
Minetest Schematic. I would rather people looked to work on other things for now though, unless they have experience working with schematics

**Comment by mrtechtroid** [comment]
Is this still an issue now? I believe that barriers now are able to have any format right?

**Comment by farooqkz** [comment]
yeah it's not an issue anymore. Thanks for reminding. Closing now.
