### ISSUE TITLE
Whispers

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1147]
I've seen this feature on PandoraBox server but I believe it could be more useful for CTF than for PandoraBox because the activity on this server.

Whisper feature in PandoraBox lets someone send a message(a "whisper") to nearby players only and not to anyone. This way first, the main chat will be less spammed with messages which are not wanted nor meant for everyone on the server and also since the whispers are shown visually different than the normal chat messages(in a different colour), it'll be easier for nearby players to notice them.

Since sending whispers with commands is really inconvenient, in PandoraBox every message prefixed with a dollar sign(`$`) is a whisper.

**Comment by LoneWolfHT** [comment]
This adds a little too much complexity to chat. If I see people requesting this I'll reopen

**Comment by farooqkz** [comment]
> This adds a little too much complexity to chat. If I see people requesting this I'll reopen

How does it add "too much" complexity?

**Comment by LoneWolfHT** [comment]
It's a separate chat based on distance from other players that you can't intuitively know. Pandorabox whispers probably work throughout the area of a CTF map anyway

**Comment by farooqkz** [comment]
> It's a separate chat based on a distance from other players that you can't intuitively grasp. Pandorabox whispers probably work throughout the area of a CTF map anyway

It's not exactly separate chat. You do a whisper by prefixing your message with a `$` and it is sent only to players around you within a tiny radius(I suggest 5 blocks).

**Comment by LoneWolfHT** [comment]
> Edit2: It was suggested by to play loud noise when someone near you places a marker.

I'm much more open to something like that. Adding color/extra utility to an existing feature.

An alternative to whispers I'd accept would be adding the speaker's distance to you in team chat

**Comment by farooqkz** [comment]
> An alternative to whispers I'd accept would be adding the speaker's distance to you in team chat

The idea of a whisper is first, not polluting the main chat and second, when you intent to chat to someone near you, they receive the message with more priority. That it is shown in different colour and a small audible notification.

**Comment by LoneWolfHT** [comment]
> not polluting the main chat

If this is an issue whispers are not the solution

> when you intent to chat to someone near you

Just /msg them.
If you want to talk to multiple people you'll need to define "near" in terms you can program into the whisper command.
CTF maps are too small to be able to logically separate/define 'near' and 'far' IMO. Resulting in you having no way of making sure you whisper who you want to whisper, or who you need to whisper, without just sending the message to at least half the players online or your whole team anyway.
You could tell the whisperer who they whispered to, but then if they didn't message who they wanted to they're probably just going to repeat the message in global chat, double messages for whoever was near them the first time.

**Comment by farooqkz** [comment]
What about defining near3 blocks away max?

**Comment by LoneWolfHT** [comment]
> What about defining near3 blocks away max?

- Consider a situation where someone is 3.1 blocks away.
- If it's just one person you want to talk to, `/msg` would be much more reliable, especially if one of you gets killed and wants to warn the other
- If it's 2-3 people that might work, but how would they know to come close to you when you want to say something? Is it a good idea to be that close together in modes like nade fight?
- More than 2-3 people and you might as well use `/t`, as 4+ people is quite often more than half your team on 4-team maps
