### ISSUE TITLE
When trying to hit void nade trapped players, only one of them gets damaged

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1153]
I am not totally sure about this, but I see the visual effect on just one of the trapped players.

**Comment by a-blob** [comment]
Yes, I've experienced this before. Only one of them takes damage.

**Comment by LoneWolfHT** [comment]
Worth double-checking that it damages everyone it traps, otherwise I think it may just be a visual bug engine-side

**Comment by farooqkz** [comment]
> Worth double-checking that it damages everyone it traps, otherwise I think it may just be a visual bug engine-side

I confirm only one of the trapped players get damaged.

**Comment by LoneWolfHT** [comment]
> I confirm only one of the trapped players get damaged.

I was talking about checking the code, which does damage everyone it traps

**Comment by LoneWolfHT** [comment]
Oh, is the name of this issue supposed to be `When trying to hit players trapped by the void nade, only one of them gets damaged` ?

That's expected/intended behavior if so. Try throwing a grenade instead

**Comment by LoneWolfHT** [comment]
Ah, line 21 of grenades.lua prevents grenades from going through objects

**Comment by farooqkz** [comment]
> Oh, is the name of this issue supposed to be `When trying to hit players trapped by the void nade, only one of them gets damaged` ?
> 
> That's expected/intended behavior if so. Try throwing a grenade instead

You mean it's fine that when more than one are trapped into a void nade, only one of them get damaged on hit? And you intended only the grenades damage ALL trapped players?

**Comment by LoneWolfHT** [comment]
> You mean it's fine that when more than one are trapped into a void nade, only one of them get damaged on hit? And you intended only the grenades damage ALL trapped players?

Yeah, items only target one person by default, and the mode is called 'Nade Fight'

**Comment by LoneWolfHT** [comment]
> Okay I will check if the grenade damage work for all trapped players or just one.

I don't think it does, unless it insta-kills every player it hits

**Comment by farooqkz** [comment]
Closing as invalid(see discussion).
