### ISSUE TITLE
Allow medic bandage to capture flags

### ISSUE THREAD

**Issue by src4026** [MT-CTF/capturetheflag#1156]
I've opened this issue to discuss the medic bandage not being able to capture flags (I haven't checked the technical name for it). I think it should be allowed to hit *only* the team flags. This may be useful as some matches are quite intense and one doesn't pay much attention to the item selected. This happened to me today and it cost a match loss. I also verified it in single player and it is indeed the case that medic bandages do not capture flags.

**Comment by LoneWolfHT** [comment]
Some tools should already have code in place to allow them to hit/take flags, the fix would probably be a matter of copying that code over

**Comment by 165135** [comment]
Tried to fix this, probably did it in the wrong way though

**Comment by src4026** [comment]
Closing since #1182 was merged.
