### ISSUE TITLE
Add /hp command to reveal your current location and HP to teammates

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1158]
This feature was requested in Discord in [this message](https://discord.com/channels/447819017391046687/448136308108296213/1115865726587256973). An example usage: You are low in HP and need medical attention. You do `/hp` and a marker similar to normal teammate-only markers will be created for your location with your name, your current HP and your maximum class HP.

**Comment by src4026** [comment]
I believe this can be closed. #1159
