### ISSUE TITLE
The smoke and poison grenades vanish if thrown right before death near bases

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1160]
Steps to reproduce:

 - Throw a poison or smoke nade near one of the bases where it can't be thrown
 - Quickly before the nade lands, die
 - The nade will return to your now dead inventory
 - You respawn and the nade will vanish

**Comment by farooqkz** [comment]
Can someone other than me confirm this?

**Comment by LoneWolfHT** [comment]
It makes sense, your inventory is cleared before your respawn inventory is populated IIRC

**Comment by Emojigit** [comment]
As reported in #1203 (a slightly different issue but technically the same problem), nades will return to the thrower's inventory if the player respawns before the nade lands. My PR also fixes this issue.
