### ISSUE TITLE
Removing stuff from enemies and putting them in teamchest must give the player some score

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#1163]
- You kill an enemy and collect their dropped items
 - You put the items in teamchest and some score is given to the one putting stuff in teamchest(who is probably the enemy killer?)
 
I think this can be implemented using item metadatas?

**Comment by LoneWolfHT** [comment]
The items should be good ores/swords/powerful guns only, and they should give score as soon as you put them in the team chest

**Comment by farooqkz** [comment]
> The items should be good ores/swords/powerful guns only, and they should give score as soon as you put them in the team chest

Regarding the last part, I've thought about that but wouldn't this make people put the items in the teamchest then immediately taking them?

If we go by valuing items like I did in #1093 we can make a threshold and give score based on items value.

**Comment by LoneWolfHT** [comment]
Any items that can stack won't work for this, because giving them metadata would complexify things

**Comment by farooqkz** [comment]
Duplicate of #1010
