### ISSUE TITLE
Add sounds on item pickup and item pickup attempt with full inventory

### ISSUE THREAD

**Issue by Calinou** [MT-CTF/capturetheflag#119]
For a more polished experience, a sound should be played when picking up an item. A different sound should be played when trying to pick up an item while having a full inventory.

If you know of any freely-licensed sounds which would fit, feel free to link them here. 😃

**Comment by ClobberXD** [comment]
- [this](https://www.zapsplat.com/music/retro-video-game-drop-item-tone/) for item pickup.
- [this](https://www.zapsplat.com/music/notification-alert/) for item pickup when inventory full.

Royalty-free sound clips obtained from [ZapSplat](https://www.zapsplat.com/sound-effect-categories/)

**Comment by Calinou** [comment]
@ClobberXD We should look for freely-licensed sound effects preferably; [Freesound](https://freesound.org/) is a good resource for this, although the sounds under CC BY-NC licenses should be avoided.

**Comment by ClobberXD** [comment]
@Calinou Will do - sadly the sounds on [Freesound](https://freesound.org/) are not as categorized as those on Zapsplat which made me turn towards the latter in the first place...

**Comment by tidle** [comment]
[Can't Pickup item](https://freesound.org/people/wildweasel/sounds/39026/)
