### ISSUE TITLE
Game freezes while loading a map

### ISSUE THREAD

**Issue by a-blob** [MT-CTF/capturetheflag#1191]
The game freezes in singleplayer while loading maps on some computers, which only happens while loading a second map after the game loads the first one after voting. This problem persists since version 3.3.0. When frozen, the player can move around but the game does not respond or teleport the player to the next map. If attempted to exit the game, Minetest freezes and crashes.

**Comment by LoneWolfHT** [comment]
How many cores do these computers have?
Are you able to wait it out? It may just be taking a long time

**Comment by farooqkz** [comment]
I had a similar problem using a VPS for a testing server. The game crashes when the match begins upon barrier removal. The problem was with low memory and the OOM killing the process. The temporary workaround was adding more swap using swapfile.

The long term solution is modifying smaller chunks of the map for barrier removal.

**Comment by a-blob** [comment]
> How many cores do these computers have? 

The current one I'm using, which has the problem, has 10.

> Are you able to wait it out? It may just be taking a long time

It does eventually load, but that's after waiting approximately 7 minutes.

**Comment by farooqkz** [comment]
How much free memory have you got on the computer?

**Comment by a-blob** [comment]
Around 10 GB.

**Comment by farooqkz** [comment]
Hmm then it probably is not the issue I was encountering

**Comment by a-blob** [comment]
No, they're pretty much idle.

**Comment by a-blob** [comment]
Funny enough, if you close the Minetest window during the 7 minutes, it continues running in the background. 
![image](https://github.com/MT-CTF/capturetheflag/assets/88883098/a6192c9e-54d6-4ae0-a616-08837df553eb)

**Comment by farooqkz** [comment]
> No, they're pretty much idle.

That's the problem then. Relying on a single core is making it take too long and crash. Are you on Windows?

**Comment by a-blob** [comment]
Yep

**Comment by 165135** [comment]
I have basically the same problem (When loading the second map in a mode **or** after that mode has already been run at least once.) The game freezes for about a 20 seconds to a minute, in the same fashion that was already described. Minetest isn't even using an entire core of cpu, practically none, and memory isn't a problem either...

**Comment by src4026** [comment]
This could also be the issue I have been facing on a CTF server that is public.:thinking:

**Comment by farooqkz** [comment]
I never had this problem. All those who have got this problem on Windows? Does anybody from Linux have this problem?

**Comment by src4026** [comment]
> I never had this problem. All those who have got this problem on Windows? Does anybody from Linux have this problem?

When I run single player on Linux, I do not run into this issue. However, I think the server that Catars runs for me is also on Linux, need to verify that once with them.

**Comment by a-blob** [comment]
Some on Windows are also not experiencing this problem, so this might not be related to the OS.

**Comment by a-blob** [comment]
Tested on Android, works fine.

**Comment by a-blob** [comment]
It seems like this is fixed now.
