### ISSUE TITLE
Decrease the difference between weapons of different types

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#120]
Currently we have following problems:
* Wood sword is useless
* If you get sword better than average, you become a god
* You can kill someone who don't even realize that you seen him

I propose to change stats of weapons to reduce difference between them.
General points:
* Steel tool is better than stone sword. steel sword is better than steel tool. same for any pair of materials of nearest quality
* Better weapons hit more often
* It should not be possible to kill anyone alone faster than in 4 seconds
* wood, stone and steel weapons are considered as "simple". Bronze, mese, diamond are considered as "advanced" mostly because they don't appear much in The Bridge and The H&L.

Currently we have following tool stats:
tool - damage / delay
pick wood - 2 / 1.2
pick stone - 3 / 1.3
pick steel - 4 / 1.0
pick bronze - 4 / 1.0
pick mese - 5 / 0.9
pick diamond - 5 / 0.9

sword wood - 2 / 1.0
sword stone - 4 / 1.2
sword steel - 6 / 0.8
sword bronze - 6 / 0.8 (bronze and steel have equal properties!)
sword mese - 7 / 0.7
sword diamond - 8 / 0.7

To calculate time to kill and amount of hits I assume that every player has 20 health and regenerate 1 health per second. Modelling is here https://docs.google.com/spreadsheets/d/1xlXBmgieZk6nkBzW6YrDllvu8WslcShlQpcMejdtVik/edit?usp=sharing
I propose following stats (tool means any of {pick, axe, shovel)}:
tool wood - 4 / 1.2 (7,2 seconds to kill, 7 hits)
tool stone - 4 / 1.1 (6,6 seconds to kill, 7 hits)
tool steel - 4 / 1.0 (6 seconds to kill, 7 hits)
tool bronze - 5 / 1.3 (5,1 seconds to kill, 5 hits OR 6,5 seconds to kill, 6 hits)
tool mese - 5 / 1.2 (4,8 seconds to kill, 5 hits)
tool diamond - 5 / 1.1 (4,4 seconds to kill, 5 hits)

sword wood - 4 / 1.1
sword stone - 4 / 1.0
sword steel - 4 / 0.9 (4,7 seconds to kill, 6 hits)
sword bronze - 5 / 1.2
sword mese - 5 / 1.1
sword diamond - 5 / 1,0 (4 seconds to kill, 5 hits)

**Comment by afshaan4** [comment]
Good idea, that would make new or just spawned players less likely to die right at their base(during the occasional spwankilling massacre)

**Comment by tidle** [comment]
working on it :+1:

**Comment by tidle** [comment]
nvm this is really hard :sweat_smile:

**Comment by AKryukov92** [comment]
I tried to implement this on local server and decided that steel should noticable be better than stone. Same for diamond ones. Steel swords are valuable resource, which dictates base tactic of the game.

General points:
* Steel tool is better than stone sword by damage. steel sword is better than steel tool. same for any pair of materials of nearest quality
* Better weapons deal more damage per hit
* It should not be possible to kill anyone alone faster than in 4 seconds
* wood, stone and steel weapons are considered as "simple". Bronze, mese, diamond are considered as "advanced" mostly because they don't appear much in The Bridge and The H&L.

So the stats of weapons and tools should be like this
tool wood - 3 / 1.2 (10.8 - 12 seconds to kill, 10-11 hits)
tool stone - 3 / 1.1 (9.9 seconds to kill, 10 hits)
tool steel - 3 / 1.0 (8-9 seconds to kill, 10-11 hits)
tool bronze - 4 / 1.4 (0.8 seconds to kill, 8 hits)
tool mese - 4 / 1.2 (7,2 seconds to kill, 7 hits)
tool diamond - 4 / 1.0 (6 seconds to kill, 7 hits)

sword wood - 3 / 1.1 (9.9 seconds to kill, 10 hits)
sword stone - 3 / 0.9 (7 seconds to kill, 9 hits)
sword steel - 4 / 1.0 (6 seconds to kill, 7 hits)
sword bronze - 5 / 1.4 (5.6-7.1 seconds to kill, 5-6 hits)
sword mese - 5 / 1.2 (4,8 seconds to kill, 5 hits)
sword diamond - 5 / 1,0 (4 seconds to kill, 5 hits)

**Comment by AKryukov92** [comment]
I thought today: why should I make mese weaker than diamonds? Both of the minerals exists only in The cave map. Both are gathered by digging. Both are used for swords and tools.
Why their properties are different?
Maybe we should make properties of diamond and mese tools equal?

**Comment by ClobberXD** [comment]
They become redundant then. If both of them are equal in all respects, why do both of them even have to exist? :)

**Comment by AKryukov92** [comment]
Why do both of them are exists now?

**Comment by afshaan4** [comment]
It's a difference in quality so you have three classes of weapons in that map

**Comment by ClobberXD** [comment]
Re-opening, as the corresponding PR (#223) is still open.
