### ISSUE TITLE
Visually indicate pro players

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#121]
Currently, all players look the same. It is not clear which players one can count on and which are not, which players are dangerous and which are not.
I propose to indicate players with access to pro-section somehow.
It should be something simple and visible from all directions. Probably colorful hat.

**Comment by afshaan4** [comment]
Hmm, that would have some interesting implications, like new players would know who to hide from, pros would be able to make calculated attacks (based on their health and the opponent).

Wouldn't that partly undo the effect of name tags not being seeable, for short range of-course.

Still, interesting.

**Comment by ClobberXD** [comment]
Interesting idea indeed, but I feel that not knowing who are pros will make the game even more challenging / thrilling, especially considering that numerous pros are playing with multiple names all the time *glares at ANAND* :P

**Comment by afshaan4** [comment]
yeah, it would make sneak attacks harder.

**Comment by AKryukov92** [comment]
I am not proposing to increase visibility of nametags of pro players nor making them visible from greater distance.
What I am asking is to show is this player complete noob or not.

**Comment by afshaan4** [comment]
ok. i think it's a good idea

**Comment by harrycode** [comment]
I like an dislike that idea. The reason why I like is because we can tell who is our lords and saviours that will make us win the round with our help. But i don't like it because people can also brag about it.

**Comment by afshaan4** [comment]
>But i don't like it because people can also brag about it.

most of the pro's i know don't brag about anything.

**Comment by harrycode** [comment]
> most of the pro's i know don't brag about anything.
Well, that's my only con solved! I love modest people.

**Comment by AKryukov92** [comment]
> most of the pro's i know don't brag about anything.

They just leave no survivors on the spawn

**Comment by ClobberXD** [comment]
@harrycode A visual distinction is no big deal compared to getting access to the pro section of the team-chest, or being able to join the server even after the user_limit has been reached - these are the **true** privileges that are brag-worthy IMO...

**Comment by ClobberXD** [comment]
A checkered-shirt (instead of plain blue/red) maybe?

This distinction will encourage new players to actually play the game the way it is intended, instead of building houses by the beach and wondering why `/protect My House` is not working...

**Comment by afshaan4** [comment]
>This distinction will encourage new players to actually play the game the way it is intended, instead of building houses by the beach and wondering why /area_pos1 isn't working..

XD

Oh and don't forget: making houses of their own with materials obtained by breaking the base and it's defenses.

**Comment by afshaan4** [comment]
Let's, implement and try it out?

**Comment by LoneWolfHT** [comment]
Maybe something like the character_creator mod for CTF. But one that only allows the changing of a hat and shoes?

**Comment by DS-Minetest** [comment]
>something like the character_creator mod

Nah, it should be uniform.

Apart from the texture, the model size could be slightly increased.
And in the chat the pro comments should be better readable to allow giving commands to beginners.

**Comment by MinetestSam** [comment]
I feel like the pro criteria needs to be made better before this can be added and also if you visually differenciate a pro then it will easy to target the pro in situations when there are unbalanced teams and this won't be great in Caverns as you would be easily able to differentiate between a noob and a pro

**Comment by AKryukov92** [comment]
Actually, by "pro" here I mean "players who is skilled in combat higher than average".
It doesn't have to be associated with special section in chest. Though, it might be the same.
Criteria of visual indication might be based on total rankings.
For example: "only top 10% of players by score get team-colored pants".

I don't really understand your concern. Whole idea is to "make it easy to differentiate between a noob and a pro". You are saying that it will be an issue.
Unbalanced teams is other issue, that needs to be fixed, regardless of the map. I don't have any exact ideas what to do with it. If had had any, I'd make an issue with proposal.

**Comment by masterleo** [comment]
Realy NOT a good idea !!
I have a ratio of more than 2 in game, and if I know I would target noobs so much !!!
