### ISSUE TITLE
Water flow on barrier removal not working on Plains of the Past

### ISSUE THREAD

**Issue by Emojigit** [MT-CTF/capturetheflag#1211]
As reported by @HobbitPower in a [Discord message](https://discord.com/channels/447819017391046687/448136831385468930/1141693318019952640), 
> btw @Emojigit idk why but for the Plains of the Past map the 'barrier water bug' is still the case. For other maps with water it just worked fine.

The content ID of the water sources in Plains are normal, so there is nothing to do with the map placement. The reason is still unknown.

**Comment by Emojigit** [comment]
Reason found: Barrier area parameter in `map.conf` limited the loaded area. As we are checking water source blocks only within the loaded area, water sources are not detected and hence, not generated in barriers.

**Comment by LoneWolfHT** [comment]
Probably need to fix this when we do map-calculated barrier removal

**Comment by Emojigit** [comment]
> Probably need to fix this when we do map-calculated barrier removal

I have a fork branch where I am working on barrier nodes that turn into water, lava or air without checking for adjacent liquids. This will be a performance boost and fixes this problem.

**Comment by LoneWolfHT** [comment]
Should be fixed now
