### ISSUE TITLE
Idea: CTF DevTest Server

### ISSUE THREAD

**Issue by SaiPanneerselvam** [MT-CTF/capturetheflag#1224]
I think that Capture the Flag should have a Development Testing Server and an official website (optional). The capture the flag development testing server can connect to the actual CTF Servers and also pose as an extra server in case CTF ever gets full.

**Comment by farooqkz** [comment]
I'm considering launching a small experimental server. But I can do it once I'm back from my research.

**Comment by farooqkz** [comment]
Okay I think I'll be running an Experimental CTF on ctf.farooqkz.ir in a few days. I'm currently running it from this repo's master but in future I plan to use my own master where I will experiment things. The first thing to experiment is probably going to be TNTs.

BTW, Donations are welcome for keeping the server up. Just do a top up at https://pay.privex.io/top-up with my email:

fkz on riseup dot net

**Comment by SaiPanneerselvam** [comment]
All right, maybe we can scratch out the idea of connections to main server.

Sent from GitDeKit for AlcoveOS

**Comment by farooqkz** [comment]
@LoneWolfHT  Should we be closing this? I've launched an experimental server.

**Comment by LoneWolfHT** [comment]
The main server is the best possible test server. One to handle player overflow is a different issue, and one that's probably solved by the existence of other servers like JMA.

My ideal solution would probably be a launch script for CTF that moves the game back a commit whenever there is a crash, making the server stable again until the issue can be fixed, and resets to the latest point in the master branch whenever there's a new commit.
