### ISSUE TITLE
Update https://ctf.rubenwardy.com/ copyright

### ISSUE THREAD

**Issue by SaiPanneerselvam** [MT-CTF/capturetheflag#1225]
Noticed that the copyright in https://[ctf.rubenwardy.com](https://ctf.rubenwardy.com/)/ is dated 2022. Would like if it is moved to 2023, or even 2024, knowing that it is almost the end of the year?

**Comment by LoneWolfHT** [comment]
That'll be fixed soon, I'm about to update the header/background image
