### ISSUE TITLE
Add sounds to be played on flag returned

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#123]
If the flag-bearer has been killed / timed-out, a sound could be played to get the attention of the other players, who might not otherwise notice immediately, especially if the flag had been picked up a long time ago. @rubenwardy suggested a 'dull thud' sound, but I think it might sound too similar to the sound played when a player takes damage (which sounds like a thud too).

**Comment by afshaan4** [comment]
Maybe like a sad trumpet sound.

**Comment by ClobberXD** [comment]
That would be ideal - it would be perfect if this sounds like the reverse of the sound played when the flag has been picked up.

**Comment by AKryukov92** [comment]
What about https://github.com/Elkien3/kingdoms_game/blob/master/mods/soundblocks/sounds/soundblocks_trumpet.ogg
There are more sounds with license "CC BY-SA"

**Comment by afshaan4** [comment]
>What about https://github.com/Elkien3/kingdoms_game/blob/master/mods/soundblocks/sounds/soundblocks_trumpet.ogg

that one sounds too happy.

**Comment by ClobberXD** [comment]
@afshaan4 true - it should sound like the exact opposite of the sound played when the flag has been picked-up - if I _could_ get my hands on that audio file, I could try recording it in reverse...

**Comment by AKryukov92** [comment]
Actually, there are two audio files in the ctf_flag repository https://github.com/rubenwardy/ctf_pvp_engine/tree/e2a59cef6eba80464af5414d89c4e1c6fbfd597c/ctf_flag/sounds
One sound is "trumpet win" and other - "trumpet lose". I assume that "win" sound is played when your teammate picks the flag and "lose" - when your enemy picks your flag.
Thats why we need TWO sounds: one will be played when your teammate loses flag and other - when your enemy loses flag.

**Comment by ClobberXD** [comment]
- [This](https://www.zapsplat.com/music/short-saxophone-jazzy-riff/) can be played when the **enemy's flag has been returned**.
- [This](https://www.zapsplat.com/music/multimedia-alert-tone-chime-bright-positive/), [this](https://www.zapsplat.com/music/multimedia-musical-tone-chime-goodbye-or-logout-etc-1/) or [this](https://www.zapsplat.com/music/game-win-or-gain-stars-x-2-end-of-level-tone/) can be played when **our flag has been returned**.

_Royalty-free sound-clips obtained from [ZapSplat](https://www.zapsplat.com/sound-effect-categories/)_

**Comment by AKryukov92** [comment]
I like the sound of *enemy's flag has been returned*. It is more consistent with rest of the flag sounds.
But non of *our flag has been returned* really fit to the trumpet-theme.

**Comment by afshaan4** [comment]
Maybe for "our flag has returned", it can be a *relieved* trumpet.

**Comment by ClobberXD** [comment]
The suggested sounds in my last post aren't actually royalty-free, and Zapsplat has to be mentioned. So I'll delete that post and look for new ones... sorry!
