### ISSUE TITLE
Convert all MTG mods to submodules

### ISSUE THREAD

**Issue by Panquesito7** [MT-CTF/capturetheflag#1268]
### Description

To keep the desired MTG mods up-to-date, we should convert them to Git submodules.
Here are all the MTG mods separated per repository, which can be easily accessed and are always up-to-date: https://github.com/minetest-game

**Comment by farooqkz** [comment]
@LoneWolfHT Do you agree with this?

**Comment by LoneWolfHT** [comment]
Minetest game is in a feature freeze and is rarely updated. Submodules can be a pain so I'd prefer not to change the current setup
