### ISSUE TITLE
Shift-clicking items from/into team-chests doesn't work

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#129]
Probably due to the modified formspec of the team-chest with respect to the default chest.

**Comment by ClobberXD** [comment]
`listring[]` is missing... But does listring work with more than 2 lists?

We do need a separate pro-chest sometime soon, just sayin'.... ;)

**Comment by LoneWolfHT** [comment]
liststring[] connects the last two inventory lists registered

**Comment by ClobberXD** [comment]
`listring[]` not `liststring[]` - It creates a ring of lists :)

`listring[]` is a short-hand way to create a ring using the last two lists registered, but it can also be used with an explicit listname as param, to manually connect more than two lists to the ring.

**Comment by LoneWolfHT** [comment]
I think it's good as it is now. It slows you down if you're a team griefer trying to empty the team chest. I haven't really missed not being able to shift click either

**Comment by ClobberXD** [comment]
I consider it essential in situations where one respawns in the middle of a raging war, and has to gear up ASAP, to get out there and help their team-mates.

**Comment by AKryukov92** [comment]
I'd like to limit team griefers by invention of currency as discussed in #232  not by reducing time to do trivial actions.

**Comment by masterleo** [comment]
Yes this is verry annoying, even when you want to put stuff IN

**Comment by shivajiva101** [comment]
see https://github.com/MT-CTF/capturetheflag/pull/294
