### ISSUE TITLE
Discussion regarding separation of team spawn from flag

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#131]
Players could be made to spawn on the outer edge of their flag's protective 3-block radius. This prevents the players' selection boxes from interfering with the flag. Maybe randomize the same by having 4 spawn-points per team (one every corner of team base's square floor as shown below)

**`@  !  !  !  @`**
**`!  !  !  !  !`**
**`!  !  #  !  !`**
**`!  !  !  !  !`**
**`@  !  !  !  @`**

**`@`** Spawn-point
**`#`** Team-base / Flag position
**`!`** `ctf_team_base:ind_cobble`

**Comment by afshaan4** [comment]
I agree on this idea, it would make the base less cluttered.

**Comment by ClobberXD** [comment]
The four-corner implementation still makes the base a little cramped, and those who don't know the game will still remain in their bases throughout the match, making no difference whatsoever. What could be done to alleviate this is to randomize player spawn, so that players would spawn anywhere on their side of the map.

The only issue with this approach seems to be team-chest access. The team-chest formspec could be added as an sfinv page so that it can be accessed from anywhere by pressing `I`, but this ends up being a bit too OP.

Please express your opinions as to how the team-chest access issue can be resolved.

**Comment by ClobberXD** [comment]
I'm planning to try out a multi-storey team-base implementation, with the flag on the top floor, and spawn + team-chest below (or vice-versa). Instead of giving 2 flags to a map-maker, two place-holder items should be given which can only be placed if there's enough space for the multi-storey team-base.

**Comment by ClobberXD** [comment]
Separating the static spawn-point from team-base (a.k.a flag pos) requires a change in `ctf_pvp_engine`: rubenwardy/ctf_pvp_engine#21

**Comment by ClobberXD** [comment]
Any thoughts on how team spawn can be separated from the flag?

- The 4-corner spawns idea in the OP isn't really feasible at the moment, as `ctf_pvp_engine` only supports a fixed offset from the flag.
- Random spawns isn't going to be a thing any time soon, as the spawnpoint selection needs to be very robust - we can't afford to spawn players in an underground cave because the algo thought it was the surface due to the presence of air. This can't be fixed by defining a static y-height as the surface, because of undulated terrain.

**Comment by Thomas--S** [comment]
How about spawning players randomly in the 5x5 base area?

**Comment by ClobberXD** [comment]
Best of both worlds, I like this simple yet effective solution. :)

**Comment by ClobberXD** [comment]
Attended by #437
