### ISSUE TITLE
HOW to apply for moderator

### ISSUE THREAD

**Issue by SaiPanneerselvam** [MT-CTF/capturetheflag#1329]
I see lot of people who are spamming, writing all caps, and finding ways to type innapropriate words. I logon often, so if i have moderator, I will be able to kick such people.

**Comment by mrtechtroid** [comment]
Hi there, to apply to become a Guardian (moderator) you need to join the Discord server, and ask in the `privs_role_request` channel. Please dont create requests in the github.

**Comment by farooqkz** [comment]
Yeah it's like @mrtechtroid said. Closing it as invalid.
