### ISSUE TITLE
Kick out non-participants

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#142]
The code could monitor a player's kills, and flag attempts (also their distance with respect to base if needed) to kick them out for non-participation if necessary. This way, they don't waste server resources, and are kicked even if they're not AFK.

**Comment by afshaan4** [comment]
what if they are building defences throughout the match?

**Comment by Gaara95** [comment]
XD so true!

**Comment by afshaan4** [comment]
Yea maybe forcing players to kill at least *once* in a match will be beneficial

**Comment by Coder12a** [comment]
Wait what about the happy campers? What happens to them?

**Comment by ClobberXD** [comment]
That's another valid tactic. Note that this is just a rough idea at present. It'd be great if this takes shape though.

**Comment by MinetestSam** [comment]
A player surely has to go out of the 3 by 3 area to loot chest and get resources so those who remain inside the base area get kicked?

**Comment by ClobberXD** [comment]
Some keep building and wait until a team-mates drops off some loot in the team-chest. So, no.
