### ISSUE TITLE
Add more player classes(by score)

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#147]
Currently there are just pro and non-pro. How about adding more classes for higher scores?
I'm not sure about it but I have a few ideas:
 - visually or with a tag after their name or both indicate them. (Related: https://github.com/rubenwardy/capturetheflag/issues/121)
 - add more sections to the chest. not necessary for all grades/classes.
 - give more score to players who kill them

**Comment by rubenwardy** [comment]
This request doesn't make sense. Pro is just a name for the boundary which allows you to use a section of the chest.

Are you asking for more sections? A visible "rank"?

**Comment by farooqkz** [comment]
> Are you asking for more sections?

Not necessary.

> A visible "rank"?

Yes
I'll soon update the first post.

**Comment by farooqkz** [comment]
"I'm a pro!"

**Comment by Gaara95** [comment]
And what would being able to gloat do?

**Comment by farooqkz** [comment]
I don't understand.

**Comment by ClobberXD** [comment]
> How about adding more classes for higher scores?

Please clarify.

> add more sections to the chest. not necessary for all grades/classes

I understand the first part, but the second part is not comprehensible. I also suggest making the chest "bigger" before cramming it further with more sections and their accompanying labels...

> give more score to players who kill them

That's already the case - Killing pros obviously gives more points than killing noobs.

**Comment by farooqkz** [comment]
@ClobberXD, E.g from 0 to 1K are noob/no grade, from 1K to 10K are pro, from 10K to 100K are superpro, ...
This is just an example, we could discuss about names and ranges.

> I also suggest making the team- chest "bigger" 

It's a while which I have this idea in my mind and I think it's a good idea, how about opening another issue for that?

**Comment by ClobberXD** [comment]
@farooqkz - While I'd love to see some arcade levels and achievements in-game, I also feel that the game would digress from its simplicity and objective (which is just to capture the enemy's flag) - so here's my vote --> `/abstain` :+1::-1:
