### ISSUE TITLE
TNT and Bomb

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#15]
Good for knocking walls down quickly.

**Comment by ClobberXD** [comment]
`@ Weapons`

**Comment by MinetestSam** [comment]
I think it can be worked on once the lag is reduced. But would you want TNT to throw the entities or just destroy the wall and leave no entities such as dirt,cobble,etc.

**Comment by MisterPrintf** [comment]
Oh yesss please.

I can't tell you how many times I've tunneled to an enemy's base, only to get caught at the last second digging through the wall.

TNT, on the other hand, could be stacked up underneath the appropriate wall. Wait for the right moment, and the enemy now has a gaping hole in their defenses.

**Comment by farooqkz** [comment]
Why was this closed? Is it a won't add? or what?

**Comment by LoneWolfHT** [comment]
We went through and closed issues for the old codebase, this issue is a "likely won't add" for classes, which is what it would automatically point at

**Comment by farooqkz** [comment]
Why would it point at classes? And why is it a wont add?

**Comment by LoneWolfHT** [comment]
Classic is in a feature freeze state, and nade fight isn't a terrain-focused mode.
I'm open to this being a solution to something, if it's a good one, but otherwise it's just going to be one more thing I need to balance, and my plate is plenty full of that right now
