### ISSUE TITLE
Uncraftable things request thread

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#152]
- [x] Bronze ore

**Comment by ClobberXD** [comment]
@rubenwardy The title seems to be unclear, could you please elaborate in the first post?

**Comment by rubenwardy** [comment]
Some things aren't craftable, this thread is to list and consder items which aren't but should be

**Comment by Thomas--S** [comment]
- [ ] Sandstone
- [ ] Sandstone Brick
- [ ] Stone
- [ ] Stone Brick

**Comment by rubenwardy** [comment]
Stone is already craftable with a furnace

**Comment by AKryukov92** [comment]
There is no such thing like "bronze ore" because bronze is an alloy.

**Comment by ClobberXD** [comment]
@AKryukov92 he probably meant "Bronze ingot"

**Comment by Thomas--S** [comment]
- [ ] Ammo

**Comment by ClobberXD** [comment]
@Thomas--S I think all the craft-recipes from the shooter mod have been disabled intentionally.

**Comment by AKryukov92** [comment]
@ClobberXD, bronze ingot was craftable since Cave map was introduced.

**Comment by farooqkz** [comment]
- [ ] Boat

**Comment by afshaan4** [comment]
I second adding  stairs

**Comment by ClobberXD** [comment]
> Boat
IIRC, players attached to entities are immune to punches; unless that's fixed, I don't think boats would be added...

**Comment by Thomas--S** [comment]
@ClobberXD Seems to be fixed in 5.0.0-dev: https://github.com/minetest/minetest/commit/ba91624d8c354bac49c35a449029b6712022d0cb

**Comment by ClobberXD** [comment]
Ah, I see. Good to know
