### ISSUE TITLE
Lighting issues with LVM schem placement

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#169]
(Introduced with 7732d0c2)

The caverns are perfectly lit. No lighting anomalies, whatsoever.
![caverns](https://user-images.githubusercontent.com/36130650/41816718-bf4bd276-77a9-11e8-809e-f7e885bdd745.png)

Random chunks with incorrect lighting here:
![dark_2h2l](https://user-images.githubusercontent.com/36130650/41816719-bfab4800-77a9-11e8-9ef2-4c0d6ed2079b.png)

Initially, the whole map is well-lit. When the barrier's removed, a dark strip is created right where the barrier was, before.
![dark_bridge](https://user-images.githubusercontent.com/36130650/41816720-bfe4319c-77a9-11e8-9325-adcb955f3aa5.png)

Second time the schem is placed; map goes completely dark.
![dark_bridge_2](https://user-images.githubusercontent.com/36130650/41816721-c0313ea6-77a9-11e8-9751-94f3fa52a2d2.png)

After restart, lighting issues start from square 1. i.e. dark strip in the middle

**Comment by ClobberXD** [comment]
Closing as this is an upstream issue

**Comment by ClobberXD** [comment]
Experimenting with this again, and it seems like the dark strip across the middle can be fixed by a very trivial change. Reopening as this does not seem to be an upstream (engine) issue.

**Comment by ClobberXD** [comment]
Just found out - this bug was introduced in ae8005a. This commit, which was supposed to fix some lighting bugs, actually created the nastiest one of them all :P

More specifically, this line here:
`minetest.set_mapgen_params({mgname = "singlenode", flags = "nolight"})`

Going through the docs, it looks like `nolight` sets the default light level of the whole world to 0. When `vm:write_to_map()` is called, the lighting is re-calculated, but in this case, the re-calculated lighting is set to match 0, due to `nolight` mapgen param being set.

Changing this to the following **fixes the dark strip**:
`minetest.set_mapgen_params({mgname = "singlenode", flags = "light"})`

![screenshot_20181128_203721](https://user-images.githubusercontent.com/36130650/49161593-2d227900-f34f-11e8-9d6e-e4bb65f070f4.png)

**Comment by rubenwardy** [comment]
The no light was to fix lighting issues on cavern maps

**Comment by ClobberXD** [comment]
Yes, I now see the issue. Caverns is as well-lit as an outdoor map in mid-day...

I attempted to set and unset mapgen flags during runtime but apparently that wasn't allowed. I'll continue to experiment with this as I'd really like to have LVM schem placement - The performance improvements (over normal schematic placement) are extraordinary as I noted in the original PR.

**Comment by ClobberXD** [comment]
Would exporting lighting data of the schem be a viable fix?

**Comment by rubenwardy** [comment]
closed as reverted
