### ISSUE TITLE
Awards

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#17]

**Comment by est31** [comment]
If awards get added, they should be displayed in a non obstrusive way. Getting a "hey you just ate your 100th apple" award while you are 2vs2 battling another player is bad.

Perhaps display them when the match ended, somewhere next to the rankings?

**Comment by rubenwardy** [comment]
Awards are on the HUD, not formspec. But I guess it could be distracting.
And I don't like the idea of an apple eating one.

**Comment by rubenwardy** [comment]
* Bounty Hunter - Kill 50 bounties
* That was close - Kill someone when you only have 1 HP left
* To the brink and back - Get to 1HP, then survive for 20 seconds
* Evening by the fire - Die in lava five times in a row
* Noob - say "hacker", "hack", or "unfair" after dying
* Killing Spree - n kills without dieing
* Quadrakill - 4 kills in a row
* Immortal - Kill more than 50 people and have no deaths in a single match
* Canary - be the first to die in a match

**Map-specific**

* Flash - Get to the center cavern in Caverns first

**Comment by ClobberXD** [comment]
All-time achievements could be shown in the player's profile (a.k.a `/rankings`), and per-match achievements could add to the player's match score.

**Comment by afshaan4** [comment]
>??? - Get a K/D above 10

Call this one "epyc gamer"

**Comment by Gaara95** [comment]
Sniper- Kill 5 people with a gun in a single round
Snyper king- Kill 50 - 100? people with guns in total

**Comment by AKryukov92** [comment]
I think we should implement GUI and any 1 achievement in 1 PR. Just for example.
Then implement all additional achievements. Each one in a separate PRs. It will be easier to test them.

**Comment by rubenwardy** [comment]
* SQLite or some sort of NoSQL db should be added to https://github.com/rubenwardy/awards
    * Offline players should be stored in the DB, online players cached in memory.
* awards mod should contain no awards
* ctf_awards for ctf awards

**Comment by AKryukov92** [comment]
It is up to you to choose dB.
I think mongo is overkill. We don't have millions of players.
You are using redid for world now. Right? Can we use it instead of new other database?

**Comment by Emojigit** [comment]
> **All-time**
> 
>     * Bounty Hunter - Kill 50 bounties
> 
>     * ??? - Get a K/D above 10
> 
> 
> **Events**
> 
>     * That was close - Kill someone when you only have 1 HP left
> 
>     * To the brink and back - Get to 1HP, then survive for 20 seconds
> 
>     * Evening by the fire - Die in lava five times in a row
> 
>     * Noob - say "hacker", "hack", or "unfair" after dying
> 
>     * Nice Try - Be killed in the enemy's base whilst holding the flag
> 
> 
> **Match-specific**
> 
>     * Killing Spree - n kills without dieing
> 
>     * Quadrakill - 4 kills in a row
> 
>     * Immortal - Kill more than 50 people and have no deaths in a single match
> 
>     * Canary - be the first to die in a match
> 
> 
> **Map-specific**
> 
>     * Flash - Get to the center cavern in Caverns first

@rubenwardy I will work on this
