### ISSUE TITLE
Two separate detached inventories for team-chest

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#180]
Issue type: Feature request / Discussion

This way, the pro-chest is technically separate, but physically it's the same. Both pros and noobs will get 32 slots each, which is ample even with many pros on the same team.

Will submit my PR in a day if this idea is approved.

**Comment by AKryukov92** [comment]
I think, that pro-section should be somehow visible for beginners. I consider this as motivation to play good to reach it.

**Comment by ClobberXD** [comment]
@Thomas--S Good idea, but the draw-back of this approach is that players won't be able to directly shift items between both sections.

If pros should be access the other section, then both of them would've to be crammed into the same section side-by-side, which requires the size of the sfinv pages to be increased a lot.

**Comment by Thomas--S** [comment]
@ClobberXD I don't see why direct shifting isn't possible then.

You could show the pro tab to pros by default with a listring for the pro section; for beginners, the other section is shown by default with a listring for this section.
