### ISSUE TITLE
Automatic, team only, opening and closing doors (pressure plates)

### ISSUE THREAD

**Issue by DevyHeavy** [MT-CTF/capturetheflag#181]
Pressure plates or something like it need to be added to this game. Right now, you can spend hours making a base only for your team to leave a door open (all the time) and letting the enemy in and out easy.

I feel like the plates should be team specific. If a blue player places a plate by a blue placed door then it will open, but it will not open red doors.

Also, they should spawn in chests and be craftable.

It's very frustrating to spend an hour making an awesome base only for your teammates to ruin by leaving the door open.

**Comment by CLtheman1** [comment]
Yeah. I hate it when there's a door and they just keep it open and not close it behind them. I would like to have these pressure plates in game.

**Comment by ClobberXD** [comment]
Should this be added to `doors` mod itself? @rubenwardy

**Comment by AKryukov92** [comment]
I'd like to propose other option: Close door automatically after some time.
Addition of pressure plates is unnecessary complication.
Stupid teammates can just remove pressure plates and then leave door open.

**Comment by MinetestSam** [comment]
I haven't seen many players entering through doors, generally they break walls. Also you can use the open/closed position of the door and the door would open differently.
