### ISSUE TITLE
[Discussion] Store player rankings instead of calculating them at run-time

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#183]
### Advantages
- Automation of rank-based incentives. e.g. Auto-granting of `vote_starter` to players who enter the top 20 and revoking it from those who are pushed out of it.
- No calculation required every time `/rankings` is invoked. Just fetch the rank from the `ctf_stats` mod storage like the other stats.

### Disadvantages
- One-time migration, when the ranks of all players have to be calculated and stored.
- Updating a player's rank for _every_ kill. Maybe update only once at end of match?

**Comment by Thomas--S** [comment]
I think that the `vote_starter` priv should be granted manually. Being in the top 20 doesn't neccessarily qualify someone to use this priv responsibly; while a trustable player at rank 25 (as an example) might make good use of this privilege for the benefit of all. So a manual verification is absolutely neccessary, imho.

**Comment by rubenwardy** [comment]
This would bloat the file storage if done badly. Would be better to add some caching instead

**Comment by ClobberXD** [comment]
@Thomas--S I agree, we definitely should grant `vote_starter` on the basis of a more robust criteria. That was just an example for rank-based/score-based automation though.

@rubenwardy That's true. Any idea how this can be achieved by adding some sort of caching?

**Comment by AKryukov92** [comment]
How much disk space do you have, rubenwardy?
Log files are usually contain text, which is very lightweight. Zipping files can reduce disk space even further.
