### ISSUE TITLE
Player Classes

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#19]
https://github.com/MT-CTF/capturetheflag/pull/389

**Comment by ObaniGemini** [comment]
Maybe that player classes could change the begginer stuff ?

2 Needed classes :
- Builder : has more blocks and less weapons
- Warrior : has more weapons at beggining

Or if that isn't possible, maybe make at least a class with more health, and a class going faster ( for speed changes you can still get inspiration with that mod : https://github.com/MinetestForFun/server-minetestforfun/tree/master/mods/sprint )

**Comment by farooqkz** [comment]
@rubenwardy What do you mean by classes? the idea of @ObaniGemini or arranging players by their scores(which is currently pro and non-pro)

**Comment by rubenwardy** [comment]
Builder
Warrior
Archor / Shooter

And variations of such. Each of these have different starting items and bonus to different weapons. For example, an archer has less HP so is more suseptiple to swords, but can move slightly faster and is more accurate with guns and crossbow

This is a way of adding armor and variety without increasing reliance on finding things.

**Comment by farooqkz** [comment]
And then only Warriors and Shooters will get into the board?Because score is given to players whenever they kill.

**Comment by ClobberXD** [comment]
That would have to be massively overhauled too

**Comment by rubenwardy** [comment]
Note that players will be able to switch classes anytime. The icons could be their best class though

**Comment by rubenwardy** [comment]
You can change anytime at your team's base

**Comment by ClobberXD** [comment]
But what if they abuse this, by switching to an advantageous class and back, just to escape certain death? I propose to **allow players to be able to switch classes, at least 30 seconds after the previous switch**.

**Comment by AKryukov92** [comment]
What about:
* Builder - has crafting grid
* Warrior, shooter - can't craft at all
?

**Comment by ClobberXD** [comment]
@AKryukov92 - and what would they do if they need to craft advanced weapons? Completely disabling the craft-grid for non-Builders is out of the question. We can however, enable only select crafting recipes like weapons / tools, etc.

**Comment by AKryukov92** [comment]
They would switch to builder for some time to craft advanced weapons.
Anyway, building capabilities of Builder should be stronger than any other class. Otherwise, players will stick to fighting classes instead.

**Comment by afshaan4** [comment]
>Anyway, building capabilities of Builder should be stronger than any other class. Otherwise, players will stick to fighting classes instead

Agreed

I don't think we should disable crafting for combat personnel though, as crafting things like forges swords and other things is essential most of the time.

**Comment by AKryukov92** [comment]
> crafting things like forges swords and other things is essential most of the time.

Don't forget that both sides will have to switch to builders to craft anything. So this essential thing will be perfetly balanced.
Another way to make builders meaningful:
* Warrior, archer - can't dig minerals
* Builder - can dig minerals

One more option:
* Builder - can craft and dig *some special solid block* (maybe cobble bricks out of 4 regular cobble)
* Warrior, archer - can't craft and can't dig *some special solid block*

This will make builders useful in assaulting enemy bases. Only they will be able to break certain defences.

**Comment by ClobberXD** [comment]
Each player class mush have it's own minor skin variations of the same team color - this way, players from different classes can be visually distinguished; adds variety to the game-play.

@AKryukov92 - Please keep in mind that the objective here must be to **limit** certain capabilities for certain classes (e.g. **limiting** the building, digging or mining capabilities for non-builder classes), and **not to completely disable** them outright.

> Don't forget that both sides will have to switch to builders to craft anything. So this essential thing will be perfetly balanced.

Both the teams have to switch to a different class in order to craft - that's kinda fair, agreed. But it would just make it more boring (IMHO) to switch to another class, just to craft swords. I do however, agree with your proposal that only the builder class would be able to mine / craft _some special solid block_ like mese blocks, bricks (of any kind), etc.

**Comment by ClobberXD** [comment]
Looks like a similar system has been implemented here: https://github.com/MinetestForFun/server-minetestforfun/issues/183 :+1:

**Comment by ClobberXD** [comment]
> Another option: builders can use bucket while others can't.

Buckets are very dangerous IMHO - if enabled, expect ruthless, merciless griefing in *every* part of the map.

**Comment by Gaara95** [comment]
What would you do with a bucket? IMO weapon crafting is essential to the game builder or not you need it. And could you define "special solid blocks"?

**Comment by ClobberXD** [comment]
> What would you do with a bucket?
Griefing, of course! Imagine spilling water everywhere near the base(s), or even worse, lava (Cavern map only)...

> And could you define "special solid blocks"?
Crafted, strong, or rare blocks. e.g. Mese block (rare / strong), and brick (crafted / artificial).

**Comment by AKryukov92** [comment]
> Buckets are very dangerous IMHO - if enabled, expect ruthless, merciless griefing in every part of the map.

This is PvP game with short-lived maps and constructions. What kind of griefing are you afraid of?
I can easily imagine lava everywhere near the bases in Cave map. It is actually very possible to do without bucket. One can use bucket to surround own base with dangerous wall of lava and other team will have to use builder to be able to get to the flag.
Water is only thing which can slow down people now. It will open more defensive engineering options.

> And could you define "special solid blocks"?

For example #101 or cobble slabs. It should be very hard (or impossible) to break by non-builder.

**Comment by Gaara95** [comment]
Yeah, it would be interesting if that happened. We could build better bases that way.

**Comment by ChristianSirolli** [comment]
Any further development of ideas?

**Comment by rubenwardy** [comment]
Done
