### ISSUE TITLE
Stone spears

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#214]
I propose to add stone spear.
They should do same damage as stone swords, but will be able to reach enemies little further than sword.
This will give some advantage for skilled players without steel weapons.

Recipe for stone spear is
```
# 0 0
0 | 0
0 0 |
```
where:
`|` is a stick
`#` is a stone
`0` is empty craft slot

**Comment by afshaan4** [comment]
It should do enough damage than the stone sword though, but not as much as the steel sword

**Comment by AKryukov92** [comment]
> ![image](https://user-images.githubusercontent.com/28972859/50245692-fbb62f80-0387-11e9-92b4-518a29696c98.png)
@MinetestSam why are you posting feedback about feature in development outside of GitHub?
It looks like gossip behind the scenes, where I cant answer.

As I said to ClonnerXD, I intentionally made spears a bit worse than swords in terms of damage. It is very easy to add overpowered weapon. For example if their damage will be equal to swords, then they will replace swords completely. If they will have longer reach, then players will build 1x1 tower and attack from it, instead of attacking from the ground.

We haven't had any weapon with unusual reach, so it is unclear how exactly it will be used.

**Comment by MinetestSam** [comment]
I posted it there to gain the opinion of what other people thought about that. Everyone doesn't have a GitHub account ;).

**Comment by AKryukov92** [comment]
Can you copy in this issue opinions of other people, who answered you in discord?

**Comment by ClobberXD** [comment]
If you do so, paste it in the PR page itself, please.
