### ISSUE TITLE
doors placed by blue team are colorized red

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#230]
`[02:26:17] <CTF_Bot> <Stix>` @rubenwardy bug report: doors placed by blue team are colorized red, this makes things confusing

**Comment by ClobberXD** [comment]
I'm suspect that only one colour door is registered. On testing, I found out that the first door to be placed on server startup is the door registered, and `on_place` is not even invoked for the other door.

**Comment by ClobberXD** [comment]
Correction: Both doors are indeed registered, but for some reason, the code that adds the colour suffix doesn't run more than once. On further testing, This is indeed a strange issue. But I have a hacky solution that fixes this. I'll make a PR once I finish testing.

**Comment by AKryukov92** [comment]
I checked df0adb449558d1daacd56278c5b948bba37de782 and reproduced this bug in "opposite" direction.
All doors are taken by "/giveme doors:door_steel" command.
* place steel door by blue player. Door becomes blue
* place steel door as red player. Door becomes blue
In the same time, after server restart.
* place steel door by red player. Door becomes red
* place steel door by blue player. Door becomes red

**Comment by AKryukov92** [comment]
I have added logging command `minetest.log("Placing " .. name)` and found that when blue places door after red, I have following messages in log:
```
2018-11-11 22:39:14: [Server]: Placing doors:door_steel
2018-11-11 22:39:26: [Server]: Placing doors:door_steel_red
```
Which means that variable name was overriden incorrectly.
