### ISSUE TITLE
Chest points

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#232]
This is revised successor of #205 and #229.
We stay with the idea of "player loses all items on death ".
In addition, we want to encourage players to store items in chest because it makes victory closer.

Currently player needs only to get high kill/death ratio and some amount of score to get access to pro chest.
I propose:
* Allow all players to **sell** items for *chest points* (CP)
* Allow to **buy** items for *chest points*
* Chest points counter reset every round

Because different swords has different damage, they should cost different amount of points.
1 apple or 1 ammo can not be compared to whole sword, so they should cost less.
List of costs:
* Diamond sword - 500 CP
* Diamond pick - 400 CP
* Mese sword - 400 CP
* Mese pick - 300 CP
* Diamond - 250 CP
* Mese - 200 CP
* Bronze sword - 150 CP
* Shotgun - 100 CP
* Rifle - 100 CP
* SMG - 100 CP
* Steel sword - 100 CP
* Bronze ingot - 75 CP
* Pistol - 50 CP
* Steel ingot - 25 CP
* Ammo - 10 CP
* Apple - 5 CP
* Wood planks - 1 CP

**Comment by Thomas--S** [comment]
Honestly, I still prefer the current system, but if this new system will be implemented, I strongly suggest to follow @ClobberXD's idea (not resetting the points every match).

**Comment by AKryukov92** [comment]
I think that players CP should not be persisted through matches in 100% quantity. It may lead to unnecesarry banking. If you think that keeping points is a good idea, then I suggest to limit persisted points to cost of 1 diamond sword. In The Cave it is common scenario when one player is running for diamonds and stores them in chest afterwards. Cost of 1 diamond sword is equal to cost of 2 diamonds.

**Comment by Thomas--S** [comment]
I think the best option is to keep the current system. It usually works quite well and allows for a team play gamestyle whithout being worried about losing or gaining points.

**Comment by ClobberXD** [comment]
I agree with Thomas--S. Unless a very robust system is proposed, I suggest we stick to the current system.

**Comment by AKryukov92** [comment]
I don't agree that current system works good.
Everytime I join, I see same situation over and over. In the weaker team "pro" players just looting items from chest and run to enemy base. They die and lose good weapons. They don't even realize, that they need to return swords to team chest. If they find new swords in chest, they take it again and go to death.
Things are getting changed if you convince them to return good weapons to chest after attack.

Thats why I think it is right thing to encourage people to return items to chest with gameplay features.

**Comment by Thomas--S** [comment]
>  In the weaker team "pro" players just looting items from chest and run to enemy base. They die and lose good weapons. They don't even realize, that they need to return swords to team chest. If they find new swords in chest, they take it again and go to death.

This style of gameplay will lower their K/D rate very quickly, so they will loose access to the pro section.

**Comment by AKryukov92** [comment]
> This style of gameplay will lower their K/D rate very quickly

Right now I have 1356 kills and 631 deaths. This is equal to 2.1 K/D ratio. I need to die 273 times to lose that status. It means I can take everything I see from the team chest and just waste it on the enemy base. 273 times. It doesn't seem very quickly.

I suppose some players can farm high K/D by spawn killing when there are noone to oppose them.
