### ISSUE TITLE
[Recipe] Ladder generator

### ISSUE THREAD

**Issue by Thomas--S** [MT-CTF/capturetheflag#249]
```
   7 Sticks  -> 5 Ladders
   1 Ladder  -> 2 Sticks
=> 5 Ladders -> 10 Sticks = 5 Ladders + 3 Sticks
```

The current recipes can be used to make new Sticks/Ladders out of nowhere.

> `[19:51:08] <CTF_Bot> <king> i know how to make a ladder generater`

**Comment by AKryukov92** [comment]
I suggest to change ladder recipe to use 8 sticks (furnace shape) and produce 4 ladders

**Comment by ClobberXD** [comment]
The `H`-shaped recipe was used because its shape can be associated with the shape of a ladder, but since we've moved on to one-click crafting, I think ladders requiring 8 sticks is a good idea.

**Comment by ClobberXD** [comment]
> The `H`-shaped recipe was used because its shape can be associated with the shape of a ladder, but since we've moved on to one-click crafting, I think `8 sticks --> 4 ladders` is a good idea.
