### ISSUE TITLE
Add a 10 minute temporary ban when a player is vote kicked

### ISSUE THREAD

**Issue by MinetestSam** [MT-CTF/capturetheflag#265]
Vote_kick was added as a feature that would help when no mod is on. Kicking the players is generally not the best idea as most of them might just rejoin.
Let me take an example, suppose player xyz doesn't speak English and doesn't understand it. xyz likes to grief on caverns but doesn't understand what the mods  are saying. (Future scenario) A trusted player uses vote_kick to kick him. xyz doesn't understand why he got kicked, he rejoins and starts griefing again. Now constantly kicking him would surely not resolve anything so temporarily banning him for 10 mins would help and it would at least reduce the amount of griefing done

Now that was just a basic example and it can also be used against hackers (seeing the increase in the number of hackers)

**Comment by AKryukov92** [comment]
Mod could manually ban xyz on second occasion of griefing.
What is the point of automation in this case?

**Comment by MinetestSam** [comment]
Well I didn't write the example properly but I meant to add after 'future scenario' "when a mod is not online"

**Comment by AKryukov92** [comment]
Why don't just give 'ban' privilege to 'trusted player's?

**Comment by MinetestSam** [comment]
That would be basically making them a mod, they are trusted enough to kick griefers,hackers,spammers,etc when no mod is online

**Comment by ClobberXD** [comment]
> Why don't just give 'ban' privilege to 'trusted player's?

So.... what exactly is the difference between a moderator and a player with the `trusted` priv?

**Comment by MinetestSam** [comment]
No, Joe is only allowed to start a vote, its up to the players to decide if they want the player to be kicked and the ban feature is added to add some value to kicking players. Joe isn't banning the guy. Also the time period is fixed so it doesn't really work as the ban privs. Joe can't override the 10 minute ban period and neither can he ban them permanently. He just has permissions to kick the trouble makers when no mod is online

**Comment by AKryukov92** [comment]
Are there exact requirements for mods and kickers?
What is the difference in terms of requirements between mod and kicker?

I think that if player cares about order on the server, then he needs to be a mod with proper instruments.
If he don't care about order, then he is just ordinary player and don't need any way to ban people.

**Comment by MinetestSam** [comment]
A 'trusted' player can be one you can be trusted with kicking the right players and those are guilty whereas a mod is basically a trusted person who is chosen by rubenwardy to basically take care of the server

A mod gets other privs too like a mod can que up a restart, changed teams, canafk,etc
A trusted player only gets the 'vote_kick' privs

**Comment by AKryukov92** [comment]
You didn't add any clarification about requirements.
How to determine, that player is "trusted to kick", but in the same time "not trusted to ban, restart, etc"?

**Comment by MinetestSam** [comment]
Again the trusted player can only start a vote, its up to the other players to decide whether they want to kick him or not

**Comment by AKryukov92** [comment]
You are telling me what they can do. I ask why do you trust him to do this.

**Comment by MinetestSam** [comment]
Because they have been regularly active and mature enough

**Comment by AKryukov92** [comment]
Why "regularly active and mature enough" aren't trusted to be mod?

**Comment by MinetestSam** [comment]
> Why "regularly active and mature enough" aren't trusted to be mod?

Because there maybe a doubt here and there if they are good enough to become a mod or not

**Comment by AKryukov92** [comment]
It sounds like "kicker" is some preliminary and temporary stage before becoming real mod. Right?

**Comment by ClobberXD** [comment]
@AKryukov92 This is a measure to keep troublemakers in check, when there are no moderators around. This has nothing to do with preliminary/temporary stage before becoming a mod. This is about players (potentially a hundred or so) who can start a vote to kick a troublemaker. They are selected on a player-to-player basis by an admin (maybe the moderators too) as they're seen to be mature and trust-worthy, and won't abuse vote_kick to kick everyone they don't like.

> Why "regularly active and mature enough" aren't trusted to be mod?

Again, this has nothing to do with becoming a moderator, and there could potentially be hundreds of players who get the `vote_kick` priv. It's up to the admin of that server to decide who becomes a moderator and who does not.
