### ISSUE TITLE
Removal of /rankings me not obvious, make it work as before instead

### ISSUE THREAD

**Issue by tidle** [MT-CTF/capturetheflag#267]
The rankings window shows me having only one kill, despite having gotten more than one in the round.  It has also reset, but I'm not sure if this is a bug.

**Comment by rubenwardy** [comment]
Use /r instead

**Comment by tidle** [comment]
Thank you

**Comment by ClobberXD** [comment]
@rubenwardy The syntax of `/rankings` is `/rankings <name>`, where `name` is name of the player, whose rankings is to be shown. Adding a special case for the name `me` was understandable, but not the best implementation with respect to consistency. What we need to do is to document `/r` and `/rankings` properly, and probably add `/r` to random_messages.

**Comment by ClobberXD** [comment]
Ideally, `/r` should also support specifying an optional param to display another player's stats, just like how `/rankings` used to work - Players aren't too happy with being shown a formspec every time they check their score, and I can understand why. I'll make a PR for that when I get the time.

**Comment by ClobberXD** [comment]
See #304 and #307
