### ISSUE TITLE
Make bounties more scalable

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#268]
Bounty prizes are calculated using the following algorithm: `(score * KD) / 5000`. To prevent extreme bounty prizes, there's a hard upper and lower limit of 500 and 50 respectively. What happens here is that unless a player's score and KD are within a certain magical range, the bounty on their heads is always 50 or 500, because the algorithm generally returns a number outside the permitted range.

It would be great if the bounty was somehow made to scale within the 50-500 range in the first place. The lower limit should also be reduced to 5 or 10.

**Comment by AKryukov92** [comment]
Is it possible to attach actual player rankings to this issue?
We just need other formula to scale bounties more accurately.
To develop such formula, we need some real data to test  hypotheses.

**Comment by bewlay** [comment]
What about only tying it to K/D? With something like `(kd  - 1) * 100` It would start as 50 at k/d 1.5 and max out as 500 at k/d 6 (maybe higher?). I think most players have a k/d in between that, the linear scaling would probably be fine.

**Comment by JostP** [comment]
What about  `(score/deaths) * 2` (average points per death * 2)? 
You can find score/death ratio here: https://forum.minetest.net/viewtopic.php?f=10&t=13157&p=337571#p337521

**Comment by xenonca** [comment]
Can close I think?
