### ISSUE TITLE
Automatic inventory management on item pickup

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#291]
Today I have played CTF and noticed that it is extremely incomvenient to gather throphies in heat of battle.

Player as usual can manually manage his inventory as he likes.

I propose following changes:
* When player picks up tool of same type, but better quality than anything in his hotbar, then item in hotbar should be replaced by new item.
Example: when you kill enemy with stone sword, pick up his steel sword. then your stone sword will immediately be replaced by steel one in your hands.
* When player picks up tool of same type as anything in his hotbar, then this item goes to second inventory row. Even if first row has empty slots.
If you carry stone sword and pick stone swords from the ground, then they will not appear on hotbar.
* Sticks, ingots and all other non-placeable and non-usable items are always go to second inventory row.

Is it possible to handle pickups in MT?

**Comment by AKryukov92** [comment]
I checked https://github.com/minetest/minetest/blob/master/doc/lua_api.txt
And found several ways to do this:
* minetest.register_on_player_inventory_action
* on_metadata_inventory_take
* Override on_use for tools

I'll try to tinker with those options and see which one suits me more.

**Comment by ClobberXD** [comment]
`minetest.register_on_player_inventory_action` is the best option. `on_metadata_inventory_take` callbacks are executed when taking items from a node inventory (e.g. chest) and is hence irrelevant to your requirement. Overriding `on_use` is the most tedious way to do this, as you'd have to override this callback for every registered node/craftitem/tool.

**Comment by ClobberXD** [comment]
Oh no...

**Comment by AKryukov92** [comment]
I will look on this this week.
I assume, that "backward compatibility" can be handled by disabling this feature if MT version is lower than 5.0
