### ISSUE TITLE
Nametags of new players being shown on join

### ISSUE THREAD

**Issue by MinetestSam** [MT-CTF/capturetheflag#292]
The nametags of a player is shown for a couple of seconds when they join

**Comment by ClobberXD** [comment]
Bug introduced by bugfix commit 7140e84. It fixed the orphaned nametags in the middle of the map, but apparently also introduces this...

I'm sure the fix would be simple. I'll make a bugfix PR today.

**Comment by ClobberXD** [comment]
Bugfix PR: #295
