### ISSUE TITLE
Whip

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#293]
I propose this weapon to use on some specific map as its unique feature.

Whip deals 2 damage and increases speed of damaged player by 20% for 5 seconds (multiplier 1.2 of normal speed).
It can be used on teammates with same effect.
Range is equal to spear (=5).
It can be found often, but only in chests.

I think it will be very unusual option for cooperation.

**Comment by Gael-de-Sailly** [comment]
In my opinion, something that can allow to damage your own teammates has a big potential for sabotage and is best avoided, even if it has also positive effects. I would prefer an item that gives the speed boost to yourself.

**Comment by AKryukov92** [comment]
I don't like the idea of boosting yourself. We need to encourage team play.
That's why I'd like to add more items, which will boost teammates.
What about same item, but without damage?

**Comment by DS-Minetest** [comment]
I don't think, whipping someone makes them faster.
