### ISSUE TITLE
Only show enemy names if close or in line of sight of a team member

### ISSUE THREAD

**Issue by robbiewxyz** [MT-CTF/capturetheflag#3]
What do you think about ditching the always-visible nametags in favor of more sneaking around in the game?  Night would become a crazy scary thing and the infinite chases would be over.  Now that we have the colored skins, they're unnecessary for team identification.

Or I think there's a mod to show them only nearby.

Any thoughts?

**Comment by rubenwardy** [comment]
This would be good. I'd like to be able to only show nametags if:

* Enemies only visible if they can be seen (in the line of sight, and is big enough to be seen)
* or an ally can see the enemy

And it should be on the minimap as well. The size of player on screen that qualifies "big enough to be seen" should be sufficient enough to make play difficult.

This would allow tunneling etc.

**Comment by rubenwardy** [comment]
However, to achieve my vision you'd need a/multiple Minetest engine change(s).

**Comment by Ombridride** [comment]
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L815

```
#    Whether players are shown to clients without any range limit.
#    Deprecated, use the setting player_transfer_distance instead.
#    type: bool
# unlimited_player_transfer_distance = true

#    Defines the maximal player transfer distance in blocks (0 = unlimited).
#    type: int
# player_transfer_distance = 0
```

This isn't good enough  ?

**Comment by ClobberXD** [comment]
Partially fixed. The line-of-sight part adds unnecessary complexity, IMO...

Close?

**Comment by rubenwardy** [comment]
No, this includes being about to see team members at any distance

**Comment by rubenwardy** [comment]
This is possible using the HUD API, but you will need to do potentially expensive line of sites
