### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#309]
I think it is time to clarify contribution guidelines.
It is usually written in special "CONTRIBUTING" file which is stored in root of repository.

Proposed contribution workflow is supposed to solve following problems:
* Clarify potential contributors that some feature worth spending time by gathering public opinions
* Prevent endless work in PR by freezing requirements for each one individually
* Provide repository admin with ready-to-merge options of implementation of debatable feature.
* 

My proposal of feature workflow:
1. Idea is being discussed in Issues. It includes block and tool properties, game rules, gameplay mechanics and so on.
2. When comment with description gets 5 likes, then development starts. Amount of likes might be increased later. Approvals are required to show potential contributors that this feature is ready to be implemented.
3. Development starts along with PR, where we discuss implementation details: architecture, codestyle, optimisation, correct usage of API. First message of PR should contain full description of implemented feature.
4. Someone do thorough testing and add comment with results of the test.
5. Development finishes when result of the testing proves, that feature has been made as described.
6. PR gets merged

Alternative paths:
2. If description of feature in first message of issue changes during discussion, then it should be posted again as new comment in same issue.

3. If someone thinks that feature should be different, then discussion should take place in associated issue. Another PR should be made to implement feature with new description.
This way we will give repository admin possibility to choose between different implementation. Each one is ready to be merged at any time.

6. If repository admin have several different PRs with implementation of same feature, then he can arbitrary merge any one and close all others.

**Comment by AKryukov92** [comment]
Will you provide any reason for your dislikes?

**Comment by ClobberXD** [comment]
Sorry, I did not have time to comment back then.

> When comment with description gets 5 likes,

Depending on the number of thumbs-up emojis isn't the best way to gauge support. Explicit approval alone is more than sufficient, IMO.

> If someone thinks that feature should be different, then discussion should take place in associated issue.

A feature request is used to express the need for a certain feature, and gauge support from the rest of the community (including the core devs). Once a PR is made, it'll be reviewed, tested, and feedback about the PR will be provided in the PR page itself. Why would you want someone to discuss implementation details in the feature request page?

> Another PR should be made to implement feature with new description.

It's too much work to make another PR for the same feature. Let's take #258 for example. It was suggested that the spears' damage numbers be tweaked. How is it sensible to make a separate PR for this?

**Comment by Thomas--S** [comment]
The reasons for my dislike are the same as @ClobberXD stated.

Additionally, it is sometimes better to discuss the features in the PR itself because of the following reasons:

1) Some silly feature requests are never made into a PR, and I don't see why time should be wasted by discussing this in issues when it is very unlikely that it will be ever turn into written code.

2) I usually prefer to comment on features when I see the exact implementation, i.e. when there is code (PR).

**Comment by AKryukov92** [comment]
> > When comment with description gets 5 likes,
> 
> Depending on the number of thumbs-up emojis isn't the best way to gauge support. Explicit approval alone is more than sufficient, IMO.

Likes on the feature is the sign that community likes the idea of the feature.
If it is, then it worth implementing. Otherwise, it is probably a waste of time.

You are confusing with the terms in your reply.

> A feature request is used to express the need for a certain feature, and gauge support from the rest of the community (including the core devs).

I agree with it.

> Once a PR is made, it'll be reviewed, tested, and feedback about the PR will be provided in the PR page itself. Why would you want someone to discuss implementation details in the feature request page?

I don't want to discuss implementation details in feature request page.
Implementation details like whether you should use node timers or globalstep should be discussed in PR.
Things like properties of the weapons is the opposite. They should be discussed in feature request (which is in issues).

> It's too much work to make another PR for the same feature. Let's take #258 for example. It was suggested that the spears' damage numbers be tweaked. How is it sensible to make a separate PR for this?
```
git pull AKryukov92:#214
git checkout -b #214_slow_spears
--change properties of the spears as you like--
git commit -m "Changed properties of the spears to reflect my point of view"
git push origin #214_slow_spears
```
Then make PR with github web interface.

> Some silly feature requests are never made into a PR, and I don't see why time should be wasted by discussing this in issues when it is very unlikely that it will be ever turn into written code.

You just press "dislike" like you did in #229 You don't have to discuss everything.

> I usually prefer to comment on features when I see the exact implementation

Why someone should implement anything just to attract you to comment? What if you just dislike work that have been done in this PR. It is much better to save contributors time and discuss things first.

How do you like the situation when you make PR and someone tells that your work should be discarded?

**Comment by Thomas--S** [comment]
> You just press "dislike" like you did in #229 You don't have to discuss everything.

But for this, I have to read through all issues and also the respective comments. It is usually better to focus the time on discussing the features in the actual implementation proposal, i.e. PR.

> How do you like the situation when you make PR and someone tells that your work should be discarded?

This is a normal process and I don't have any problems with this.

**Comment by AKryukov92** [comment]
> But for this, I have to read through all issues and also the respective comments. 

You don't have to respond to every feature in issues. You can browse feature request as you usually do and respond to ones that attracts your attention. You have options: do nothing, press like, press dislike, comment.

> This is a normal process and I don't have any problems with this.

This is not normal.
To comment anything you just need to open your browser and write some text. You don't need special software nor skills nor knowledge to do it.
To make PR you need to know lua, MT API, git and your actions will be:
1. Fork repository
2. Clone it
3. Make branch
4. Code feature
5. Debug feature
6. Commit changes
7. Make PR

As you can see, effort, required to comment anything is significally less than effort required to code any feature.
Why someone should do so much effort just to allow you to comment feature?
More than that, your comment is very likely be "you did feature wrong and should do it other way".
Are you sure that your comments are so valuable to spend time to code features?
