### ISSUE TITLE
ctf_stats requires a major refactor/cleanup and a proper API

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#313]
There are at least 4 PRs that modify various parts of `ctf_stats`, and even if we don't take them into consideration, both `gui.lua` and `init.lua` are getting very cluttered. `ctf_stats` needs some substantial amount of refactoring and cleanup.

The mod should also provide a proper API, which can be used by mods that adds new stats like bounty kills and kill assists. e.g. to add a new stat `"kill_assists"`, the new code should just have to

- Register the new stat. e.g. `ctf_stats.register_stat("kill_assists", "Kill assists")`
- Modify the new stat whenever required like the following example:
```lua
    local assists = ctf_stats.get_stat(name, "kill_assists")
    ctf_stats.set_stat(name, "kill_assists", assists + 1)
```

Please share your thoughts on this. I'll start working on this once those 4 PRs are merged.

**Comment by ClobberXD** [comment]
I'd say the very first step is to split the two existing files into 4 files as given below:

- chatcommands.lua: Exclusively for chat-commands.
- init.lua: All the callbacks (`on_dieplayer`, `on_killedplayer`, `on_capture`, `on_winner`, etc.)
- api.lua: Existing API, `ctf_stats.players`, etc.
- gui.lua: End-of-match, league tables formspecs

**Comment by AKryukov92** [comment]
I think that new API worth implementation for things that are supposed to be added in dozens with some common logic. Something like blocks, tools and entites.
How many similar stat of player can you imagine? I don't think that their quantity will be high.
Thats why I'm not sure that API for action "add new stat" is something that worth doing.
You will get additional abstraction layer and increase complexity of code.

You showed code to add new stat in case of making API.
Can you write similar snippet to illustrate amount of code, required to do it now?
Maybe it is trivial enough to keep things as they are.

I think that any refactoring should be done with [Clean Architecture](https://rubenwardy.com/minetest_modding_book/en/quality/clean_arch.html) in mind.
In addition, I think that code should be covered with [unit-test](https://rubenwardy.com/minetest_modding_book/en/quality/unit_testing.html)s before you do any major transformations.
It will help you to find bugs on development stage. Which will be much faster than usual.

**Comment by AKryukov92** [comment]
>  I'll start working on this once those 4 PRs are merged.

Have you considered option to make 1 PR instead of 4 and do refactoring there?

**Comment by ClobberXD** [comment]
Here are the 4 PR's I'm talking about: #314, #307, #301, and #185

**Comment by AKryukov92** [comment]
> It's impractical to combine these into one PR

True. I thought they were very similar.

**Comment by ClobberXD** [comment]
Refactoring requires the `prev_match_summary` to be accessible from another file. One way to do this is to add a getter method. I think I'll finish #310 first, as I'm planning to expand the existing match summary feature, make it more generic, and add setter/getter methods for that feature request.

**Comment by ClobberXD** [comment]
2 more PRs remaining...

**Comment by ClobberXD** [comment]
rubenwardy is working on it. :tada:

**Comment by ClobberXD** [comment]
@rubenwardy Are you still interested in working on this?

**Comment by ClobberXD** [comment]
Part 1 (refactoring): #491

**Comment by ClobberXD** [comment]
I'm folding the `ctf_stats`' the problem of inefficient stats read and write into this issue.

****

[Part 1] (#491) has been merged. [Part 2] would be performance optimisations, and [Part 3] would be API improvements.

**Comment by ClobberXD** [comment]
[Part 2] would benefit a great deal from the helper functions introduced in #454 to help streamline stuff a bit. Naturally, #454 is high priority. :)

**Comment by ClobberXD** [comment]
`ctf_stats` [Part 2]: #518
