### ISSUE TITLE
Allow players to actually crouch instead of just slow down, while sneaking

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#318]
Currently, there's no value to sneak apart from being able to protrude beyond the edge of the ground without falling. As a player, I'd like to be able to move undetected while sneaking, and actually crouch. This could really add a boost to tactics and strategy. This involves:

- Some tweaking to the model (or just the animation?)
- Disabling `sneak` in player physics overrides
- Disabling footstep sounds in obj. properties
- Detecting player's sneak key-press, and modifying player model (or anim?), adjusting selection/collision boxes.

**Comment by rubenwardy** [comment]
I'd like to see this

**Comment by MinetestSam** [comment]
Is it possible to bind a key for crouching seperately?

**Comment by ClobberXD** [comment]
Unfortunately, no. Only certain hardcoded keys can pass keypress events to the server. See https://github.com/minetest/minetest/blob/c26eab6319b64089a32e43cf1626f9583947572a/doc/lua_api.txt#L5140-L5144

**Comment by MinetestSam** [comment]
I found this https://gist.github.com/Bremaweb/cd6b803dd4ef918acb67
Maybe it can help regarding the code
