### ISSUE TITLE
Player appears to stand one block below the surface

### ISSUE THREAD

**Issue by mixrat** [MT-CTF/capturetheflag#324]
Minetest version 5.0.0-dev
This only happens with CTF...
![selection_077](https://user-images.githubusercontent.com/20234985/50915477-c63fc600-149d-11e9-9415-1b7aacba2307.jpg)
The players hitbox and name are in the correct position, but the player appears to stand one block below the surface.

**Comment by rubenwardy** [comment]
Please use the https://github.com/MT-CTF/capturetheflag/tree/dev5.0 branch of CTF when hosting with Minetest 5.0
