### ISSUE TITLE
Player appears to stand one block below the surface

### ISSUE THREAD

**Issue by mixrat** [MT-CTF/capturetheflag#326]
Original issue using the master branch: https://github.com/MT-CTF/capturetheflag/issues/324
I am now using the dev5.0 branch with a fresh build of minetest 5.0.0-dev and have the same problem.
The players hitbox and name are in the correct position, but the player appears to stand one block below the surface...
![selection_078](https://user-images.githubusercontent.com/20234985/50924524-a49e0900-14b4-11e9-9951-0be4f2787927.jpg)

**Comment by rubenwardy** [comment]
This is weird as it works on the CTF5 server at ctf.rubenwardy.com:30001

**Comment by mixrat** [comment]
Yeah, I know. I tried your server yesterday. It is worth noting that I used the same compiled client on your server and mine - with different results.

Can anyone else reproduce this? I have compiled twice from scratch with the same outcome.

**Comment by rubenwardy** [comment]
Are you absolutely sure you have the dev5.0 branch of capturetheflag, with its copy of default?

**Comment by mixrat** [comment]
Quite sure but no absolutely. So I built again with this result...
![selection_085](https://user-images.githubusercontent.com/20234985/51047073-865b1900-162c-11e9-9085-39451dfd67bc.jpg)

Changing guages/init.lua Line 53 
from this: `ent:set_attach(player, "", {x = 0, y = 9, z = 0}, {x = 0, y = 0, z = 0})`
to this: `ent:set_attach(player, "", {x = 0, y = 18, z = 0}, {x = 0, y = 0, z = 0})`
fixed the HP Guage...
![selection_086](https://user-images.githubusercontent.com/20234985/51047258-ec47a080-162c-11e9-92d1-059aee10d948.jpg)

**Comment by ClobberXD** [comment]
Gauges have been fixed too (https://github.com/MT-CTF/capturetheflag/commit/97d3e6ba78399fd99e71e4bc9014ea7c6e6fbdc7). Tested on both a local game and the public test server, and this issue seems to be fixed. Closing...
