### ISSUE TITLE
Add bedrock and/or ceiling

### ISSUE THREAD

**Issue by ObaniGemini** [MT-CTF/capturetheflag#33]
For what I know, map only has limits on borders.
We have to decide here if there should be a height limit (e.g : glass roof) and a depht limit (e.g : limit)
##### Additionnal notes :

Adding a depht limit would forbid mining under some depht.

**Comment by rubenwardy** [comment]
I don't think that mining should be an important part of gameplay, except for tunnelling.

**Comment by ObaniGemini** [comment]
It is. When someone begins to mine, a team can have infinite bronze tools/weapons and mese tools weapons.

**Comment by rubenwardy** [comment]
I mean that is shouldn't be, even though it currently is.

**Comment by ObaniGemini** [comment]
So we should think about adding some bedrock at some depth.

**Comment by asl97** [comment]
a game would finish before someone get those stuff,
even if it isn't finish by then, it is a good additional depth to have in the game since the team which invested into mining to get better tools and thus get better chance of winning..

**Comment by ClobberXD** [comment]
Don't we already have `ind_stone` and `ind_glass`? Is this a feature request for adding a ceiling/bedrock parameter to `<map_name>.conf` that auto-generates the aforementioned nodes at the specified y-heights?

**Comment by afshaan4** [comment]
>Adding a depht limit would forbid mining under some depht.

The map is a singlenode map, so it only goes a certain amount of blocks deep, you cant just keeeeep on mining forever

limited depth of map = limited resources to mine

>We have to decide here if there should be a height limit (e.g : glass roof)

IMO that would be pointless, like what would you do being above the glass wall? since if you go outside the map walls you just get teleported back, **and** there is nothing beyond the walls anyway

**Comment by ClobberXD** [comment]
One does _not_ get teleported back if they "accidentally" stray outside the glass barriers, but that is a good idea... It'd work just like the teleporting of players who cross the middle barrier during build-time.

**Comment by rubenwardy** [comment]
I believe the bedrock part of this is done now?

**Comment by ClobberXD** [comment]
The ceiling's done, as well. 6562959e63206e1d047fb6b50166bce935690bd9
