### ISSUE TITLE
Healing others

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#333]
Currently, there are no ways for healing others (other than drop-pickup-use).

There was some talk about healing others in #203 PR. @MinetestSam said that @rubenwardy wants to promote teamwork.
I started reply there, but it gets too long, so I decided that original PR have nothing common with it.

First of all, I want to challenge the thesis of @ClobberXD 
> multiple items that do the exact same thing is a little overkill for CTF

Having word "healing" in description does not make features the same.
If you are healing yourself, you have almost none interaction issues. You know when healing starts and when it ends. You don't need to chanse and target anyone.

I thought a bit and come up with a number of different ways of healing others:
* Interruptable healing over time in close contact (bandages)
Player should get close to other player, target him, start healing and then both should wait for some time. This is new type of action in CTF.
You need to check: are you in the same team, are you on correct distance, do you have line of sight.
You should somehow tell subject of healing that he should stop for some time and wait for healing to be completed. You should probably interrupt healing if subject of healing run away. That's why I don't like idea of bandages for fast-paced game. You will probably waste most of your bandages.
If players will be slowed down by bandages, then it is possible to abuse them to interfere flag carrying.
* Instant healing in close contact (healing sword)
Player should get close to other player, target him, use healing item. Sword fighting is very common in CTF too.
You need to check distance, teams and line of sight.
It should be possible to use this item a lot to make it useful.
* Healing with projectiles (healing gun)
Player should get *close enough* to other player, target him, predict his movement and fire bullet. This action is very typical for CTF, so there is nothing too complex.
In this case you need to create projectiles and check if they hit player on your team.
If projectiles will be affected by gravity, then this way will be very laggy. Like crossbow.
That's why bullets should fly a simple trajectory and not far.
* Instant healing all in some area (healing grenade)
You can even use grenade API introduced in #279 
You need to check distance, team and apply healing. You don't need to target anyone. You probably don't need to check line of sight.
This item should be consumed on use. Otherwise, it is overpowered.
* Drop "hearts" to allow teammates to interact with them.
Healer clicks the ground. There appears "heart". Other players clicks "heart" or steps onto it and recieves hitpoint change.

**Comment by ClobberXD** [comment]
I prefer the first solution. #203 can be modified to interrupt healing if player moves. So if a player wants to be healed by another player, they'll have to stay still. They can manually interrupt healing if they want, by moving, which is useful for situations where the player has to get out of harm's way safely before starting to heal.

**Comment by AKryukov92** [comment]
Why do you prefer first solution?

**Comment by ClobberXD** [comment]
It's simpler. The others are conceptually interesting but will succumb to other problems like lag, and require unnecessary calculations.

**Comment by AKryukov92** [comment]
Why do you think that (chasing other players and guessing whether they have bandages or not) is simpler than other solutions?
There are much more conditions to correctly perform healing by bandages, compared with other means of healing. More conditions = more means to screw it.

**Comment by ClobberXD** [comment]
> There are much more conditions to correctly perform healing by bandages, compared with other means of healing.

Here's the algo for healing another player:
- Check if `pointed_thing` is a player, in the `on_use` callback.
- Check if player is on the same team as user (player who uses the bandage/medkit)
- Invoke `start_healing`
- Profit

That's it. I don't see how this is complicated. On the other hand, ideas 3-5 require entities, and other auxiliary checks as well. Idea 2 (healing sword) is very similar to the bandages idea, except for the instant-healing part, which is too OP.

**Comment by AKryukov92** [comment]
You forgot about:
* On globalstep check if healer and patient stay on their initial positions and interrupt healing
* On take damage of player check if victim is healer or patient and interrupt healing
* Check whether patient is healed by other healer and prevent double healing

Imagine this from players point of view. How do you know where you should run to get healing from other player?
As healer, how do you tell, that other players can get help from you?

**Comment by ClobberXD** [comment]
> How do you know where you should run to get healing from other player?

Players are supposed to communicate... They'll ask someone to heal them using team-chat.

> As healer, how do you tell, that other players can get help from you?

Again, communication. If a player finds many medkits, they could (should) inform their team, and actively go around healing players. If you're talking about player classes, then custom skins ought to fix it. Having a huge `+` on one's shirt will indicate that they're a medic/healer.

**Comment by MinetestSam** [comment]
Hm having thought about this I think the bandages mod doesn't even require any changes. (Bandages mod on Persistent Kingdoms)

**Comment by AKryukov92** [comment]
Regarding
> As healer, how do you tell, that other players can get help from you?

It can be implemented as message to potential patient if healer is too far away, targets patient and uses bandages. Something like "$healername wants to heal you. Wait him".

**Comment by ClobberXD** [comment]
We now have `ctf_bandages` (see 3e57880). Closing...
