### ISSUE TITLE
MapEditor: Provide visual cues for map editor elements

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#354]
Idea inspired by WE. I feel this would be very useful for map-makers.

Currently, visual cues for the following will be the most useful:

- Outer barriers
- Middle barriers
- Centre of schem

**Comment by archfan7411** [comment]
IMO it would also be invaluable to have a visual indicator of the axis the barrier will be generated on, since if the map author generates the barrier along the incorrect axis they often have to resort to a backup or start over.

**Comment by ClobberXD** [comment]
Tried using entities, but I wasn't happy with the results. But it just occurred to me that particles can be used to visualise map bounds. Particles are also less of a performance issue compared to entities. I'll play around with this idea a little.
