### ISSUE TITLE
Make use of separate inventories for tools, guns, grenades, and medkits each.

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#355]
This allows for limiting player inventory space, and also not take their wielded item into consideration, as it's technically not taking up inventory space. The main inv. will be used for blocks, ammo, and other non-weapons.

It's possible to handle moving stuff into their respective inventories when they're picked up. But this is only for 5.0.0+, I'm afraid. I'll just wait until it's released, and see the various implementation possibilities.

**Comment by afshaan4** [comment]
could you elaborate on how that'd work?
and how do we switch between them, or do they each get their own hotkey?

**Comment by ClobberXD** [comment]
> how do we switch between them, or do they each get their own hotkey?

That's the hard part. I don't think it's possible to combine multiple inventory lists into the hotbar. So we require some behind-the-scenes action to copy the items from the individual inventory lists to a separate hotbar inventory list, which the hotbar will connect with.

**Comment by rubenwardy** [comment]
I don't think it's possible to have a hotbar not based on main

**Comment by ClobberXD** [comment]
Meh... Well, time to make a feature request :D

**Comment by rubenwardy** [comment]
You can, however, render things specially in the inventory formspec to make it look like the same list is multiple list

This is done already to render the hotbar slightly above the other slots

**Comment by ClobberXD** [comment]
Yes, but being able to actually select them is important, I think. ;)

The inventory formspec should have the lists separated and labeled, on the contrary.

**Comment by ClobberXD** [comment]
> I don't think it's possible to have a hotbar not based on main

Then we can have `main` as the behind-the-scenes-hotbar-connected inv. list, and have another list for the actual inventory (`backpack` maybe?)

**Comment by ClobberXD** [comment]
Just throwing this here - this feature greatly reduces the amount of work required for implementing #291.
