### ISSUE TITLE
Medkit bugs

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#361]
\<butbitbug> endless healing when healing is interupted
\<butbitbug> you gain 2 hp everytime you try to heal

**Comment by ClobberXD** [comment]
I noticed the inconsistency too. On it.

**Comment by ClobberXD** [comment]
Disabled hpregen; added some debug messages to output HP value when healing starts, and the value passed to `set_hp` when healing is interrupted - both these values are the same, but somehow, the final HP exceeds this by 1 HP...

**Comment by ClobberXD** [comment]
Tweaked `regen_step` to find out more. Here's the problematic code:
https://github.com/MT-CTF/capturetheflag/blob/a5eb95b9ecd395752263f252c51361ad015c211a/mods/pvp/medkits/init.lua#L72-L92

`stop_healing` sets `players[name]` to `nil`, but the part of the code that handles regen doesn't check whether `players[name]` exists.

**Comment by ClobberXD** [comment]
#363
