### ISSUE TITLE
Add sound devices (war horns, gongs, etc.)

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#368]
Audio devices like war horns are very effective in improving team spirit and making the enemy go berserk. What better way to approach the enemy flag than to go in as a pack, blowing war-horns?

Devices like gongs would also be very useful to signal to team-mates of incoming danger, or to just make them come back to base...

**Comment by MinetestSam** [comment]
But can't it be overused by griefers to an extent that the sounds become a pain to the ears and annoying?

**Comment by ClobberXD** [comment]
Then the griefers can be kicked. Anything and everything can be misused or overused by malicious players, but hindering new features with that reason is overkill. :)

**Comment by An0n3m0us** [comment]
I've created a base mod for these types of items:

`https://github.com/An0n3m0us/sounditems`

The mod stores a value for when the sounds are played for each player so that each player cannot play another sound until their first sound is finished.
