### ISSUE TITLE
A way to allow maps to use any node from any mod without the issue of unknown nodes

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#395]
At present, maps can only use nodes that the game knows (i.e. those from `default`, `stairs`, `wool`, `doors`, and a few custom, game-defined ones). Just thought of a very random but interesting idea to remove this restriction.

#### The idea

- During export, `ctf_map` would iterate through all the nodes in the schem.
- For each new node encountered, the node def would be requested.
- The nodedef would then be written to a file in serialized form.
- At runtime, the map would cycle through all the serialized nodedefs and registers them (after `nil`-ifying the fields of type `function`).
- Profit!

#### Obvious flaw(s)

- Nodes can't be registered at runtime, duh. Even if they can, there's no straightforward way to send all the extra media (textures, sounds, meshes) to the client.

#### Caveats

All the nodes registered at runtime would be static - even if a map contains nodes from mesecons or technic, for example, they would just be static, and won't do anything special.

**Comment by rubenwardy** [comment]
This could be done by making the maps repo a mod pack instead

**Comment by ClobberXD** [comment]
Interesting... but how would maps repo being a modpack help in this matter?

**Comment by rubenwardy** [comment]
Actually, it may just be easier to adds mods and content to a modpack in this repo. Maps need to be able to be reloaded as adding maps without a restart is such a nice feature

**Comment by ClobberXD** [comment]
> it may just be easier to adds mods and content to a modpack in this repo

Avoiding that was the whole purpose of this issue, lol. This would allow for nodes from any mod, be it known or unknown, without having to add that mod into this repo. :)

This is actually possible to implement right away, by parsing all the serialised nodedefs at loadtime (maps are already parsed at loadtime). But the big gotcha is that we'd not be able to add maps without a restart. :(
