### ISSUE TITLE
Medkits bugging

### ISSUE THREAD

**Issue by appgurueu** [MT-CTF/capturetheflag#399]
Use medkit before round ends. End the round before you finished healing. Healing is interrupted when you spawn in new map and you get a medikit. Yay.

**Comment by ClobberXD** [comment]
Haha, cool bug :)

**Comment by Thomas-AC-Dev** [comment]
Darn it, I thought only me and Stix knew about that
We should just leave it as an easter egg or just a cool thing you can do
