### ISSUE TITLE
Use mod.conf, modpack.conf; remove deprecated counterparts

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#425]
I actually did finish doing this, but I had targeted the wrong branch. Switching to the correct target branch resulted in conflicts throughout. And I did not have the patience to redo this whole thing again

P.S. @rubenwardy advised on using a bash script to do this.

EDIT: Clarified issue desc.

**Comment by Panquesito7** [comment]
Shouldn't this be closed? 
The pull #443 and #441 fixes this.

**Comment by ClobberXD** [comment]
The `crafting` sub-module still has `depends.txt` and no `mod.conf`, although that's to be fixed upstream.

**Comment by Panquesito7** [comment]
> The `crafting` sub-module still has `depends.txt` and no `mod.conf`, although that needs to be fixed upstream.

@ClobberXD, it already has a `mod.conf`, but it is in a newer commit.
Plus, I've created a PR to delete deprecated `depends.txt` (and improve a bit `README.md`).

**Comment by ClobberXD** [comment]
Ah ok, thanks.

**Comment by ClobberXD** [comment]
https://github.com/MT-CTF/capturetheflag/commit/22e2e03798508444c16e0d3d5a61fbda21580fbf

Updated to include the latest commits in `crafting` including `mod.conf`. `depends.txt` deletion PR hasn't been merged yet, and probably won't for quite some time.
