### ISSUE TITLE
Can take from chests across border.

### ISSUE THREAD

**Issue by CoderBlaze** [MT-CTF/capturetheflag#431]
I played a game yesterday where I was able to take items out of a chest on the other side of the red barrier.

**Comment by LoneWolfHT** [comment]
I kind of like this feature, because you have to rush to the middle to get your chests before the other team does, and maybe steal some of their loot too

**Comment by ClobberXD** [comment]
This is a feature disguised as a bug. ;)

I don't think there's any harm in letting it be.
