### ISSUE TITLE
Vertical headings in menus sometimes display incorrectly when using a large font

### ISSUE THREAD

**Issue by Calinou** [MT-CTF/capturetheflag#442]
**Client version:** Minetest 5.0.1

In the `/summary` menu, the vertical heading is partially cut when using a large font:

![image](https://user-images.githubusercontent.com/180032/63215442-af91d980-c126-11e9-8e13-d4b857d94a83.png)

However, it displays correctly in the `/rankings` menu:

![image](https://user-images.githubusercontent.com/180032/63215445-bcaec880-c126-11e9-9274-f0f0c554dda5.png)

The font used is [Inter SemiBold](https://rsms.me/inter/) at size 29. `hud_scaling` is set to 2 in `minetest.conf`.

**Comment by ClobberXD** [comment]
It seems to me like this can be fixed by simply increasing `size.x` and `size.y` of the HUD element def(?).

**Comment by ClobberXD** [comment]
Both of these formspecs use the same formspec code behind the scenes, btw - only the titles are different. I don't know of any way to modify the width and height of labels. Maybe this is an engine bug?
