### ISSUE TITLE
Delete MTG tnt sounds if a mod uses them

### ISSUE THREAD

**Issue by Panquesito7** [MT-CTF/capturetheflag#447]
If a mod is using sounds from the `tnt` mod (included in minetest_game), delete them immediately.
See [the Forums](https://forum.minetest.net/viewtopic.php?f=18&t=23154) for more information.

**Comment by ClobberXD** [comment]
The shooter mod uses the `tnt_explode` sound for the grenade explosion. I'll replace it with the new `tnt_explode.ogg` from the updated `tnt` mod in MTG.

**Comment by ClobberXD** [comment]
https://github.com/MT-CTF/capturetheflag/commit/67c1dfa4ee685a529286827a1d549f4cfeffa2e1

**Comment by Panquesito7** [comment]
Nice! 👍
