### ISSUE TITLE
Recipe for bandages from papyrus

### ISSUE THREAD

**Issue by farooqkz** [MT-CTF/capturetheflag#459]
How about adding a recipe to craft bandages from papyrus?

**Comment by ClobberXD** [comment]
Players won't be able to obtain bandages in maps without papyrus. Bandages and medkits weren't meant to be craft-able anyway.

**Comment by farooqkz** [comment]
> Players won't be able to obtain bandages in maps without papyrus.

No problem. Just like when players are not able to craft diamond swords in maps without diamond.

**Comment by ClobberXD** [comment]
However, unlike diamond swords, bandages would already be available in chests, and in those maps with papyrus (only two, IIRC) bandages would be too abundant.

**Comment by LoneWolfHT** [comment]
It doesn't take long to run out of bandages after a while. So a complex craft would still be nice

**Comment by ClobberXD** [comment]
Still not very convinced on the need to be able to craft this, but if we do need one, I suggest using leaves as the ingredient - leaves are everywhere, and maps without leaves are very rare. That way, bandages would be craftable on most maps, but the recipe would still be realistic.

**Comment by MinetestSam** [comment]
I still don't think there is a need for crafting recipe (also quite a low chance that the recipe would even be used seeing that traps are rarely made or reinforced cobble). And yeah although leaves would be a good option and the closest one but still I don't think that would be the only item in the crafting recipe.

**Comment by Cahrs** [comment]
I think it would be much better to have a shop connected to team chest where players can use per-match points to purchase certain gear, such as meds, bandages, and ammo

**Comment by LoneWolfHT** [comment]
A shop would be neat. Finding a good price for the items will be fun

**Comment by MinetestSam** [comment]
I do like the idea of shops, that would make the points system a bit more useful and the rankings won't be useless. Players could purchase items for whatever points they earn in a match and the points they gained from the match after deducting everything they bought for points during the match will be added to their score. 

Although this would make Pro Vs. Pro matches a tad bit too long.

**Comment by LoneWolfHT** [comment]
> Although this would make Pro Vs. Pro matches a tad bit too long.

How so?

**Comment by MinetestSam** [comment]
Well lets assume the match going on is even and the teams are balanced, now there is a high probability the both the teams would have killed each other a lot especially the pros. The pros would have stacked up points and they would also have a chest with some iron swords. But lets say they run out of iron swords, they could then go and mine iron. Now assuming they even lost that, now they could buy swords with the accumulated points.
Due to plenty of resources no team would be able to gain advantage over the other

**Comment by LoneWolfHT** [comment]
Yeah, the shop would only be for 'consumables' like bandages, medkits, ect

**Comment by ClobberXD** [comment]
Please don't hijack the original issue. :P

**Comment by LoneWolfHT** [comment]
I no longer support this now that we have a medic class.
