### ISSUE TITLE
Break away from MTG completely

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#472]
This idea was inspired by ITB. MTG's `default` is just too much bloat, and updating our nodes after a new MTG release is ever so painful. We've also got a ton of indestructible nodes, created thanks to shameless copy-pasta, resulting in enormous "code" duplication.

If we develop our own nodes instead, we could manage all these issues in a much more elegant manner. Map makers might still be able to make maps from MTG nodes if they want to - we could have some sort of a conversion system available, that'd convert MTG nodes to their CTF counterparts.

Like, share, and subscribe. And feel free to share your thoughts about this proposal in the comments section down below.

**Comment by Thomas--S** [comment]
To be honest, I'm not sure if this is really worth the efforts. Eventually, it will most likely be a duplication of large parts of MTG's `default` anyways.

**Comment by ClobberXD** [comment]
> it will most likely be a duplication of large parts of MTG's default anyways

To a basic extent, yes. But the resulting code would have a *much* better structure, as all nodedefs are in the mod, and the ind node code duplication can be done with for good. That's the main takeaway of this proposal.

**Comment by Cahrs** [comment]
the indestructible nodes are made via copy-pasta? why not just loop through minetest.registered_nodes and register the equivalant with no changed values but groups?

**Comment by Cahrs** [comment]
Id like to say im in favor of this proposal though, this would also maybe open the door for custom deco nodes per map?

**Comment by ClobberXD** [comment]
> the indestructible nodes are made via copy-pasta? why not just loop through minetest.registered_nodes and register the equivalant with no changed values but groups?

There's no guarantee of the map maker having the exact same arsenal of nodes as CTF (the game) does. If they're using a newer version of MTG, for example, they could potentially add nodes in their map that CTF doesn't recognise. While we have to way to check for that, I thought we'd at least avoid creating the same situation for indestructible nodes, as the latter is completely under our control. However, looping through `minetest.registered_nodes` is exactly what we're doing to register indestructible stairs and wool, at the moment.

**Comment by ClobberXD** [comment]
Some more perspective into why breaking away from MTG is a good idea. A non-exhaustive list reasons to break away from MTG:

- More consolidated API:

  - A single mod for nodes instead of fragmentation like wool, xpanes, stairs, etc.
  - A more unified approach to player death and respawning - e.g. initial item handling is in one place, most of the CTF-related respawning code is in another place, etc. Ideally, one mod should handle all player-related stuff like HP, initial items, respawning, etc.
  - Custom player model with support for stuff like crouching. I *think* this isn't possible to implement using `player_api`.
  - A lot of code is tied to the concept of teams in CTF. It'd be nice if we could directly handle more of the base game within CTF rather than outsource that to `default`.

- Bloat-reduction: The only stuff we use from MTG are

  - A rather trimmed-down version of `default`.
  - Non-trivially modified version of `doors`.
  - `wool`.
  - Bloat-free versions of `flowers`, `fire`, `vessels`, `walls`, `xpanes`.

  The stuff we don't use from MTG:

  - beds
  - binoculars
  - boats
  - bones
  - bucket
  - butterflies
  - carts
  - creative
  - dungeon_loot
  - dye
  - env_sounds (might be interesting to use this until we break free of MTG, provided this is somewhat lag-free)
  - farming
  - fireflies
  - game_commands
  - give_initial_stuff
  - map
  - screwdriver
  - sethome
  - spawn
  - tnt
  - weather

**Comment by Thomas--S** [comment]
I guess that as soon as we break away from MTG completely, we should offer a CTF environment to be used for map creation, too. It'd be rather illogical to use MTG for map creation (as it is now) when the real CTF game would have nothing to do with MTG then.

**Comment by ClobberXD** [comment]
@Thomas--S I was actually thinking of that very idea - the same CTF game should be used for map-creation as well. How would you suggest we detect map maker mode vs CTF mode? Ideally, automatic detection would be nice to have. But what would we check for?

**Comment by Thomas--S** [comment]
Probably check for singleplayer?

**Comment by ClobberXD** [comment]
That would unfortunately restrict collaboration among multiple players to make a map.

Would WE enabled indicate map maker mode? WE is only used in the `map_maker` mod.

**Comment by LoneWolfHT** [comment]
I use WE for ingame debug (//lua).

**Comment by ClobberXD** [comment]
Offtopic, but the `luacmd` mod provides a `/lua` chat-command that does the exact same thing, but with one `/` less. You'll need the `lua` priv, btw.

**Comment by Thomas--S** [comment]
> Offtopic, but the luacmd mod provides a /lua chat-command that does the exact same thing, but with one / less. You'll need the lua priv, btw.

Personally, I think that WE is the more comfortable approach, you'll need one mod installation less (luacmd), as WE is needed anyway.

---

Back to topic: Most maps are probably created in singleplayer, so this could be the main distinction feature. Additionally, we could add a conf flag for map making, or check for a special admin user name (similiar to the singleplayer approach), or use a chat-command to toggle the modes.

**Comment by ClobberXD** [comment]
As I noted earlier, some players prefer to collaborate with others while making maps (which is perfectly okay), so checking for singleplayer misses this edge case. The conf-approach is good, but that requires the player to manually toggle the setting whenever they want to switch modes. Ideally, it should be a little less manual, but I'm okay with the conf-based approach for the time-being.

> use a chat-command to toggle the modes.

Modes can't be determined at runtime, AFAIK, because "modes" are essentially omissions of certain files in `ctf_map_core` depending on a condition (which is currently the presence of the `ctf` mod).
