### ISSUE TITLE
Give player more points for capturing flag

### ISSUE THREAD

**Issue by JostP** [MT-CTF/capturetheflag#477]
Currently we get 35 points for capturing.

Since server has so many pros and consequently longer matches, we should get more points for capturing. Also number of points should dependent on how many players are playing and how long a match lasts. This will encourage players to put more effort into capturing. Point of game is capture the flag and not kill as many players as you can, isn't it ?
I suggest to give player between 35 and up to 400 (for very long matches where 20+ pros/30 players are playing) points.

And second suggestion: give every member of a team who won some points. This could encourage players to help a player who has the flag and work as a team.

**Comment by ClobberXD** [comment]
I support this suggestion. Flag grabbing and capturing score computations need to be much more wholesome and... just plain higher. The pathetic score for grabbing and capturing a flag is just not rewarding at all. e.g. Grabbing the enemy flag awards a player 10 measly points. For that, I could just kill a nub with a steel sword (or better) and I'd get _at least_ 14 points.

**Comment by Thomas--S** [comment]
I also support rising the points for these a bit, and additionally add difficulty-related points.

At first, I thought that the time-based approach might be very promising, but I fear it might lead to artificially prolonged matches. I think that the approach of calculating the capture points on cumulative team scores might be the better one.

**Comment by ClobberXD** [comment]
Score obtained for attempts and captures have been doubled (d25e060d9056c97725d6017d94c4a7d7b58f0484). But this feature request hasn't been fully attended to yet, as the author also requests that the score should vary depending on the strength of the enemy team.

**Comment by xenonca** [comment]
@JostP I think this has been solved already by now?

**Comment by JostP** [comment]
I think it has already been solved.

> Give every member of a team who won some points. This could encourage players to help a player who has the flag and work as a team.

Maybe just mention second suggestion, to think about it.
