### ISSUE TITLE
Map maker: Barrier problems

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#479]
![](https://cdn.discordapp.com/attachments/631489123865198613/633375780230922254/Zaslonska_slika_2019-10-14_20-45-49.png)

Original bug report and screenshot by @JostP

**Comment by JostP** [comment]
Red barrier is also always placed on X = 0, whether you choose X or Z.

**Comment by ClobberXD** [comment]
PR: #485. PR will replace this issue in the `2.0.0` milestone
