### ISSUE TITLE
Moving items in the treasure chest

### ISSUE THREAD

**Issue by MinetestSam** [MT-CTF/capturetheflag#480]
So if you scroll wheel down on an item which is stackable in the treasure chest and then scroll wheel up in the empty spaces, you can move the item in the empty slots
![screenshot_20191024_120607](https://user-images.githubusercontent.com/42088654/67459418-3054e080-f656-11e9-92ad-4cda969e329c.png)

**To Test**
1. Open a treasure chest
2. Scroll wheel down on an item which is stackable like cobblestone or wooden planks
3. Scroll wheel up in the empty spaces

**Comment by ClobberXD** [comment]
#56 has been fixed somewhen. The ability to move items *within* the treasure chest inventory is still possible. I'll re-open this issue to serve as a reminder.

Btw, do we really want to restrict player from moving stuff around within the chest?

**Comment by LoneWolfHT** [comment]
I don't think it matters if players can move things around in the chest. Comment if you disagree. Closing for now
