### ISSUE TITLE
Classifying items on the basis of rarity 

### ISSUE THREAD

**Issue by MinetestSam** [MT-CTF/capturetheflag#483]
Classifying items as common, uncommon, rare and legendary by changing the colour of description. Example below

![](https://cdn.discordapp.com/attachments/448136308108296213/638642153307766795/unknown.png)

**Comment by MinetestSam** [comment]
For now I have considered 4 categories, that is, common, uncommon, rare and legendary with items falling under common category being depicted by grey/dark green color, for uncommon it would be blue color, for rare it would be red and for legendary it would golden.

**Comment by ClobberXD** [comment]
Sounds interesting. How do you plan on categorising them? It'd be a pain to manually classify them, and things would break after an update or two.

**Comment by MinetestSam** [comment]
Yep I am thinking about how to tackle the MTG updates
