### ISSUE TITLE
Place barriers at runtime, and keep the schem clean

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#494]
Doing so would:

- Make it a lot easier to replace all nodes in the middle with barrier nodes, as we'd know what the original nodes are. We could even use two LVMs (one with original nodes, and one with barrier nodes) and swap them at the end of buildtime, like framebuffers.
- Remove compat issues, because maps won't have any barrier info. If we for example, change the barrier node to pink wool, existing maps would still fare alright, in spite of looking like alien poop.
- Make the process of map creation much more stream-lined, as map makers wouldn't have to bother about the barriers or the problems that come with them.

**Comment by Thomas--S** [comment]
:+1:

**Comment by ClobberXD** [comment]
:+1:

**Comment by ClobberXD** [comment]
Adding to 2.0.0, as I'd consider this a very important change. Breaking changes should only come with major releases.

**Comment by ClobberXD** [comment]
Since barriers won't be placed during the map-making stage, #354 is now high priority as well, and will precede this PR as some sort of visualisation is required for this idea to be feasible.

**Comment by rubenwardy** [comment]
This is very likely to increase the load time and number of packets. I suggest making sure it doesn't do that too much

**Comment by ClobberXD** [comment]
I'm trying to keep bulk node placements as minimal as possible. I'm planning to populate the LVM buffers once during loadtime, and they will remain for the rest of the server session. Every time the match starts, the barrier LVM will be activated, and once the buildtime ends, the non-barrier LVM will be activated. I don't think it's possible to reduce node placements much further.
