### ISSUE TITLE
Make map selection random again

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#497]
Two things:

- Number of maps have increased tenfold.
- Maps have been de-coupled from this repository, so we can't hardcode stuff depending on the number of maps.

My proposal: Implement both cyclic and random map selection, but employ the appropriate technique based on the number of maps. I'd say random selection if `#maps >= 10`.

**Comment by KaylebJay** [comment]
I'm completely in favor of this! Random maps are a LOT better and it fixes the issue I already brought up about three mese maps in a row.

**Comment by Thomas--S** [comment]
I approve this concept, but I'm not sure about the changed behaviour depending on the number of maps. Instead, I'd suggest to introduce a .conf setting for this.

**Comment by ClobberXD** [comment]
Yes, that's the plan, but the setting would be the lower limit for the number of available maps, to make use of random selection instead of cyclic selection.

If you rather prefer the selection mode itself to be settable using a setting, that's perfectly fine with me too. We could drop the idea of employing either of the modes based on number of maps.

**Comment by ClobberXD** [comment]
@KaylebJay Random was how CTF originally rolled. When multiple maps were introduced, we had 2H2L, Bridge, and Caverns, and we used random selection right from the start (see a3f5e065 and aa960557). But then there wasn't much scope for "random" when there are only 3 maps available, and we ended up playing two maps over and over again. I kept on ranting that the random wasn't random enough due to the very low number of maps, and rubenwardy made the selection cyclic in order to shut me up (see d3c8f393).

**Comment by Thomas--S** [comment]
> Yes, that's the plan, but the setting would be the lower limit for the number of available maps, to make use of random selection instead of cyclic selection.

This is indeed a very good idea, as this also contains the option to always use a certain mode by either using a very low or a very high breakpoint.

> If you rather prefer the selection mode itself to be settable using a setting, that's perfectly fine with me too. We could drop the idea of employing either of the modes based on number of maps.

No; your setting suggestion is much better than mine.
