### ISSUE TITLE
Increase rules' window width

### ISSUE THREAD

**Issue by JostP** [MT-CTF/capturetheflag#504]
On devices with small resolution this happens:

![Zaslonska slika 2019-11-12 15-36-45](https://user-images.githubusercontent.com/47271658/68680677-62c17180-0562-11ea-925f-f95af77a7469.png)

**Comment by ClobberXD** [comment]
This issue would be better suited for https://github.com/MT-CTF/rules, although issues have been disabled in that repo...

@rubenwardy
