### ISSUE TITLE
Collision boxes of dead players are not restored at the start of a new match

### ISSUE THREAD

**Issue by MinetestSam** [MT-CTF/capturetheflag#506]
Collision box is not returned to default if the player never respawns when the flag is captured. This results in the player having no collision box on the next map. The player can get back to the normal collision box only by killing themselves.

**To Test**
1. Make a private server
2. Log in through two accounts.
3. Kill the other player and make sure to NOT respawn with the player that has been killed
4. Grab the flag and end the game.
5. In next match, you'll see that the player that was killed still has no collision box at all

**Comment by ClobberXD** [comment]
That's quite weird, because the collisionbox data should persist across matches, and should be restored when a player respawns, even if it's a different match.

**Comment by MinetestSam** [comment]
Did test this on the latest version of CTF and it does seem to be a bug.

**Comment by ClobberXD** [comment]
Tested, can reproduce.
