### ISSUE TITLE
Crafting with full inventory

### ISSUE THREAD

**Issue by JostP** [MT-CTF/capturetheflag#520]
It has happend to me twice. I had full inventory with 4 mese or more. Then I dug something and forgot that I have full inventory and I pressed "craft mese sword" button. And yay mese sword disappeared unknown where, so I didn't get it.
I think this is a bug because sword should be dropped and not wasted when you have full inventory

**Comment by ClobberXD** [comment]
@rubenwardy This belongs to the `crafting` mod, I think.

**Comment by JostP** [comment]
Should I make issue in repository rubenwardy/crafting?

**Comment by ClobberXD** [comment]
Yes, please
