### ISSUE TITLE
Make bounties secretive and randomise the score

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#532]
There's no fun in a bounty if everyone including the target knows about it. Making them secretive would allow for two things:

- No one would know who the bounty is, until the target is killed, making for a fun, edge-of-the-seat gameplay.
- A random bounty score, which is more realistic and thrilling, compared to a fixed score.

**Comment by MinetestSam** [comment]
> * A random bounty score, which is more realistic and thrilling, compared to a fixed score.

How would you calculate the score? Will it be based on score and K/D? Or do you want to make it completely random?

**Comment by ClobberXD** [comment]
The bounty prize would be totally independent from the target's stats. i.e. a less pro has an equal chance of getting a large prize on their heads as a "pro" pro does. The score would be a random value between x and y (250 - 500 maybe?).

**Comment by Thomas--S** [comment]
I think that a score based value +/- a random value might probably be more appropriate to reflect the different difficulty levels.

**Comment by ClobberXD** [comment]
I think a completely random score would be more engaging. Players don't know who's the bounty, and they'll not have to play *for* the bounty. I'm thinking of making bounties completely random so that there's the element of luck. Putting in sweat and tears to kill a "pro" pro and realising that the bounty was just 50 points would all be a part of the game. Also, since players wouldn't know who the target is, even a meagre prize of 50 points is a plus.

**Comment by Thomas--S** [comment]
I can see your point. I think that different kinds of players probably prefer one or the other approach.

Maybe this should be decided by the players in a poll?

**Comment by ClobberXD** [comment]
Closing, as the majority of players voted against this feature in the poll.
