### ISSUE TITLE
Take victim's "time since last death" into kill score calculation

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#537]
If a player dies very infrequently, that tells a lot about their strategy and play-style. Even if they haven't killed enemies much, they're very careful about their movements and stick together with their team-mates (or they're just tunnelling in the furthest reaches of the map). Essentially, such players are much harder to kill, and their killers should be rewarded with more score. Hence my proposal is to take "time since last death" of victim into consideration while calculating kill score.

**Comment by MinetestSam** [comment]
What about players who are just newbies/noobs and stay inside their base for quite a long period of time?

**Comment by ClobberXD** [comment]
Well, they're harder to kill, because they're away from the battlefield for whatever reason. You'd maybe get 8 or 9 points instead of the usual 7. ;)

**Comment by Thomas--S** [comment]
:+1:
