### ISSUE TITLE
Wrong icon with death by gun in kill history

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#566]

**Comment by ClobberXD** [comment]
Pretty simple to fix, **but** this would keep repeating if we change names or add more guns. This is because `ctf_events` checks for the `shooter` substring in the item-name. A more robust solution would be to make use of item groups for this purpose. `shooter` doesn't add any groups, AFAIK, so we may need to make some changes.

**Comment by rubenwardy** [comment]
I think this may have been due to the shooter gun names changing from shooter: to shooter_guns:.

But I don't think this is still the case, and it would be good to merge this into the general kill history icon issue.

Side-note: there's also the issue that the way we get the wield item is completely wrong. The player get_wielditem() is checked at time of damage, not of time of use

**Comment by ClobberXD** [comment]
> I think this may have been due to the shooter gun names changing from shooter: to shooter_guns:.

That's exactly the issue, and that's what I'm trying to fix now. PR coming soon :tm:.

> But I don't think this is still the case, and it would be good to merge this into the general kill history icon issue.

Do you mean this bug doesn't exist now? I'm sure it does, I've checked it myself.

Btw, we don't have a general kill history issue yet :)

> Side-note: there's also the issue that the way we get the wield item is completely wrong. The player get_wielditem() is checked at time of damage, not of time of use

True. This is the reason why we have to handle throwables in a special way (read hacky way). Fixing this is a little less straight-forward than fixing the subject of this specific issue. I am planning to try and fix this, but it's going to take some time.
