### ISSUE TITLE
Medkits seem to not work with knights

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#571]

**Comment by LoneWolfHT** [comment]
Does it check with hp_max or 20?

**Comment by ClobberXD** [comment]
[Medkits heal upto exactly 20 HP](https://github.com/MT-CTF/capturetheflag/blob/063707c0b677322edf57163024e4c6370ceb8de3/mods/pvp/medkits/init.lua#L9). This is an over-sight, and I think a medkit should heal a player completely, no matter how high their hp_max is.
