### ISSUE TITLE
Class isn't saved

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#574]

**Comment by rubenwardy** [comment]
It looks like it does remember, because clicking the same class doesn't show the class change message. But the initial stuff and update() is wrong

**Comment by rubenwardy** [comment]
Not a bug, the classes GUI is shown explicitly

**Comment by ClobberXD** [comment]
Change of perspective is a great way to fix bugs, at times. :D

**Comment by rubenwardy** [comment]
There is no bug, there's this code in ctf_classes:

```lua
minetest.register_on_joinplayer(function(player)
	ctf_classes.update(player)

	if minetest.check_player_privs(player, { interact = true }) then
		ctf_classes.show_gui(player:get_player_name())
	end
end)
```
