### ISSUE TITLE
Falling through the world

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#575]
This happens with both 5.1.1 and 5.2.0-dev clients

Maybe something wrong with the player model?

**Comment by rubenwardy** [comment]
hit box is also invisible during this time

**Comment by MinetestSam** [comment]
> hit box is also invisible during this time

My guess is that, this may be something related to the collisionbox mod

**Comment by MinetestSam** [comment]
Can confirm after testing that this has something to do with the collisionbox mod.

**Comment by rubenwardy** [comment]
I have reverted collisionbox

**Comment by ClobberXD** [comment]
Problem solved?

**Comment by MinetestSam** [comment]
> Problem solved?

Yes, I think it has been solved.
