### ISSUE TITLE
Can place class items into team chest by swapping

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#576]
* Click item in team chest
* Click class item
* Click old slot

**Comment by MinetestSam** [comment]
Same as #56 and this is an engine bug as far as I know.

**Comment by ClobberXD** [comment]
:point_up_2: I tried to fix #56 by adding `on_metadata_inventory_put`, and then realised that the callback won't even be invoked when items are put into inventories by swapping (I remember filing a bug report in MT, but I can't find it).

Assuming that this isn't fixable at the moment, I suggest we look into other ways to prevent unauthorised players from using it.

**Comment by ClobberXD** [comment]
Is this reproducible in 5.3.0-dev? I'm unable to reproduce this, and I'm unable to bypass meta inv. callbacks using swapping on the whole.

**Comment by ClobberXD** [comment]
Never mind, I can reproduce this again. *sigh*

**Comment by ClobberXD** [comment]
Folding this into #56, as the root cause is the same.
