### ISSUE TITLE
[Question] CTF setting not taking effect

### ISSUE THREAD

**Issue by grantcarthew** [MT-CTF/capturetheflag#580]
Hi,

Sorry to add to the noise however I can't find a solution to this issue myself.

I'm running a v5.2 mintestserver with the `--config` option pointing to a `minetest.conf` file. I've copied all the CTF settings into the file and when I run the server the console reports the settings. They don't seem to affect the game though.

Specifically build time. I have dropped it down to 60 and yet the game still takes 4 minutes to start.

Can you please give me an idea as to what I am doing wrong? Where should I be changing the `build_time` setting?

Thanks. It's a great game and the kids are loving it in these "stay at home" times.

Here is the `minetest.conf` file I'm using:

```bash
server_name = Minetest Capture The Flag
port = 30001
default_game = capturetheflag
default_password = xxxxxx
max_users = 30
name = xxxxxxxxx

# Following settings are from the game minetest.conf
give_initial_stuff = true
enable_pvp = true
mg_name = singlenode
vote.kick_vote = false
barrier = 106
hpregen.interval = 6
hpregen.amount = 1
random_messages_interval = 60
sprint_stamina = 10
enable_lavacooling = false

#
# CTF_PVP_ENGINE
# See mods/ctf_pvp_engine/minetest.conf.example for ctf_pvp_engine settings.
#

ctf.colors.skins = true
ctf.colors.nametag = true
ctf.colors.nametag.tcolor = false

ctf.flag.capture_take = true
ctf.flag.waypoints = true
ctf.flag.nobuild_radius = 3
ctf.flag.alerts = true
ctf.flag.drop_time = 600

ctf.allocate_mode = 4
ctf.players_can_change_team = true
ctf.friendly_fire = false
ctf.autoalloc_on_joinplayer = true

ctf.match = true
ctf.match.teams = 2
ctf.match.team.1 = red
ctf.match.team.1.color = red
ctf.match.team.1.pos = 7,65,93
ctf.match.team.2 = blue
ctf.match.team.2.color = blue
ctf.match.team.2.pos = -22,66,-78
ctf.match.build_time = 60
ctf.match.clear_inv = true
ctf.match.destroy_team = true
ctf.match.reset_on_winner = true
ctf.match.map_reset_limit = 200
ctf.match.remove_player_on_leave = true

```

**Comment by rubenwardy** [comment]
CTF includes some bash scripts to optimise out settings. You need to make sure not to use update.sh or build.sh if you want to be able to change settings using a .conf. If you didn't run those, then there's another issue somewhere

**Comment by grantcarthew** [comment]
Ah, you ripper. That's what the problem is.
I see the bash script does a grep replace on the actural lua files.
I'll re-install without running all of the update.sh script.

Thanks a heap and happy Easter!

**Comment by grantcarthew** [comment]
Better yet, I'll change the settings in the `settings_cache.csv` file and run it again.

Thanks.
