### ISSUE TITLE
Shotgun is way too OP

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#582]
The _humble_ shotgun's fire-rate is much faster in shooter v0.6.1. This corresponds to how fast shotguns fire IRL a _little_ more accurately, but it's now on the faster side. This makes the shotgun way too OP, as its rounds/ammopack or rounds/reload is way too high (~40-ish rounds/ammopack). The increase in fire-rate seems to be an intentional change, but I'd consider this a bug nonetheless.

Possible solutions (non-exhaustive):

- Reduce fire-rate
  The fire-rate is a little more realistic, but it's now on the faster side and it's still insanely fast.
- Reduce rounds/ammopack
  This stat is extremely unrealistic, as shotgun ammo is physically much larger than the normal variants.
- Nerf reload mechanics
  This option is a little more thorough, and requires a sizeable chunk of modification to `shooter`'s API. The idea is to make reloads last longer than a left-click, by actually implementing a "cool-down" time during which guns can't be fired. Implementing this approach would also nerf the SMG, which is insanely OP in v0.6.1, due to automatic fire.
- Combinations of individual options
  I'd personally prefer this approach, as multiple aspects of individual guns (and shooter as a whole) are unrealistic and OP.

****

This is game-breaking, as players wielding shotguns or SMGs are virtually invincible as long as they have ammo. Needs to be fixed before the release of v2.0.

**Comment by Calinou** [comment]
I vote for "Combinations of individual options" personally. Be sure not to do overdo it though, you don't want to make shotguns completely useless and have nobody use them anymore.

**Comment by ClobberXD** [comment]
As a quick fix (v2.0 release is nearing), my plan is "Reduce fire-rate + Reduce rounds/ammopack".

Nerfing the reload mechanics is a little more involved, `<shameless_plug>` and frankly, I'd replace shooter with another mod like [gunslinger](https://github.com/ClobberXD/gunslinger) altogether. `</shameless_plug>` :man_shrugging:

**Comment by ClobberXD** [comment]
Didn't have a better place to post this (:P), so here it goes:

The reason why I think most guns in shooter have insanely high rounds/ammopack is _probably_ because guns would consume ammo-packs faster/slower depending on their rounds. This becomes somewhat unfair, as the same ammo pack (crafted using the same quantity and type of materials) would be consumed much quicker or last much longer depending on the gun used. There are a couple of ways to get around this limitation:

- Using different caliber ammo-packs for different guns

  Basically having separate ammo-pack craftitem for each guns, with varying crafting recipes if required. The downside to this approach is that players now have to remember which type of ammo each gun would consume, and multiple ammo-packs add to the clutter.

- Ditching the concept of ammo-packs and using craft-items to represent individual bullets

  The advantage to this approach is that the same bullet can be used by all guns, and the number of bullets consumed would be directly equal to the magazine size of the gun. This is a much simpler approach, both for players and modders. This approach is used by the `ranged_weapons` mod and the `gunslinger` mod.

(It's to be noted that `ranged_weapons` also has multiple calibers of ammo, in spite of using this approach, because realism)

**Comment by ClobberXD** [comment]
PR: #583
