### ISSUE TITLE
ctf_map error how do I fix it

### ISSUE THREAD

**Issue by nathsmcn08** [MT-CTF/capturetheflag#587]
ModError: Failed to load and run script from /home/username/snap/minetest/1521/.minetest/mods/ctf_map/init.lua:
Unknown node: ctf_map:ind_stone
stack traceback:
	[C]: in function 'get_content_id'
	....minetest/mods/ctf_pvp_engine-master/ctf_map/barrier.lua:1: in main chunk
	[C]: in function 'dofile'
	...21/.minetest/mods/ctf_pvp_engine-master/ctf_map/init.lua:16: in main chunk

**Comment by ClobberXD** [comment]
@nathsmcn08 It looks like you're running an outdated version of the `ctf_map` mod. You can install the latest version of the mod from https://content.minetest.net/packages/rubenwardy/ctf_map/download/, or from the Content tab in-game.
