### ISSUE TITLE
Switch to GitHub actions

### ISSUE THREAD

**Issue by Panquesito7** [MT-CTF/capturetheflag#589]
GitHub actions is faster, easier and better to use.
IMO, I think it would be nice to change to GitHub actions.

**Comment by Calinou** [comment]
Sounds fine to me, although we're not especially hitting performance concerns with this repository :slightly_smiling_face:

**Comment by ClobberXD** [comment]
I'm not sure if switching to GH actions is worth the dev time invested in making it happen. But if someone is willing to do it, I have no objections.
