### ISSUE TITLE
Add diggable = false to flags

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#597]
Will allow falling nodes to be re-enabled

```lua
diggable = true,  -- If false, can never be dug
```

**Comment by LoneWolfHT** [comment]
What about people flooding the base with gravel?

**Comment by rubenwardy** [comment]
well, I guess it shouldn't be re-enabled. The node should still have that flag though

**Comment by ClobberXD** [comment]
:+1: Didn't know such a field even exists. However, I'm not too keen on falling nodes until we have a robust anti-griefing measures.

**Comment by LoneWolfHT** [comment]
I think falling nodes will have an on_touchdown() or something similar that could be used to make falling nodes drop as an item if they drop near the flag
I wonder if for now we could just use on_construct() :thinking:

**Comment by ClobberXD** [comment]
There's also the issue of players filling up enemy bases with falling nodes.

**Comment by LoneWolfHT** [comment]
\*could be used to make falling nodes drop as an item if they drop near *any* flag
