### ISSUE TITLE
SMG duplication bug

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#598]
Switching to a different inventory slot while firing an SMG results in the SMG being duplicated over to the new slot, replacing the previously existing item. ~~Upon further testing, I noticed that the duplicated SMG items are unusable (thank the heavens).~~

v2.0 can't be released with this bug, so marking as high priority.

:musical_note: Bob the builder, can we fix it? :notes: 
:notes: Bob the builder, yes we can! :musical_note:

**Comment by MinetestSam** [comment]
I did test this in my local world and the SMGs were usable.

**Comment by ClobberXD** [comment]
Dang it, it's worse than I thought. :)

**Comment by ClobberXD** [comment]
Did some digging around. The reason for this bug is that shooter doesn't check if the player is still wielding the same item before continuing to fire. The fix is a two-line change; I suppose that's good news. :)

**Comment by ClobberXD** [comment]
Fixed in 778a1f49
