### ISSUE TITLE
Allow dropping class items; prevent unauthorised players from picking it up instead

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#599]
This would allow class items to be shared between those who can use it.

**Comment by MinetestSam** [comment]
Could you further explain how sharing items would be useful since class items are same for everyone?

**Comment by MinetestSam** [comment]
I think that ammo shouldn't be a class item since it is required by knights, shooters and medics for pistols, shotguns and SMGs.

**Comment by ClobberXD** [comment]
I agree. I thought it wouldn't be much of a problem as ammo is craftable and can be found in chests. But it's better to not take any chances. This PR will be put on hold until we've implemented whitelisting items for classes.

**Comment by ClobberXD** [comment]
It's possible to omit class-items from the blacklist by manually defining the blacklist. With that out of the way, this feature can be implemented.

**Comment by rubenwardy** [comment]
This will result in the ability to get infinite items

**Comment by ClobberXD** [comment]
How about tracking dropped items, and deleting a player's dropped class-items if the player changes class?

**Comment by ClobberXD** [comment]
This PR isn't high-priority enough for the label and milestone.
