### ISSUE TITLE
Add background to hearts

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#60]

**Comment by ClobberXD** [comment]
Maybe use `hudbars` instead?

**Comment by ClobberXD** [comment]
Why was this closed? This is a simple feature which can be implemented using another stat-bar placed behind the health bar, which will always be full.

`hudbars` would be nice, but the commit that removed hudbars cited lag as the reason for removal. So normal stat-bars are fine too.
