### ISSUE TITLE
End respawn immunity by distance

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#612]
> i forgot to mention that you can get to the enemy base within like 15 seconds without losing respawn immunity
> if you use a shooter class with a grapple
> i remember a recent match where someone was grabbing the flag like every 30 seconds

**Comment by rubenwardy** [comment]
Lone_wolf suggests removing it

**Comment by ClobberXD** [comment]
I thought we could reduce the time to 5s for a start. But I'm also fine with removing it altogether.
