### ISSUE TITLE
Class items can be put into furnace

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#617]
Class items can be put in furnaces (possibly any node inventory except the team chest). This allows players to change classes and continue to possess a restricted item (like medics wielding swords).

This isn't a problem for guns because there's a class-check on use, but that's not the case with swords.

Here's what I think would be a good solution to this issue:

I *assume* the class-item-restricting code is present within an `on_metadata_inventory_put` for the team-chest. The logic in this callback should be moved to a generic `register_on_metadata_inventory_put` callback, so that it applies to all node inventories.

**Comment by rubenwardy** [comment]
> The logic in this callback should be moved to a generic register_on_metadata_inventory_put callback, so that it applies to all node inventories.

This doesn't exist

**Comment by ClobberXD** [comment]
You're right. I do remember seeing it somewhere though... probably just a feature request. >.<

**Comment by Nifty-Neutron** [comment]
So,
Since the fix isn't present on the server,
I some players abuse the glitch,
would they get punished or not.

**Comment by LoneWolfHT** [comment]
Probably not, it's discouraged though

**Comment by Nifty-Neutron** [comment]
ok,
so can an admin remove the reports from players I reported please

**Comment by Nifty-Neutron** [comment]
I only reported for using this bug and since it's not punishable please remove the reports

**Comment by Nifty-Neutron** [comment]
my username is : Nifty-Neutron
