### ISSUE TITLE
Crash when selecting a class before joining a team

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#621]
```
AsyncErr: ServerThread::run Lua: Runtime error from mod '*builtin*' in callback on_playerReceiveFields(): [...]/mods/ctf/ctf/teams.lua:119: attempt to index local 'team' (a nil value)
```

The classes GUI shows up right after I join a singleplayer world, but since I haven't joined a team yet (related: #489), things mess up. I'd consider this low priority as this can happen only in a singleplayer world.

**Comment by Anthony-De** [comment]
I just crashed the server testing this

**Comment by LoneWolfHT** [comment]
I don't see this error in the crash logs for the past day

**Comment by Anthony-De** [comment]
I tried to select my class before the new teams had been assigned and the server crashed.

**Comment by LoneWolfHT** [comment]
You mean your local testing server?

**Comment by Anthony-De** [comment]
On the public server. I had the class selection formspec open when the round finished. I had to do this several times to get the timing right.
