### ISSUE TITLE
Add dependabot to update submodules daily

### ISSUE THREAD

**Issue by Panquesito7** [MT-CTF/capturetheflag#622]
Currently, there are some submodules outdated (here and in other repositories).
I think it's best to keep them up-to-date.

If you need help setting it up, I can help doing it. 🙂
Link to the app: https://github.com/marketplace/dependabot-preview

**Comment by Panquesito7** [comment]
@rubenwardy?

**Comment by Panquesito7** [comment]
Ping?

**Comment by xenonca** [comment]
Pong!

**Comment by Emojigit** [comment]
ping?

**Comment by LoneWolfHT** [comment]
Pong!

**Comment by LoneWolfHT** [comment]
I think we don't update automatically for a reason

**Comment by Panquesito7** [comment]
It won't be updated automatically, it'll make a PR first when there are updates and it'll prompt you to merge it or not. 🙂

**Comment by Emojigit** [comment]
LGTM

**Comment by LoneWolfHT** [comment]
Well if someone wants to do this they can then I guess. It's a oneliner for me to update a submodule so this is low priority IMO

**Comment by Panquesito7** [comment]
Only someone with administrator access can add it.
In order to do so, follow the next steps:

1. Install the [Dependabot preview](https://github.com/marketplace/dependabot-preview) app for this repository.
2. Once Dependabot is successfully installed, go to https://app.dependabot.com/accounts/MT-CTF.
3. Click on the "Add repos" button. Add the Capture the Flag repository.
4. Choose the "Git Submodules" option. By default it is set to "Ruby".
5. After that, keep an eye for PR's in the repository.

If it didn't work properly, let me know and I'll give you the steps with screenshots. 🙂

**Comment by LoneWolfHT** [comment]
Added to my fork. Not even sure if I have access here

**Comment by LoneWolfHT** [comment]
It's now in the main repo
