### ISSUE TITLE
Can use zoom with sniper rifle without shooter class

### ISSUE THREAD

**Issue by Panquesito7** [MT-CTF/capturetheflag#626]
I've just found that I can use sniper rifle's zoom without being a shooter.
Is this a bug, or is this normal?

**Comment by ClobberXD** [comment]
This is unintended. I assume class-item checks are only applied to `on_use`, @rubenwardy? If so, fixing this would be as simple as applying class-item checks to `on_place` and `on_secondary_use` as well.

**Comment by Beanzilla** [comment]
Having said all that, this could provide a tactical advantage... you could use it to see where the enemy team is coming from. (IF you had line of sight and it wasn't dark)

**Comment by LoneWolfHT** [comment]
Don't need to know how to shoot a gun accurately to know how to use a scope. Could redress this bug in feature clothes
