### ISSUE TITLE
Better balance between classes

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#628]
This would balance out the movement aspect of classes - knights are currently underpowered, compared to shooters (110% speed, grappling gun) and medics (10% speed).

Inputs, suggestions, and alternatives appreciated.

**Comment by LoneWolfHT** [comment]
Why not increased damage with swords instead?

**Comment by ClobberXD** [comment]
My original logic was that knights were stronger, and hence they have more stamina.

> Why not increased damage with swords instead?

I was thinking this won't account for the movement-speed imbalance between classes. But if they can hit harder, I think we can ignore the movement-speed imbalance, as the classes would be balanced overall.
