### ISSUE TITLE
More robust way of purging inventory of class items

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#640]
Currently, there's the problem of certain items being omitted from blacklist, resulting in them being infinitely obtainable by changing classes. I suggest using item meta to differentiate class-items (obtained as part of class initial items) in a more robust way. The following segment of code that removes all class items, can instead purge the player's inventory of *all* items containing the special meta field:

https://github.com/MT-CTF/capturetheflag/blob/baf5f1787815e1a7bbcd62b0ae921acb6098e7bf/mods/ctf/ctf_classes/items.lua#L35-L60

This is a much better solution IMO, and if implemented, we most likely don't need to implement class-change cooldowns as a workaround.

**Comment by Thomas--S** [comment]
Metadata might work perfectly well for items with max stack size of one. But it might be problematic for items with a larger stack size. Either, you'll allow the user to combine different stacks with different metadata, but this will make a separation near impossible; or you'll forbid mixing stacks with different metadata, which will confuse the players.

**Comment by ClobberXD** [comment]
Hmm, you're right. This would indeed work for non-stackable class items, but screws with stackable class items like ammo and bandages. Welp, have you got any better ideas? :)

**Comment by LoneWolfHT** [comment]
It's not too serious if you can stack ammo/bandages. Using meta for items with a stack size of 1 would be a step up at least

**Comment by ClobberXD** [comment]
I agree, but it'll mean that we'll have to rely on two techniques to reliably detect class items. Ideally, a unified detection logic would be best.

**Comment by appgurueu** [comment]
You could not use item meta, but keep track of class items using inventory callbacks. If stacks were merged, you could keep track of how many items of the stack were class items.

**Comment by appgurueu** [comment]
This was implemented.
