### ISSUE TITLE
Use managed HUD elements instead of spammy chat-messages for feedback

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#642]
Use a HUD API resembling the one provided by `hud_scores` (maybe even re-use the same HUD API), to display feedback to player, instead of spammy chat-messages. Examples:

```
<name> is on your team!
<name> has more than <n> HP, you can't heal them!
Feel free to suggest more (no, this isn't a feedback message in-game)
```

The advantage to this is that the player's chat won't be spammed with these messages - they'll be displayed as a HUD element for a couple of seconds and disappear.

**Comment by xenonca** [comment]
`Can't place another marker <x seconds left>`

**Comment by xenonca** [comment]
`You need to wait to change class again`
`You can't explode smoke grenade so close to you flag!`
`Pillar digging started`
`Pillar digging stopped at undiggable noce Can activate again in x seconds`
`You can't activate yet`
`Can't dig node or build time active`
`<player> has x HP. You can't heal them`
`<player> is now a <class>`  

Inventory (Crafting):
`Missing required items`
