### ISSUE TITLE
Tweak HUD text element sizes wherever applicable

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#643]
Some applications I can think of, off the top of my head:

- HUD scores; definitely needs to be made a little larger

(yeah, that's it...)

Not strictly required for v2.0.0, but it shouldn't be much of a problem to implement this in time for the release.

**Comment by LoneWolfHT** [comment]
The flag status text could probably be increased in size too. That's sometimes hard to notice for me

**Comment by ClobberXD** [comment]
Agreed. :+1:
