### ISSUE TITLE
Regression: shooter is not particularly child-friendly now

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#649]
Blood splattering ... everywhere!

I wonder if it's possible to override the hit texture from `shooter_tweaks`...

**Comment by Calinou** [comment]
I think it's good to have some kind of visual feedback when hitting someone. We should just replace the blood with something else (even confetti :stuck_out_tongue:).

**Comment by ClobberXD** [comment]
Visual feedback is very important indeed, agreed.

(Hm, I forgot what texture we were using before this regression...)

**Comment by ClobberXD** [comment]
This is the texture that was being used in v1 before replacing shooter with the submodule: https://raw.githubusercontent.com/MT-CTF/capturetheflag/stable-1/mods/pvp/shooter/textures/shooter_hit.png

I'll see if this overrides the original texture when placed in another mod.

**Comment by rubenwardy** [comment]
> I wonder if it's possible to override the hit texture from shooter_tweaks...

Yes, using a dependency

**Comment by ClobberXD** [comment]
> you could make a game texture pack by making a folder at `games/capturetheflag/textures`

Oh that's neat!
