### ISSUE TITLE
Reminder: Revert inventory swap workarounds

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#651]
This can be done once minetest/minetest#9923 has been merged. It should be okay to attend to this after the grand v2 release.

**Comment by xenonca** [comment]
Looks like it's been merged :P

**Comment by appgurueu** [comment]
Yes, the workarounds can be removed now.

**Comment by appgurueu** [comment]
@savilli so the workarounds have been removed? Comment on why you're closing an issue, or tag it appropriately.
