### ISSUE TITLE
Reinforced cobble can be used to trap players

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#660]
This is because players spawn with stone pickaxes by default, which can't break `cracky=1` nodes.

- Changing reinforced cobble to `cracky=2` results in it being as *soft* as normal stone and cobblestone.
- Making stone pick capable of breaking `cracky=1` nodes allows players to mine many more hardy nodes like ores, [steel|bronze] blocks, etc.
  - I've also tried `cracky=2` + `level=2`, but the `level` group only affects wear, and not dig times.

Any ideas?

Note: This also affects v1, and the fix needs to be backported to it.

**Comment by Calinou** [comment]
> Making stone pick capable of breaking cracky=1 nodes allows players to mine many more hardy nodes like ores, [steel|bronze] blocks, etc. 

I'd prefer this solution. Just make it quite slow so reinforced cobble is still useful.

**Comment by ClobberXD** [comment]
Making stone pickaxes mine `cracky=1` was my original plan, but then I realised that most other hard-to-dig nodes can be dug with a stone pickaxe. While I'm personally fine with this change, I'd like to know the opinion of others.

Also, I initially tested mining `cracky=1` nodes with a digtime of 8s, and it felt correct to me. Should it be more/less? Thoughts?

**Comment by KaylebJay** [comment]
Sounds good to me. Changing the stone pick to `cracky=1` is quite trivial and won't affect the speed or strength of the pick (sort of).

**Comment by ClobberXD** [comment]
#663
