### ISSUE TITLE
Different colors of damage cobble for different teams

### ISSUE THREAD

**Issue by random-geek** [MT-CTF/capturetheflag#676]
Basically just the title. Currently damage cobble is just red, which is confusing since that's also a team color. I suggest making it like team doors—a generic item in chests, which becomes a different node when placed.

**Comment by MinetestSam** [comment]
I disagree. Knowing the colour of the trap would just prevent anyone from breaking it but if you don't know the colour or the team who place it then it is a 50-50 risk which is the point of the trap.

**Comment by xenonca** [comment]
I think this issue can be closed?
