### ISSUE TITLE
Power shields

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#69]
The base would be covered with a shield which is powered by two other generators outside the base. If an enemy touches the shield, they get damaged and knocked back. The generators can be damaged to take down the shield

* Needs power?
* Repairing?
* Build initially

**Comment by ClobberXD** [comment]
Interesting new idea! But this will make the light-weight game much more complex IMO, and consequently worsen lags...

**Comment by rubenwardy** [comment]
The server has plenty of spare CPU - the issue with the server is network and Minetest-related

**Comment by afshaan4** [comment]
is the game served over a CDN? That would solve some network lag issues.

**Comment by rubenwardy** [comment]
> is the game served over a CDN? That would solve some network lag issues.

You can't serve a game server over a CDN as, by definition, CDNs only work with static content. The closest alternative would be location nodes for the server, but Minetest does not support this unfortunately

**Comment by afshaan4** [comment]
Oh, ok.
