### ISSUE TITLE
Weapon balance

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#70]
Cross bows are pitifully weak
Guns are too weak for distance - it's often easier to run and use a sword

Related: #15

**Comment by ThomasMonroe314** [comment]
I agree the swords beat just about everything.
Maybe look at adding some guns from the ranged weapons mod.

**Comment by AKryukov92** [comment]
You can add special features to crossbow
Options:
- slow down
- drop current item
- drop flag

**Comment by AKryukov92** [comment]
Imagine situations for "drop current item":
1. swordsman "just runs" to crossbowman, gets hit by arrow, loses his sword and needs to pick it up back. Crossbowman or someone else can pick it first and kill enemy with his own weapon.
2. swordsman takes serious damage, starts eating apples, gets hit by arrow and loses apples. 1 second without apples under pressure and he is dead.

Item should fall behind victim of arrow to make sense.
Crossbow becomes perfect support weapon. It can counter sword of any quality and reduce impact of apples.

**Comment by ClobberXD** [comment]
Interesting ideas - thank you for the clarification. It is probably a little difficult to implement though - dropping behind the player requires a lot of modifications to the shooter mod and a few others too...

**Comment by afshaan4** [comment]
You say guns are too weak for distance, but
Often when an opponent if far a rifle is quite effective and for closer combat the shotgun with a sword works great.

I agree with @AKryukov92  adding extra features to the crossbow would be great, it's kinda useless as it is.

**Comment by ThomasMonroe314** [comment]
like maybe exploding arrows? :smiley:

**Comment by afshaan4** [comment]
yeah that would be interesting.

**Comment by AKryukov92** [comment]
I made PR which adds extra feature for crossbow: drop current item of arrow target.

**Comment by appgurueu** [comment]
Does it occur with a chance ?
I mean, else it's too overpowered.

**Comment by appgurueu** [comment]
Crossbows aren't so weak.
In caverns, you can use them to trap enemies in tunnels(make them stuck)

**Comment by afshaan4** [comment]
We know, but it barely does any damage

**Comment by afshaan4** [comment]
i though it was a ~~bug~~ feature

**Comment by AKryukov92** [comment]
Crossbows are really not so weak.
You can cause heavy lag for whole bunch of players with your x-bow.

**Comment by afshaan4** [comment]
Lag != Damage
We don't want lag
