### ISSUE TITLE
Missing damage_cobble from ctf trap for paxel

### ISSUE THREAD

**Issue by mazes-80** [MT-CTF/capturetheflag#705]
"wool:" class also get skipped
[damage_cobble.patch](https://github.com/MT-CTF/capturetheflag/files/5582921/patch.txt)

sorry I do not open PR for the near one line patches

**Comment by LoneWolfHT** [comment]
I'm not going to add damage cobble to the list. It should be dug normally

**Comment by mazes-80** [comment]
Still "wool:" remains in list is_diggable, but it will never be reached because of the find("default:" before is_diggable

**Comment by mazes-80** [comment]
I don't know the good way, or remove ' or find("wool:")' from is diggable or remove 'find("default:") before calling is_diggable

Sorry I just red lines very fast while playing. Not easy to guess intentions

**Comment by LoneWolfHT** [comment]
If it's not `default:` then it's `wool:` or something else. If it's `default:` I don't want it to reach `wool:`
Looks like there is no wool map anymore though so I've removed that and added some other nodes

**Comment by mazes-80** [comment]
what I meant is that "or 'wool:'" from is_diggable would never be reached as previous condition before entering in it is checking "default:" in remove_pillar.
Anyway, no need to be picky as wool: is not used anymore
