### ISSUE TITLE
Improve mapmaker mod

### ISSUE THREAD

**Issue by xenonca** [MT-CTF/capturetheflag#706]
Especially for newbies it is atm pretty difficult to straightly dive in and create a map imo. I think this is not only but also due to unclear instructions from in-game. Assuming I'm relatively new to map creation I wouldn't really know what R, H and other values in the GUI actually mean in this context. The [README.md](https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_map/map_maker/README.md) file provided in the mod is quite helpful here, which is why I think it'd be great to see the content of that file in-game too. It would also be great to extend the readme file a little with information on how to submit maps (where and which format) to a place where they can be reviewed, and some minimal requirements (such as a screenshot and license) the map should meet.
Another thing is that map creators should be able to type in every info that needs to (or can) be defined in the `map.conf` via the in-game `/gui`, such as hints, treasures or license.
***
I know this probably requires a lot of modifications to the mod, but I really hope some devs are willing to work on it at some time. This would save a bit of time for future new maps and facilitate the process of submitting a map for map creators.

**Comment by Avyukt1** [comment]
Well, As I saw, there is very little code in the [Maps](https://github.com/MT-CTF/maps) folder. The main code is in this repository. There is an issue regarding the code in this repository while the issue is creates there. See [The Issue](https://github.com/MT-CTF/maps/issues/157#issue-752718810) and just try making the changes.

**Comment by xenonca** [comment]
So the only way to create a map at the moment is using `Z=0`?

**Comment by Avyukt1** [comment]
Yes! The `X = 0` doesn't work properly/

**Comment by Avyukt1** [comment]
Instead of fixing `X = 0`,  what if we remove the option in the map maker GUI?
