### ISSUE TITLE
Kick players with enemy flag and staying on his team base too long

### ISSUE THREAD

**Issue by ghost** [MT-CTF/capturetheflag#75]
I hate teammates that steal flags and stay AFK on our base!

**Comment by ClobberXD** [comment]
Probably warn them on the first capture timeout and kick them on repetition?

**Comment by Coder12a** [comment]
Don't forget to kick flag bearers that stay around the enemy's base too long.

**Comment by Thomas--S** [comment]
> Probably warn them on the first capture timeout and kick them on repetition? This should also persist across matches, since it isn't logical to warn them once before kicking, every single match. Maybe also add reminders that are sent to the player every 30 seconds, starting from 3/4 minutes after flag has been taken?

If implementing this, please remember situations where it is impossible to end because the enemy team has the flag too.
