### ISSUE TITLE
Correction: "Craft 6 cobbles and 1 steel ingot together to make reinforced cobble."

### ISSUE THREAD

**Issue by jasonkhanlar** [MT-CTF/capturetheflag#750]
https://github.com/MT-CTF/capturetheflag/blob/0c9cd8ea2ecac77e5f7320956bcac42fc8c819f9/mods/other/random_messages/init.lua#L61

Shouldn't 4 be 6?

**Comment by TSafa-23** [comment]
Yeah, good eye
