### ISSUE TITLE
It is possible to hit and kill yourself

### ISSUE THREAD

**Issue by EliasFleckenstein03** [MT-CTF/capturetheflag#756]
I discovered it a while ago, and it leads to very strange kill messages. I mean how is that even possible? Should you get the message "You are in your team!" ?

How to reproduce:
Using a dragonfire script:
```lua
minetest.register_globalstep(function()
	local player = minetest.localplayer
	if not player then return end
	local playercao = player:get_object()
	local control = player:get_control()
	if control.dig then
		playercao:punch()
	end
end)
```
Do not ask me how I found this out.

**Comment by Calinou** [comment]
The server should be blocking self-damage attempts on the server side.

**Comment by realOneplustwo** [comment]
I can see how a hacker could use this to farm points.

**Comment by LoneWolfHT** [comment]
Are there any advantages to killing yourself?

**Comment by realOneplustwo** [comment]
You could kill yourself over and over again, and get a lot of points. Fortunately, this is easy to detect, just by looking at the kill feed.

**Comment by LoneWolfHT** [comment]
Oh I guess you don't lose points when you die then

**Comment by EliasFleckenstein03** [comment]
It's possible to kill yourself when you are at 1 heart, which prevents your opponent from getting the score.

**Comment by appgurueu** [comment]
Fixed by https://github.com/minetest/minetest/pull/11137

**Comment by appgurueu** [comment]
As the PR has been merged, this issue can be closed as soon as the server upgrades to newest dev @LoneWolfHT @rubenwardy
