### ISSUE TITLE
I got a question and an error

### ISSUE THREAD

**Issue by geilmaker** [MT-CTF/capturetheflag#779]
Hello, im trying to use the capturetheflag game for minetest, but the game/server is crashing every time when im shooting ranged weapons with the following error:

2021-02-04 21:29:28: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'shooter_guns' in callback item_OnUse(): ...st\minetest-5.3.0-win64\bin\..\builtin\common\vector.lua:59: attempt to index local 'a' (a nil value)
2021-02-04 21:29:28: ERROR[Main]: stack traceback:
2021-02-04 21:29:28: ERROR[Main]: 	...st\minetest-5.3.0-win64\bin\..\builtin\common\vector.lua:59: in function 'distance'
2021-02-04 21:29:28: ERROR[Main]: 	.....\games\capturetheflag\mods\pvp\shooter\shooter/api.lua:397: in function 'fire_weapon'
2021-02-04 21:29:28: ERROR[Main]: 	.....\games\capturetheflag\mods\pvp\shooter\shooter/api.lua:473: in function 'fire_weapon'
2021-02-04 21:29:28: ERROR[Main]: 	.....\games\capturetheflag\mods\pvp\shooter\shooter/api.lua:97: in function <.....\games\capturetheflag\mods\pvp\shooter\shooter/api.lua:91>

So maybe its my stupidity and I didnt got everything right?
All I did was cloning this repo inside my games folder, then I had the option to start a world with that gamemode, took the singlenode mapgen and the world was started just fine, all works pretty well, but I literally cant shoot some weapons, like the standard weapon from the ranged guy or this shotgun like in the error...
Can anybody help me here? :D

Kind regards

**Comment by Anthony-De** [comment]
I had the same error. It is caused because your using 5.3.0 rather than 5.4.0.
Here is a link where you can get already compiled 5.4-dev.
https://minetest.kitsunemimi.pw/builds/

**Comment by geilmaker** [comment]
Thanks man!
Are there any problems with that minetest version, or why I cant download it from the minetest website? :D
And I was googling but cannot really find that version for linux systems, is there also an opportunity to get that on my Ubuntu 18.04 bionic server? :D

**Comment by Anthony-De** [comment]
The link I gave you is for windows. 
You should be able to compile the Linux version from here:
https://www.minetest.net/downloads/

**Comment by geilmaker** [comment]
Im sorry to take ur time, Im kinda new to this... But I can only find the 5.3 version for Ubuntu...
e.g.
https://packages.ubuntu.com/search?keywords=minetest
https://code.launchpad.net/~minetestdevs/+archive/ubuntu/daily-builds/+packages
https://launchpad.net/~minetestdevs/+archive/ubuntu/stable

**Comment by LoneWolfHT** [comment]
5.4 is the dev version of Minetest. I guess I must have accidentally used a feature from it. Doesn't matter too much now though, they're going to release it soon.

https://forum.minetest.net/viewtopic.php?f=18&t=26175 has some install instructions for Ubuntu. Although I don't think it updates your client version properly

**Comment by geilmaker** [comment]
Well thank you very much :D
So maybe its worth to wait... have you got a little more detailed explanation of soon? Might it be like 1 month? 3 months? 2 weeks? Just for me to plan a little bit 😄

**Comment by LoneWolfHT** [comment]
The forum page I linked to was for Release Candidate 1. They're basically asking for bug finders now.
I run 5.4 and the CTF server also runs on it. I'm not having any issues. It has a lot of nice features too.

**Comment by geilmaker** [comment]
So both are working on windows? Or did you clone the current repository from Github and compiled it yourself for linux? :)

**Comment by LoneWolfHT** [comment]
I self-compile Minetest on both Windows and Linux. It all worked fine.
You don't need to self-compile (On Windows at least) though thanks to that link I sent

**Comment by geilmaker** [comment]
Thanks man! :D
Do I need all these files in that repo after I compiled it myself? If not, is there any command to delete all unnecessary files from my folder?
Im so sorry for all those questions, but you are helping me out so well! :D

**Comment by LoneWolfHT** [comment]
You probably don't need to self-compile. What OS are you using?

**Comment by geilmaker** [comment]
Im using Ubuntu 18.04 on a server...
I just self-compiled it, looks like it worked pretty well, but the files are maybe not at the right directory, I get 3 warnings on starting:
2021-02-05 15:04:42: WARNING[Main]: system-wide share not found at "/usr/local/share/minetest"
2021-02-05 15:04:42: WARNING[Main]: system-wide share not found at "/usr/bin/../share/minetest"
2021-02-05 15:04:42: WARNING[Main]: system-wide share not found at "/usr/bin/.."
So can I somehow get the right files into there? Or which files are the right files...? :D

**Comment by LoneWolfHT** [comment]
That's fine I think.
I like to compile as RUN_IN_PLACE so it doesn't spread the files out everywhere.
`cmake . -DRUN_IN_PLACE=TRUE && make -j $(nproc)` to compile it that way

**Comment by geilmaker** [comment]
Okay, with the result that I can only start the server from over there, not global, right? :D
So well thanks for that advise, I'll try it out, pretty cool for me, I'll ask again if I need help, thanks very much man! :)

**Comment by geilmaker** [comment]
Its all working pretty fine, thank you so much for your help! :)
If I can just ask 1 last stupid question, when I start a world its always initialized without worldedit, then I need to stop the server, activate it in the world.mt file and then start the server again, is there a way to enable it while initializing/generating the map?
Well, not a problem at all if not, but just for my interest if its possible to go easier :)

**Comment by LoneWolfHT** [comment]
I don't think map generation starts until a player joins. You could create the world, enable the mod, then start it up and join. Unless I misunderstand you

Closing since it looks like the problem was solved. Can still keep talking though

**Comment by geilmaker** [comment]
Yea, I mean can I just pre-enable the mod for every world I do create? :D

**Comment by LoneWolfHT** [comment]
Could drop it in your game's mod folder I guess

**Comment by geilmaker** [comment]
Oh man, thank you so much! :D
All working so fine, thx man! :)
