### ISSUE TITLE
ammo not taken from marksman when they change to another class

### ISSUE THREAD

**Issue by Minetest-j45** [MT-CTF/capturetheflag#797]
i recently found out that if you are a marksman and you change class, you keep the ammo that was given to when you first switched into a marksman.

**Comment by Panquesito7** [comment]
That's normal, you keep the ammo when you previously were Sharp Shooter and then change class.
@LoneWolfHT I think this issue can be closed. Thank you.

**Comment by LoneWolfHT** [comment]
The quick fix for this would be to prevent the other classes from using ammo.
I'm working on the long fix but it'll take a while
