### ISSUE TITLE
MLG and waterBuckets

### ISSUE THREAD

**Issue by Sirius-Black4** [MT-CTF/capturetheflag#814]
It wold be nice if players could MLG water-bucket to avoid fall damage. A major number of deaths are by fall damage and if players are skilled enough can help them survive. However it can be abused by towering opponents for advantage and can help suffocate players.

**Comment by TSafa-23** [comment]
Water buckets are not used because of potential griefing

**Comment by realOneplustwo** [comment]
Close the issue
