### ISSUE TITLE
Allow ladders in team base next to wall

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#85]
Requires the check to be moved to on_place rather than is_protected, in order to get node name.

**Comment by AKryukov92** [comment]
I'll check corners of the base next time. I believe it is possible to place block 1 block above base "basement" in the corner.

**Comment by AKryukov92** [comment]
![default](https://user-images.githubusercontent.com/24266616/35781714-cc32ee84-0a17-11e8-9ab5-559a322f6079.PNG)

**Comment by AKryukov92** [comment]
It is possible only in corners. Though, I think it is enough.
