### ISSUE TITLE
Shooter mod request

### ISSUE THREAD

**Issue by Beanzilla** [MT-CTF/capturetheflag#858]
Is there a way we could make 2 separate turrets... "Rocket Turret" and "Gun Turret"?

I want to use the Shooter mod but I don't want just rockets to be fired from the turret.

Maybe make a dark red or even light red turret design for the "Rocket Turret" and use the green for the "Gun Turret"?

(I was thinking of doing this myself but it would take me awhile while I look over the existing turret/guns code)

**Comment by Beanzilla** [comment]
Oh, nevermind... it's WIP anyway.

Sorry to bother anyone.

**Comment by Beanzilla** [comment]
I thought it was WIP but the turret does work.

I change my mind, I would like to see if a "Gun Turret" could be made.

**Comment by LoneWolfHT** [comment]
What would the turret be able to do that a player can't do already with an SMG/rifle?

**Comment by Beanzilla** [comment]
Good point, I guess it's not really needed then... (Sorry for taking up anyone's time)

**Comment by LoneWolfHT** [comment]
No time wasted. It'll probably be on my mind if we ever redo any game mechanics though
