### ISSUE TITLE
Show HP when you hover on teammates

### ISSUE THREAD

**Issue by Emojigit** [MT-CTF/capturetheflag#863]
Show HP when you hover on teammates

**Comment by Emojigit** [comment]
This requires a global step which may cause lags

**Comment by LoneWolfHT** [comment]
You could do it by setting player infotext

**Comment by appgurueu** [comment]
> You could do it by setting player infotext

But that would then apply to enemies too

**Comment by appgurueu** [comment]
@savilli was this implemented?

**Comment by farooqkz** [comment]
May I ask why is this feature useful?

**Comment by LoneWolfHT** [comment]
It gives you exact numbers that you don't get from looking at player's HP bars. Maybe useful for medics.

I think if you enable a debug setting you can already see player HP in their infotext, so CTF's implementation would probably just be a prettier layer over that

**Comment by farooqkz** [comment]
I've been medic many times in game and I would say this feature is not a big deal for a medic.

**Comment by LoneWolfHT** [comment]
I will close this until someone expresses reasonable interest then

**Comment by LoneWolfHT** [comment]
Aka *won't do*, can't reproduce, duplicate, or stale issue. I disagree with the wording 'not planned' that they use as the main name.
![image](https://github.com/MT-CTF/capturetheflag/assets/28972859/ed022566-1b07-43e4-b2a7-af826f7e9292)

We don't have enough trouble with organization to fret about how issues are closed though. I'd recommend you just ignore the end of the close message for now.
