### ISSUE TITLE
The "unlocked" message is annoying

### ISSUE THREAD

**Issue by Emojigit** [MT-CTF/capturetheflag#864]
![圖片](https://user-images.githubusercontent.com/55009343/114390493-eef91d80-9bc8-11eb-9e87-f2f12034b123.png)
It blocks ALL MESSAGES sent my players.

**Comment by farooqkz** [comment]
Maybe `You've unlocked A,B,C,...` instead of current behavior?

**Comment by LoneWolfHT** [comment]
This is controlled entirely by the crafting mod, you should probably make an issue there https://github.com/rubenwardy/crafting/blob/b4ac60ba9b12db0867022ac8bf6b00338da9d56e/api.lua#L109-L117
