### ISSUE TITLE
How do I get the sniper_rifles mod without the need for ctf or ctf_flag dependency?

### ISSUE THREAD

**Issue by Beanzilla** [MT-CTF/capturetheflag#867]
I would like to have guns on my server but I don't want ctf. I have the shooter mod working without ctf but the sniper_rifles mod is more difficult to get working.

I have changed line 156 in init.lua so it checks if ctf is not nil then it will do all that.

I now get an error:

```
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'sniper_rifles' in callback item_OnSecondaryUse(): /minetest/bin/../mods/sniper_rifles/init.lua:46: attempt to call field 'set' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	/minetest/bin/../mods/sniper_rifles/init.lua:46: in function 'show_scope'
ERROR[Main]: 	/minetest/bin/../mods/sniper_rifles/init.lua:95: in function </minetest/bin/../mods/sniper_rifles/init.lua:81>
```

I will continue to try to get this to work but I was wondering if anyone else could maybe throw an idea out on how to make it optionally dependent on ctf without requiring it.

Minetest Server: 5.4.0
Minetest Client: 5.4.0

**Comment by LoneWolfHT** [comment]
You need the `physics` mod too. Could maybe put it and the sniper rifles mod together in a modpack

**Comment by Beanzilla** [comment]
Could you get a github link to the physics mod repo? (I think I have it... but maybe I don't)

**Comment by Beanzilla** [comment]
At first I thought shooters had all the guns, including the sniper rifles but as I found no the shooters mod does not.
