### ISSUE TITLE
shooter mod and sniper_rifle mod can be repaired

### ISSUE THREAD

**Issue by Beanzilla** [MT-CTF/capturetheflag#868]
I know, most of the time you are playing ctf, but for my server I wanted guns and technic.

I have encountered a strange thing that can happen.

Using technic's MV Tool Workshop (which provides the ability to repair tools), you can actually repair the guns. (using that means you only need 1 ammo for the initial load of the gun, else just reload via repairing in the tool workshop)

The reason I bring it up is because you can set a flag to indicate something like irreparable this way the workshop will not reload/repair guns.

(Just something to think about, nothing quite too important)

**Comment by Beanzilla** [comment]
Ah, I just looked at specifically technic's flashlight since I know that can't be repaired only recharged.

Then again I don't see anything where you can tell technic to not allow charging or repairing. (I need to look at the MV Workshop, I think there maybe a blacklist where we can add the items to that)

**Comment by Beanzilla** [comment]
Ok, looks like maybe we set our wear to say "ammo_mag" for the ammo inside the gun this way it doesn't trigger the ability to be repaired.

**Comment by Beanzilla** [comment]
Simply add to shooter/shooter/api.lua at line 106 make a new line and add:

```lua
wear_represents = "ammo_mag",
```

Problem solved.

**Comment by Beanzilla** [comment]
Looks like [anvil](https://github.com/minetest-mods/anvil) mod supports blacklist... just need to add in a call to make_unrepairable()

```lua
-- For the shooter mod
anvil.make_unrepairable("shooter:ammo")
anvil.make_unrepairable("shooter:flare")
anvil.make_unrepairable("shooter:pistol")
anvil.make_unrepairable("shooter:rifle")
anvil.make_unrepairable("shooter:shotgun")
anvil.make_unrepairable("shooter:machine_gun")
anvil.make_unrepairable("shooter:flaregun")
anvil.make_unrepairable("shooter:pistol")
anvil.make_unrepairable("shooter:crossbow")
-- Need to itterate over arrows and loaded crossbows
anvil.make_unrepairable("shooter:grenade")
anvil.make_unrepairable("shooter:rocket")
anvil.make_unrepairable("shooter:turret")

-- For the sniper_rifle mod
anvil.make_unrepairable("sniper_rifle:rifle_762")
anvil.make_unrepairable("sniper_rifle:rifle_magnum")
```

**Comment by Beanzilla** [comment]
No need to worry about [basic_anvil](https://github.com/MikeRedwood/basic_anvil) mod since it's recipe based.

**Comment by Beanzilla** [comment]
Looks like [cottages](https://github.com/Sokomine/cottages) mod will cause issues, and it doesn't look very easy to fix.

**Comment by LoneWolfHT** [comment]
Have you considered https://forum.minetest.net/viewtopic.php?f=9&t=15173 for your weapons instead? It's different but not attached to CTF like these mods are.

**Comment by Beanzilla** [comment]
I have, for some reason on my server it crashes on firing any gun or throwing any weapon.

I choose the ones in CTF mainly because they are simple and work out of the box. (For the most part)

Yup, see [https://github.com/Beanzilla/rangedweapons-1](https://github.com/Beanzilla/rangedweapons-1), my repo trying to help the dev who made rangedweapons.
