### ISSUE TITLE
Randomise ore spawns

### ISSUE THREAD

**Issue by rubenwardy** [MT-CTF/capturetheflag#88]
* Remove from schems
* Use function

**Comment by ClobberXD** [comment]
If this isn't implemented asap, one team will get to savour **3 Mese blocks, 6+ diamond crystals and 8+ mese crystals**, while the other team has to contend with steel swords (Bronze implements aren't really worth the long, multi-step crafting process IMO)...

**Comment by afshaan4** [comment]
yeah this happened quite a few times

**Comment by Gael-de-Sailly** [comment]
There is a function for generating ores in a chunk: `minetest.generate_ores(voxelmanip, minpos, maxpos)`
The problem is that it doesn't allow to change the ore parameters and the seed for every match.

**Comment by ClobberXD** [comment]
I was planning on using an LVM and some hacky math to manually "generate" ores, but while their rarity and proportions would be realistic, they would be chaotically scattered, and won't look natural.

**Comment by Gael-de-Sailly** [comment]
It's fully possible to generate them in clusters by Lua, just imitate the behaviour of the engine's ore spawning function for "scatter" ores (and use LVM too). Anyway a clean, natively available method would be largely preferable, but I don't think it's possible yet.

**Comment by AKryukov92** [comment]
I think that main problem is that players know where to dig ore exactly.
What if we manually create several similar maps with different ore locations?
Cave 1 will have mese around (50,50,50) while Cave 2 will have mese around (150,50,50).
Players should not see which variation of cave is used.
So they will not know exactly where to go to immediately find valuable ore.

Other idea is to make stand-alone process which will create map for next match and put it to server directory with maps.

**Comment by afshaan4** [comment]
Thats a long winded way to do things we would need a bunch more maps and all that, it would be much more elegant to *generate* the ores in code as said here:

>It's fully possible to generate them in clusters by Lua, just imitate the behaviour of the engine's ore spawning function for "scatter" ores (and use LVM too). Anyway a clean, natively available method would be largely preferable, but I don't think it's possible yet.

**Comment by Gael-de-Sailly** [comment]
Another solution, probably not the best but still worth saying: using the probability data in the map schematics. What we could do is increasing the number of ores, but giving them a lower probability value so that they won't spawn every time.
The advantage is that it's fast and natively supported (won't need any more code, just changes to the schematics).
The drawback is that ores that haven't spawned will be replaced by air instead of stone, so there will be small air holes here and there.
