### ISSUE TITLE
map_maker error

### ISSUE THREAD

**Issue by Miniontoby** [MT-CTF/capturetheflag#886]
Hello,

I run since a day a server for a friend who wants to make ctf maps,

I added ctf_map mods to the server and the server starts up with the map maker enabled.

Then he tries to make an area for the map and it crashed (see bottom for link to error)

Please help me fixing this.

- Miniontoby

Links:
- https://termbin.com/ki5d (error log)

**Comment by LoneWolfHT** [comment]
I think you ran out of memory, we get a similar error when the server runs out of RAM

**Comment by OwOBot27** [comment]
On what you edit map?IOC,Mac?

**Comment by Miniontoby** [comment]
> I think you ran out of memory, we get a similar error when the server runs out of RAM

Yeah could be


> On what you edit map?

It was on a server, with OpenBSD 

(Btw I am not a fan of Apple and I dont have it)
