### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by TableTooN** [MT-CTF/capturetheflag#903]
More Sprinting While lagg
you sprint and you have  lag, You have like infinity SPrinting.

**Comment by TableTooN** [comment]
while lagging

**Comment by Calinou** [comment]
There is no way to solve this yet. Mod code runs server-side and there's no client-side prediction for it. Fixing this would require support for server-provided client-side modding, which is not available yet (and won't be for a while).

**Comment by TableTooN** [comment]
That's In CTF

**Comment by TableTooN** [comment]
That's In CTF

**Comment by OwOBot27** [comment]
Hmm

**Comment by Emojigit** [comment]
My TMP fix suggestion: make a Dragonfire CSM which detects the keypress and predict the speed (use Deagonfire because it provide full player client-side objects since it is a hack client)
