### ISSUE TITLE
Include `playtime` mod

### ISSUE THREAD

**Issue by AFCMS** [MT-CTF/capturetheflag#922]
Thats useful to re-evaluate your life choices....
As far as I can see, this mod isn't laggy at all.
https://content.minetest.net/packages/Lejo/playtime/
https://github.com/Lejo1/playtime/

**Comment by LoneWolfHT** [comment]
I think I saw a CSM for this somewhere, I'd prefer this be done that way

**Comment by AFCMS** [comment]
With per-server storage?
Also, many people just don't know how to install CSM.

This mod contains no globalsteps, just some access to modstorage. I don't think it will increase lag at all.

**Comment by savilli** [comment]
Do we really need that in the core game? It should be installed as a separate mod on the server IMO.

**Comment by LoneWolfHT** [comment]
I directed them to the servermods repo in their PR, this is not relevant to CTF
