### ISSUE TITLE
UNwalkable leaves

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#94]
Leaves now have properties like dirt: easy to gather, can be used for 1x1 tower.
I did an experiment (cut all leaves from trees on H&L) and found that jungle trees stay close enough to each-other to jump from trunk to trunk.

I propose leaves to be unwalkable. Having different properties of different blocks makes game interesting.

**Comment by farooqkz** [comment]
But if leaves should be unwalkable to make game more realistic: +1

**Comment by tidle** [comment]
Would the player just phase through the leaves, or would they break under your feet?

**Comment by afshaan4** [comment]
Kinda fall through them
