### ISSUE TITLE
Respawn on join

### ISSUE THREAD

**Issue by appgurueu** [MT-CTF/capturetheflag#951]
Sometimes you're presented a respawn button after joining. This should be fixable trivially by setting the player's HP to max on join.

**Comment by savilli** [comment]
> This should be fixable trivially by setting the player's HP to max on join.

That already happens https://github.com/MT-CTF/capturetheflag/blob/5310f1693a967d0e37e642da4aa019b13aaa6786/mods/ctf/ctf_modebase/player.lua#L99

**Comment by savilli** [comment]
Fixed in 7dde465e8216d9854866611fa0bb936028c814da
