### ISSUE TITLE
Taking stuff out of chests while dead is possible

### ISSUE THREAD

**Issue by appgurueu** [MT-CTF/capturetheflag#962]
If you rightclick a chest before dying, you can still take stuff out of the chest while dead (that is, after your stuff has been dropped, and before your stuff is reset). I assume that the taken stuff is nuked as your inventory is set to the initial items on respawn. ~~As a (snide) side remark, using [`respawn_timer` instead of rolling your own "non-bloaty" version would've prevented this](https://github.com/appgurueu/respawn_timer/blob/master/main.lua#L210).~~

**Comment by savilli** [comment]
Looks impossible https://github.com/minetest/minetest/blob/1c5ece8334d050379eb99fe2ead52f9f4db44249/src/network/serverpackethandler.cpp#L976

**Comment by appgurueu** [comment]
> Looks impossible https://github.com/minetest/minetest/blob/1c5ece8334d050379eb99fe2ead52f9f4db44249/src/network/serverpackethandler.cpp#L976

It probably is if the player is at zero health. Is that the case in CTF though?

**Comment by savilli** [comment]
Fixed in #3536edc2ab756739818d379ce58d2d09d8d2ef5e
