### ISSUE TITLE
Falling sand and gravel

### ISSUE THREAD

**Issue by AKryukov92** [MT-CTF/capturetheflag#98]
Currently, sand and gravel don't fall down if there is an air underneath them.
I propose to let them fall down in this situation. (like in default MT)
They will be a great material to build walls because noone will be able to dig tonnel in gravel.

**Comment by afshaan4** [comment]
I agree, this would especially be useful in the cave map.

**Comment by ClobberXD** [comment]
It would be useful everywhere - the only problem is obtaining the gravel in 2Hills2Lakes and The Bridge maps... That could be alleviated by increasing gravel spawns a few blocks below the bases.

**Comment by AKryukov92** [comment]
Other option is to craft gravel out of cobblestone. 5 cobble in X shape to 5 gravel.
There is too much cobble everywhere anyway.

**Comment by rubenwardy** [comment]
The falling of nodes were disabled due to how destructive they are - it's possible to use them to make the flag drop as an item. Whilst it's possible to fix, I'm not too fussed about this feature currently

**Comment by ClobberXD** [comment]
dropping gravel on flag can be prevented by preventing gravel/sand from being placed anywhere above the flag, in a 3-block radius

**Comment by AKryukov92** [comment]
But you can place gravel 4 block high. If it ever fall down, then it drop the flag.
I think that only unwalkable blocks can be dropped as item by falling gravel.
Flag can be be changed to walkable (like fences or columns) and this will not be an issue.

**Comment by ClobberXD** [comment]
Picture a 3x3 imaginary 'tower' with it's base around the flag, extending up to the ceiling - I meant that placing gravel/sand within this imaginary tower could be disallowed.

**Comment by masterleo** [comment]
I don't really see the point of sand falling.

**Comment by ClobberXD** [comment]
The point is: (as taken from the original post)

> They will be a great material to build walls because noone will be able to dig tonnel in gravel.

It's much harder to break into a base if a wall is made up of gravel, since the hole will keep closing up until there's no more gravel above.

**Comment by masterleo** [comment]
Ok, personaly I thinks it is hard enought. Or maybe make just one map with sand ?

**Comment by MinetestSam** [comment]
If it is added then some maps would also need to be fixed as the bottom of some maps contains gravel/sand
