### ISSUE TITLE
Breath bubbles are shown incorrectly

### ISSUE THREAD

**Issue by appgurueu** [MT-CTF/capturetheflag#991]
These are full bubbles:

![Bildschirmfoto von 2022-02-12 13-05-54](https://user-images.githubusercontent.com/34514239/153710656-e5b19371-de48-4233-a5d9-24a759954e9c.png)

Bubbles are now shown as halves, the bubble bar has shrinked to half its size. Have you messed with builtin again?

**Comment by appgurueu** [comment]
> How is it different from #986?

This is not about the overlap, this is about too few bubbles being shown (only 5 bubbles instead of 10).

**Comment by savilli** [comment]
Works fine for me. How do you test?

**Comment by appgurueu** [comment]
> Works fine for me. How do you test?

I simply join with 5.5.0.

**Comment by appgurueu** [comment]
Can't reproduce anymore either. Perhaps it was just lag that drained many of my bubbles all at once and I failed to notice? Closing for now.
