### ISSUE TITLE
`give_idx` was broken

### ISSUE THREAD

**Issue by appgurueu** [MT-CTF/capturetheflag#992]
https://github.com/MT-CTF/capturetheflag/commit/44a33df238be33e671aff996568419905e1e4e0e does a `table.indexof` which will for obvious reasons fail if dropdowns are in `give_idx` mode. @savilli how about you stop directly committing to master?

**Comment by savilli** [comment]
Fixed in 29fd290d94544c41051173d74b09a0c26e836cad
